import { ind, ae, warn } from "./helpers.mjs";

/** Per-drug patches for distinctive content / unmatched drugs */
export const DRUG_PATCHES = {
  "Vitamin D3 (Cholecalciferol)": {
    indications: [ind("Vitamin D deficiency / insufficiency"), ind("Osteoporosis adjunct with calcium"), ind("Hypoparathyroidism adjunct", "moderate"), ind("CKD-related mineral bone disorder per protocols", "moderate")],
    adverse: [ae("Hypercalcemia with excess dosing", "serious"), ae("Nausea, constipation, polyuria (hypercalcemia)", "moderate"), ae("Nephrocalcinosis / renal impairment with prolonged toxicity", "serious", "moderate"), ae("Soft-tissue calcification (severe excess)", "serious", "low")],
    warnings: [warn("warning", "Megadoses without monitoring", "major", "Toxicity risk."), warn("precaution", "Granulomatous disease / primary hyperparathyroidism", "moderate", "Hypercalcemia risk.")],
    special: { pregnancy: "Deficiency treatment important — avoid excessive doses.", lactation: "Compatible at replacement doses.", renal: "Monitor calcium in CKD." },
    monitoring: ["25-OH vitamin D when indicated", "Calcium / phosphate / PTH in higher-risk regimens"],
    sourceKeys: ["dailymed", "nice", "who", "ema"],
  },
  "Ferrous sulfate": {
    indications: [ind("Iron deficiency anemia"), ind("Iron deficiency without anemia (selected)", "moderate"), ind("Prophylaxis in pregnancy when indicated", "moderate")],
    adverse: [ae("Constipation, nausea, dark stools", "common"), ae("Abdominal pain / diarrhea", "common"), ae("Accidental overdose fatal in children", "serious", "high", "Leading childhood poisoning concern"), ae("Teeth staining (liquid)", "moderate", "moderate")],
    warnings: [warn("boxed", "Keep away from children", "major", "Overdose can be fatal."), warn("warning", "Not for non-deficiency anemia", "moderate", "Risk without benefit.")],
    special: { pregnancy: "Commonly used when iron indicated.", lactation: "Compatible.", "geriatric": "Constipation / interaction with other meds." },
    monitoring: ["CBC / ferritin response", "Counsel on childproof storage"],
    sourceKeys: ["dailymed", "who", "nice", "bnf"],
  },
  "Tamsulosin": {
    indications: [ind("BPH lower urinary tract symptoms"), ind("Medical expulsive therapy for ureteral stones (off-label common)", "moderate", false), ind("Urinary retention adjunct selected contexts", "moderate")],
    adverse: [ae("Dizziness / orthostatic hypotension", "common"), ae("Retrograde ejaculation", "common"), ae("Rhinitis", "common", "moderate"), ae("Intraoperative floppy iris syndrome (cataract surgery)", "serious", "moderate"), ae("Priapism (rare)", "serious", "low")],
    warnings: [warn("warning", "Cataract/glaucoma surgery — warn ophthalmologist", "major", "IFIS risk."), warn("precaution", "Orthostasis — careful with PDE5 inhibitors", "moderate", "Hypotension.")],
    special: { pregnancy: "Not indicated in women.", hepatic: "Caution severe impairment.", renal: "Generally usable." },
    monitoring: ["BP / dizziness", "PSA evaluation as appropriate for BPH care"],
    sourceKeys: ["dailymed", "nice", "ema", "bnf"],
  },
  "Finasteride": {
    indications: [ind("BPH"), ind("Androgenetic alopecia (1 mg)"), ind("Hirsutism (off-label)", "moderate", false)],
    adverse: [ae("Decreased libido / erectile dysfunction / ejaculation disorder", "common", "moderate"), ae("Breast tenderness / gynecomastia", "moderate"), ae("Depression / suicidal ideation reports (labeled warnings evolving)", "serious", "moderate"), ae("High-grade prostate cancer detection signal (PCPT context)", "serious", "moderate", "Labeled — discuss screening implications")],
    warnings: [warn("contraindication", "Pregnancy — crushed/broken tablets teratogenic risk to male fetus", "major", "Women who are/may be pregnant should not handle."), warn("warning", "Blood donation restrictions (product-specific)", "moderate", "See label."), warn("warning", "Mood changes — discontinue and seek help if depression", "moderate", "MHRA/FDA communications.")],
    special: { pregnancy: "Absolute avoidance of handling crushed tabs by pregnant persons.", lactation: "Not indicated." },
    monitoring: ["PSA interpretation (halves PSA roughly)", "Sexual/mood AEs counseling"],
    sourceKeys: ["dailymed", "mhra", "ema", "fda", "nice"],
  },
  "Melatonin": {
    indications: [ind("Insomnia / jet lag (jurisdiction-dependent licensing)", "moderate", true, "Regulated as medicine in some regions, supplement in others"), ind("Circadian rhythm sleep disorders (selected)", "moderate"), ind("Pediatric sleep in neurodevelopmental disorders (specialist)", "moderate", false)],
    adverse: [ae("Daytime drowsiness, headache", "common", "moderate"), ae("Vivid dreams", "common", "moderate"), ae("Hormonal concerns theoretical with chronic pediatric use", "moderate", "low", "Evidence uncertain")],
    warnings: [warn("precaution", "Quality variability of supplements", "moderate", "Prefer regulated products where possible."), warn("precaution", "Driving next morning if sedated", "moderate", "Individual response.")],
    special: { pregnancy: "Insufficient data — avoid unless advised.", lactation: "Discuss.", pediatric: "Specialist guidance preferred." },
    monitoring: ["Sleep hygiene first-line emphasis", "Duration of use"],
    sourceKeys: ["ema", "nice", "mhra", "bnf"],
  },
  "Oseltamivir": {
    indications: [ind("Influenza treatment (within early symptom window)"), ind("Influenza post-exposure prophylaxis as labeled"), ind("Severe influenza / hospitalized (guidelines)", "moderate")],
    adverse: [ae("Nausea, vomiting", "common"), ae("Headache", "common", "moderate"), ae("Neuropsychiatric events reported (esp. pediatrics — causality debated)", "serious", "moderate"), ae("Severe skin reactions (rare)", "serious", "low")],
    warnings: [warn("warning", "Start early for outpatient benefit", "moderate", "Benefit diminishes with delayed start."), warn("precaution", "Renal impairment — dose adjust", "moderate", "Important.")],
    special: { pregnancy: "Often recommended when influenza treated — benefits may outweigh risks.", renal: "Adjust dose.", pediatric: "Age/weight dosing." },
    monitoring: ["Symptom onset timing", "Renal dosing", "Mood/behavior unusual changes"],
    sourceKeys: ["dailymed", "cdc_stis", "ema", "who", "nice"],
  },
  "Aciclovir (Acyclovir)": {
    indications: [ind("Herpes zoster"), ind("Genital herpes treatment/suppression"), ind("Herpes labialis"), ind("HSV encephalitis (IV)", "high"), ind("Varicella in selected high-risk patients", "moderate")],
    adverse: [ae("Nausea, headache, malaise", "common", "moderate"), ae("Crystalluria / nephrotoxicity (IV high dose)", "serious"), ae("Neurotoxicity in renal impairment (confusion, tremor)", "serious", "moderate"), ae("Thrombotic microangiopathy reports (rare high dose)", "serious", "low")],
    warnings: [warn("warning", "Hydration with IV therapy", "major", "Renal toxicity prevention."), warn("precaution", "Renal impairment — adjust", "moderate", "Critical.")],
    special: { pregnancy: "Extensively used when indicated.", lactation: "Compatible.", renal: "Dose adjust." },
    monitoring: ["Renal function with IV", "Hydration", "Lesion response"],
    sourceKeys: ["dailymed", "cdc_stis", "ema", "bnf"],
  },
  "Hydroxychloroquine": {
    indications: [ind("Rheumatoid arthritis"), ind("Systemic lupus erythematosus"), ind("Malaria treatment/prophylaxis as labeled"), ind("COVID-19 outpatient (not established for routine use)", "low", false, "Large RCTs did not support routine benefit — historical misuse caution")],
    adverse: [ae("Nausea, rash, headache", "common", "moderate"), ae("Retinopathy with long-term use", "serious"), ae("QT prolongation / cardiomyopathy (rare)", "serious", "moderate"), ae("Hypoglycemia", "moderate", "moderate"), ae("Hemolysis in G6PD deficiency (more with primaquine; caution)", "serious", "moderate")],
    warnings: [warn("warning", "Ophthalmologic monitoring for long-term therapy", "major", "Dose/duration-dependent retinopathy."), warn("warning", "Not established for COVID-19 treatment in general population", "moderate", "Avoid non-evidence-based use."), warn("precaution", "QT risk drugs / cardiac disease", "moderate", "ECG considerations.")],
    special: { pregnancy: "Often continued for lupus — specialist care.", lactation: "Generally considered compatible.", renal: "Dose adjust.", hepatic: "Caution." },
    monitoring: ["Baseline and periodic ophthalmology per guidelines", "CBC/LFTs as indicated", "ECG if QT risk"],
    whyStillPrescribed: "Foundation therapy for SLE and useful DMARD for RA with retinopathy risk managed by dosing and eye screening — COVID use not established.",
    sourceKeys: ["dailymed", "fda", "ema", "nice", "who"],
  },
  "Paxlovid (nirmatrelvir/ritonavir)": {
    indications: [ind("Mild-to-moderate COVID-19 in high-risk patients to reduce progression", "high"), ind("Not for pre-exposure prophylaxis as primary labeled use", "moderate", false)],
    adverse: [ae("Dysgeusia (taste disturbance), diarrhea", "common"), ae("Hypertension, myalgia", "common", "moderate"), ae("Hypersensitivity", "serious", "low"), ae("Rebound symptoms reported after course (observational)", "moderate", "moderate", "Clinical significance variable")],
    warnings: [warn("warning", "Extensive ritonavir CYP3A drug interactions", "major", "Many contraindications — mandatory interaction check."), warn("contraindication", "Strong CYP3A inducers / many interacting drugs", "major", "See checklist."), warn("precaution", "Severe renal/hepatic impairment", "major", "Dose adjust or avoid.")],
    special: { pregnancy: "Discuss; limited data — risk–benefit in high-risk pregnant patients.", lactation: "Discuss.", renal: "Dose adjust eGFR 30–59; avoid <30 (US label concepts).", hepatic: "Avoid severe." },
    monitoring: ["Full medication reconciliation before prescribing", "Renal function", "Symptom course"],
    whyStillPrescribed: "Oral antiviral with RCT evidence for reducing hospitalization/death in high-risk outpatients when started early — interaction burden is the main operational constraint.",
    sourceKeys: ["dailymed", "fda", "ema", "who", "nice", "nih_covid"],
  },
  "Diltiazem": {
    drugClass: "Non-DHP calcium channel blocker",
    indications: [ind("Hypertension"), ind("Chronic stable angina"), ind("Rate control in atrial fibrillation/flutter"), ind("IV for acute rate control (selected)", "moderate")],
    adverse: [ae("Bradycardia, constipation, edema", "common"), ae("AV block / HF exacerbation", "serious"), ae("Hypotension", "moderate"), ae("Gingival hyperplasia", "moderate", "moderate")],
    warnings: [warn("contraindication", "Sick sinus / high-grade AV block without pacemaker; acute MI with pulmonary congestion (selected labels)", "major", "See label."), warn("warning", "CYP3A4 interactions (statins, etc.)", "major", "Myopathy and other risks."), warn("warning", "Beta-blocker combinations — additive bradycardia", "moderate", "Monitor.")],
    special: { pregnancy: "Discuss alternatives.", hepatic: "Caution.", renal: "Caution." },
    monitoring: ["HR/BP", "ECG if conduction disease", "HF symptoms", "Drug interactions"],
    sourceKeys: ["dailymed", "ema", "nice", "esc_hf"],
  },
  "Verapamil": {
    drugClass: "Non-DHP calcium channel blocker",
    indications: [ind("Hypertension"), ind("Angina"), ind("Rate control / SVT (selected)"), ind("Cluster headache prophylaxis (off-label high-dose specialist)", "moderate", false)],
    adverse: [ae("Constipation (prominent)", "common"), ae("Bradycardia / AV block", "serious"), ae("HF precipitation", "serious"), ae("Hypotension, edema", "moderate")],
    warnings: [warn("contraindication", "Severe LV dysfunction / sick sinus / AV block without pacemaker", "major", "See label."), warn("warning", "Beta-blocker coadministration risks", "major", "Additive cardiodepression."), warn("warning", "CYP3A4 inhibitor — many interactions", "major", "Including colchicine, some statins.")],
    special: { pregnancy: "Discuss.", hepatic: "Dose reduce.", geriatric: "Constipation / bradycardia." },
    monitoring: ["HR/BP", "Constipation management", "Interaction check"],
    sourceKeys: ["dailymed", "ema", "nice", "bnf"],
  },
  "Ceftriaxone": {
    indications: [ind("Community-acquired / hospital infections as labeled"), ind("Gonorrhea (guideline regimens — note resistance)", "high"), ind("Meningitis / endocarditis (selected)", "high"), ind("Lyme (selected neurologic)", "moderate"), ind("Surgical prophylaxis (selected)", "moderate")],
    adverse: [ae("Diarrhea, rash", "common"), ae("Biliary sludge / cholecystitis-like pain", "moderate"), ae("Hypersensitivity / anaphylaxis", "serious"), ae("C. difficile infection", "serious"), ae("Hemolytic anemia (rare)", "serious", "low")],
    warnings: [warn("contraindication", "Neonates with hyperbilirubinemia / calcium-containing IV solutions in neonates", "major", "Precipitation risk."), warn("warning", "Penicillin-allergic cross-reactivity considerations", "moderate", "Risk stratified.")],
    special: { pregnancy: "Often used when indicated.", lactation: "Compatible.", hepatic: "Biliary excretion — sludge.", renal: "Usually no adjust unless combined severe hepatic+renal." },
    monitoring: ["Allergy history", "C. difficile symptoms", "Biliary symptoms with prolonged use"],
    sourceKeys: ["dailymed", "cdc_stis", "ema", "idsa", "bnf"],
  },
  "Gentamicin": {
    indications: [ind("Serious gram-negative infections"), ind("Synergy in selected endocarditis/gram-positive regimens", "moderate"), ind("UTI when susceptible (selected)", "moderate")],
    adverse: [ae("Nephrotoxicity", "serious"), ae("Ototoxicity (cochlear/vestibular — may be irreversible)", "serious"), ae("Neuromuscular blockade (rare)", "serious", "low")],
    warnings: [warn("boxed", "Nephrotoxicity and ototoxicity", "major", "Monitor levels/renal function."), warn("precaution", "Pregnancy — fetal ototoxicity risk", "major", "Use only if no safer alternative.")],
    special: { pregnancy: "Avoid if possible — fetal 8th nerve toxicity.", renal: "Dose by levels/renal function.", geriatric: "High toxicity risk." },
    monitoring: ["Serum levels", "Creatinine", "Hearing/balance symptoms"],
    whyStillPrescribed: "Bactericidal activity against serious gram-negatives remains important; toxicity mandates stewardship and monitoring.",
    sourceKeys: ["dailymed", "ema", "idsa", "bnf", "who"],
  },
  "Vancomycin": {
    indications: [ind("Serious MRSA / gram-positive infections"), ind("C. difficile infection (oral vancomycin)", "high"), ind("Surgical prophylaxis in beta-lactam allergy (selected)", "moderate")],
    adverse: [ae("Nephrotoxicity", "serious"), ae("Vancomycin infusion reaction (histamine red man syndrome)", "common"), ae("Ototoxicity (rare)", "serious", "low"), ae("Neutropenia with prolonged use", "moderate", "moderate")],
    warnings: [warn("warning", "Infuse slowly to reduce infusion reaction", "moderate", "Counseling/nursing point."), warn("warning", "Monitor AUC/trough per guidelines", "major", "Nephrotoxicity risk.")],
    special: { pregnancy: "Use if clearly needed.", lactation: "Oral poorly absorbed — discuss.", renal: "Major dose adjustments." },
    monitoring: ["AUC/trough levels", "Creatinine", "CBC prolonged courses"],
    sourceKeys: ["dailymed", "idsa", "ema", "bnf"],
  },
  "Metronidazole": {
    indications: [ind("Anaerobic infections"), ind("Bacterial vaginosis / trichomoniasis"), ind("C. difficile (selected regimens)"), ind("Amebiasis / giardiasis"), ind("H. pylori regimens", "high")],
    adverse: [ae("Nausea, metallic taste", "common"), ae("Disulfiram-like reaction with alcohol", "moderate"), ae("Peripheral neuropathy with prolonged use", "serious"), ae("CNS toxicity (rare seizures/encephalopathy)", "serious", "low"), ae("Mutagenicity concerns / boxed carcinogenic warning in US label", "serious", "moderate", "Use only for approved indications")],
    warnings: [warn("boxed", "Carcinogenicity in mice/rats — unnecessary use discouraged (US)", "major", "Still widely used for labeled infections."), warn("warning", "Avoid alcohol during and for period after", "moderate", "Disulfiram-like reaction."), warn("warning", "Warfarin potentiation", "moderate", "INR rise.")],
    special: { pregnancy: "Used when indicated (e.g., trichomonas) — discuss trimester nuances.", lactation: "May interrupt briefly for high dose — discuss.", hepatic: "Dose reduce severe impairment." },
    monitoring: ["Alcohol counseling", "Neuropathy with long courses", "INR if on warfarin"],
    sourceKeys: ["dailymed", "cdc_stis", "ema", "bnf"],
  },
  "Fluconazole": {
    indications: [ind("Candidiasis (mucosal / systemic as labeled)"), ind("Cryptococcal meningitis maintenance"), ind("Prophylaxis in selected immunocompromised", "moderate"), ind("Tinea / onychomycosis (selected — alternatives often preferred)", "moderate")],
    adverse: [ae("Headache, GI upset, rash", "common"), ae("Hepatotoxicity", "serious"), ae("QT prolongation", "serious", "moderate"), ae("Severe cutaneous reactions (rare)", "serious", "low")],
    warnings: [warn("warning", "Embryo-fetal toxicity with high-dose/chronic first trimester exposure concerns", "major", "Single low-dose thrush treatment often still considered — discuss."), warn("warning", "CYP2C9/3A4 interactions (warfarin, some statins, etc.)", "major", "Check interactions."), warn("warning", "QT risk drugs", "moderate", "Additive risk.")],
    special: { pregnancy: "Avoid high-dose/chronic; single 150 mg for VVC often discussed as lower concern.", hepatic: "Monitor.", renal: "Adjust for some indications." },
    monitoring: ["LFTs with prolonged therapy", "Drug interactions", "ECG if QT risk"],
    sourceKeys: ["dailymed", "ema", "cdc_stis", "bnf"],
  },
  "Terbinafine": {
    indications: [ind("Onychomycosis"), ind("Tinea corporis/cruris/pedis (oral/topical as labeled)")],
    adverse: [ae("Headache, GI upset, taste disturbance", "common"), ae("Hepatotoxicity", "serious"), ae("Severe skin reactions (rare)", "serious", "low"), ae("Depression / taste loss prolonged (uncommon)", "moderate", "moderate")],
    warnings: [warn("warning", "Liver disease — check LFTs", "major", "Discontinue if liver injury."), warn("warning", "CYP2D6 inhibition interactions", "moderate", "Check interacting drugs.")],
    special: { pregnancy: "Prefer defer oral therapy if possible.", hepatic: "Contraindicated in chronic/active liver disease.", renal: "Caution." },
    monitoring: ["Baseline LFTs", "Repeat if symptoms", "Taste changes"],
    sourceKeys: ["dailymed", "ema", "bnf"],
  },
  "Gliclazide": {
    indications: [ind("Type 2 diabetes mellitus")],
    adverse: [ae("Hypoglycemia", "serious"), ae("Weight gain", "common", "moderate"), ae("GI upset", "common", "moderate"), ae("Rare hyponatremia / hematologic reactions", "serious", "low")],
    warnings: [warn("warning", "Hypoglycemia risk — especially elderly/renal impairment", "major", "Prefer lower-hypoglycemia agents when appropriate per ADA/EASD."), warn("contraindication", "Type 1 diabetes / DKA", "major", "Not indicated.")],
    special: { pregnancy: "Insulin preferred.", renal: "Caution — hypo risk.", hepatic: "Caution.", geriatric: "Hypoglycemia — consider deprescribing." },
    monitoring: ["Glucose / HbA1c", "Hypoglycemia education"],
    whyStillPrescribed: "Affordable insulin secretagogue still used globally; newer agents often preferred when cost/access allow due to hypo and weight effects and fewer cardiorenal benefits.",
    sourceKeys: ["dailymed", "ada_diabetes", "nice", "ema", "who"],
  },
  "Sitagliptin": {
    indications: [ind("Type 2 diabetes mellitus")],
    adverse: [ae("Nasopharyngitis, headache", "common", "moderate"), ae("Joint pain (DPP-4 class reports)", "moderate", "moderate"), ae("Pancreatitis (uncommon — labeled)", "serious", "moderate"), ae("Bullous pemphigoid (rare)", "serious", "low"), ae("HF hospitalization signal debated across class (saxagliptin/alogliptin stronger)", "serious", "moderate", "Sitagliptin generally more neutral in trials")],
    warnings: [warn("warning", "Pancreatitis — discontinue if suspected", "moderate", "Labeled."), warn("precaution", "Renal dose adjustment", "moderate", "Required."), warn("warning", "HF risk not uniform across DPP-4 inhibitors", "moderate", "Agent-specific data.")],
    special: { pregnancy: "Limited data — usually not first-line.", renal: "Dose adjust.", geriatric: "Often well tolerated." },
    monitoring: ["Renal function for dosing", "Glucose / HbA1c", "Pancreatitis symptoms"],
    sourceKeys: ["dailymed", "ada_diabetes", "ema", "nice"],
  },
  "Ezetimibe": {
    indications: [ind("Primary hyperlipidemia ± statin"), ind("Homozygous familial hypercholesterolemia adjunct"), ind("Sitosterolemia", "moderate")],
    adverse: [ae("Diarrhea, arthralgia, fatigue", "common", "moderate"), ae("Elevated LFTs especially with statin", "moderate"), ae("Myopathy rare alone; higher with statin", "serious", "moderate")],
    warnings: [warn("precaution", "Active liver disease when combined with statin", "moderate", "Follow statin rules."), warn("warning", "Cyclosporine interaction", "moderate", "Levels may rise.")],
    special: { pregnancy: "Avoid combo lipid therapy generally.", hepatic: "Caution moderate-severe." },
    monitoring: ["Lipids", "LFTs when with statin"],
    whyStillPrescribed: "LDL-lowering add-on with outcome support in IMPROVE-IT-style contexts when added to statin post-ACS; well tolerated.",
    sourceKeys: ["dailymed", "ema", "nice", "aha_hypertension"],
  },
  "Fenofibrate": {
    indications: [ind("Severe hypertriglyceridemia"), ind("Mixed dyslipidemia adjunct (selected)"), ind("Diabetic retinopathy progression adjunct (some regions — fenofibrate)", "moderate", true, "Jurisdiction-specific evidence/labeling")],
    adverse: [ae("Elevated LFTs", "common", "moderate"), ae("Myopathy risk especially with statin", "serious"), ae("Cholelithiasis", "moderate"), ae("Increased creatinine (hemodynamic)", "moderate"), ae("Pancreatitis (paradoxical with trigs still high)", "serious", "moderate")],
    warnings: [warn("warning", "Gallbladder disease", "moderate", "May increase cholesterol excretion into bile."), warn("warning", "Statin combination — myopathy", "major", "Use carefully."), warn("contraindication", "Severe renal/hepatic / gallbladder disease (selected)", "major", "See label.")],
    special: { pregnancy: "Avoid.", renal: "Dose adjust/avoid.", hepatic: "Monitor/avoid active disease." },
    monitoring: ["LFTs", "Creatinine", "CK if muscle symptoms", "Triglycerides"],
    sourceKeys: ["dailymed", "ema", "nice", "ada_diabetes"],
  },
  "Clonidine": {
    indications: [ind("Hypertension"), ind("ADHD (extended-release — labeled US)", "high"), ind("Menopausal flushing / withdrawal adjuncts (off-label)", "moderate", false), ind("Opioid/alcohol withdrawal supportive (off-label)", "moderate", false)],
    adverse: [ae("Dry mouth, sedation, dizziness", "common"), ae("Bradycardia / hypotension", "serious", "moderate"), ae("Rebound hypertension with abrupt withdrawal", "serious"), ae("Depression", "moderate", "moderate")],
    warnings: [warn("warning", "Do not stop abruptly", "major", "Rebound hypertension."), warn("precaution", "CNS depressant co-use", "moderate", "Sedation.")],
    special: { pregnancy: "Not preferred antihypertensive.", lactation: "May decrease prolactin — discuss.", renal: "Dose adjust." },
    monitoring: ["BP/HR", "Sedation", "Taper plan"],
    withdrawal: "Taper to avoid rebound hypertension and sympathetic overactivity.",
    sourceKeys: ["dailymed", "aha_hypertension", "ema", "nice"],
  },
  "Doxazosin": {
    indications: [ind("Hypertension (not usually first-line)"), ind("BPH symptoms")],
    adverse: [ae("First-dose hypotension / syncope", "serious"), ae("Dizziness, fatigue", "common"), ae("Edema", "common", "moderate"), ae("Intraoperative floppy iris syndrome", "serious", "moderate")],
    warnings: [warn("warning", "First-dose effect — bedtime start counseling", "major", "Fall/syncope risk."), warn("precaution", "HF (ALLHAT doxazosin arm concerns for HTN monotherapy)", "moderate", "Not first-line for HTN.")],
    special: { pregnancy: "Limited data.", geriatric: "Fall risk high.", hepatic: "Caution." },
    monitoring: ["BP especially first doses", "Fall risk"],
    whyStillPrescribed: "Useful for BPH and as add-on antihypertensive; not preferred first-line HTN monotherapy after outcome trial signals.",
    sourceKeys: ["dailymed", "aha_hypertension", "nice", "ema"],
  },
  "Mirabegron": {
    indications: [ind("Overactive bladder (urge incontinence / frequency / urgency)")],
    adverse: [ae("Hypertension", "common"), ae("Nasopharyngitis, UTI, headache", "common", "moderate"), ae("Urinary retention (less than anticholinergics typically)", "moderate", "moderate"), ae("Angioedema (rare)", "serious", "low")],
    warnings: [warn("warning", "Uncontrolled hypertension", "major", "Do not use if severe uncontrolled HTN per label."), warn("warning", "CYP2D6 inhibition interactions", "moderate", "Check substrates."), warn("precaution", "Bladder outlet obstruction", "moderate", "Retention risk.")],
    special: { pregnancy: "Avoid unless necessary.", renal: "Dose limits.", hepatic: "Dose limits.", geriatric: "BP monitoring." },
    monitoring: ["BP", "Continence outcomes", "Retention symptoms"],
    sourceKeys: ["dailymed", "nice", "ema", "bnf"],
  },
  "Oxybutynin": {
    indications: [ind("Overactive bladder"), ind("Neurogenic bladder detrusor overactivity")],
    adverse: [ae("Dry mouth, constipation, blurred vision", "common"), ae("Cognitive impairment / delirium risk (esp. elderly)", "serious", "moderate"), ae("Urinary retention", "moderate"), ae("Heat intolerance / anhidrosis risk", "moderate", "moderate")],
    warnings: [warn("precaution", "Elderly / dementia (Beers Criteria — avoid if possible)", "major", "Anticholinergic cognitive burden."), warn("contraindication", "Uncontrolled narrow-angle glaucoma / urinary retention / GI obstruction (selected)", "major", "See label.")],
    special: { pregnancy: "Discuss.", lactation: "Discuss.", geriatric: "Prefer alternatives (mirabegron, newer agents, non-drug)." },
    monitoring: ["Continence vs anticholinergic AEs", "Cognitive changes", "Post-void residual if obstruction risk"],
    whyStillPrescribed: "Older, inexpensive antimuscarinic still used; cognitive and anticholinergic burden push many guidelines toward alternatives in older adults.",
    sourceKeys: ["dailymed", "nice", "ema", "bnf"],
  },
  // Exemplar deepenings for key thin meds already class-matched
  "Omeprazole": {
    withdrawal: "Rebound acid hypersecretion may occur after prolonged PPI therapy; step-down or on-demand strategies sometimes used when deprescribing.",
    adverse: [ae("Cutaneous lupus / SLE flare reports (rare)", "serious", "low"), ae("Fundic gland polyps", "common", "moderate")],
    sourceKeys: ["label_omeprazole", "fda_ppi_magnesium"],
  },
  "Warfarin": {
    longTermEvidence: "Decades of use with INR-guided therapy; DOACs preferred for many NVAF/VTE patients but warfarin remains essential for mechanical valves and selected APS.",
  },
  "Sertraline": {
    longTermEvidence: "Maintenance therapy reduces relapse in recurrent depression; sexual side effects and discontinuation symptoms remain clinically important long-term considerations.",
  },
  "Metformin": {
    adverse: [ae("Lactic acidosis (rare when eGFR/hypoxia cautions followed)", "serious", "high", "Boxed warning — absolute risk low in appropriately selected patients")],
  },
  "Levofloxacin": {
    whyStillPrescribed: "Broad gram-negative and atypical coverage useful for selected serious infections; FDA advises reserving for situations without safer alternatives for many uncomplicated indications.",
  },
  "Atorvastatin": {
    indications: [ind("Primary prevention in diabetes / elevated risk as labeled/guidelines"), ind("Secondary prevention post-ACS")],
  },
  "Amoxicillin": {
    indications: [ind("Dental infections as labeled/guidelines", "moderate"), ind("Lyme disease early (alternative regimens region-dependent)", "moderate")],
  },
};
