import { stdReg, ind, ae, warn } from "./helpers.mjs";
import { CLASS_TEMPLATES } from "./class-templates-more.mjs";
import { mergeMed } from "./helpers.mjs";

function base(genericName, brandNames, drugClass, mechanism, extras = {}) {
  return {
    genericName,
    brandNames,
    drugClass,
    mechanism,
    routes: extras.routes || ["oral"],
    regulatoryStatus: { ...stdReg },
    evidenceQualityOverview: extras.evidenceQualityOverview || "Supported by regulatory labeling and major clinical guidelines; see product-specific evidence.",
    benefitsSummary: extras.benefitsSummary || `${genericName} is used for labeled indications within the ${drugClass} class.`,
    whyStillPrescribed: extras.whyStillPrescribed ?? null,
    longTermEvidence: extras.longTermEvidence ?? null,
    indications: extras.indications || [ind("See labeling for approved indications"), ind("Guideline-supported uses within class", "moderate")],
    adverse: extras.adverse || [ae("See class adverse effect profile", "common", "moderate"), ae("Hypersensitivity (rare)", "serious", "low"), ae("Class-specific serious risks — review labeling", "serious", "moderate")],
    warnings: extras.warnings || [warn("warning", "Review full labeling", "moderate", "Contraindications and interactions are product-specific.")],
    special: extras.special ?? null,
    monitoring: extras.monitoring ?? null,
    withdrawal: extras.withdrawal ?? null,
    sourceKeys: extras.sourceKeys || ["dailymed", "ema", "nice", "bnf"],
  };
}

/** Apply matching class templates to a stub med */
function withClass(m) {
  let out = m;
  for (const t of Object.values(CLASS_TEMPLATES)) {
    if (t.match(out)) out = mergeMed(out, t.patch);
  }
  return out;
}

const stubs = [
  base("Lansoprazole", ["Prevacid"], "Proton pump inhibitor (PPI)", "Irreversibly inhibits gastric H+/K+-ATPase.", { sourceKeys: ["dailymed","ema","nice","fda_ppi_magnesium"], benefitsSummary: "PPI for GERD, erosive esophagitis, ulcers, and H. pylori regimens as labeled." }),
  base("Rabeprazole", ["Aciphex", "Pariet"], "Proton pump inhibitor (PPI)", "Inhibits gastric proton pump.", { sourceKeys: ["dailymed","ema","nice","fda_ppi_magnesium"] }),
  base("Dexlansoprazole", ["Dexilant"], "Proton pump inhibitor (PPI)", "R-enantiomer of lansoprazole; dual delayed-release PPI.", { sourceKeys: ["dailymed","ema","fda_ppi_magnesium"] }),
  base("Diclofenac", ["Voltaren", "Cataflam"], "NSAID", "COX inhibition reducing prostaglandins.", { sourceKeys: ["dailymed","label_ibuprofen","ema","fda"], benefitsSummary: "NSAID analgesic/anti-inflammatory; topical and systemic forms — systemic use carries boxed CV/GI warnings.", whyStillPrescribed: "Effective for inflammatory pain; topical diclofenac may offer lower systemic exposure for some joint pains." }),
  base("Celecoxib", ["Celebrex"], "NSAID", "Selective COX-2 inhibition.", { sourceKeys: ["dailymed","label_ibuprofen","ema","fda"], benefitsSummary: "COX-2 selective NSAID that may reduce some GI ulcer risk vs nonselective NSAIDs but retains CV risk boxed warning.", warnings: [warn("boxed","CV thrombotic risk","major","COX-2 selectives retain serious CV risk warnings."), warn("contraindication","Sulfa allergy (celecoxib)","major","Sulfonamide structure — contraindicated in sulfonamide allergy per label."), warn("boxed","GI risk still present","major","Serious GI events can occur.")] }),
  base("Meloxicam", ["Mobic"], "NSAID", "Preferential COX-2 inhibition at lower doses; NSAID class effects.", { sourceKeys: ["dailymed","label_ibuprofen","ema"] }),
  base("Indomethacin", ["Indocin"], "NSAID", "Potent nonselective COX inhibition.", { sourceKeys: ["dailymed","label_ibuprofen","ema"], whyStillPrescribed: "Still used for gout flares, ankylosing spondylitis, and specialized indications despite CNS and GI toxicity profile." }),
  base("Ketorolac", ["Toradol"], "NSAID", "Potent nonselective COX inhibition — short-term analgesia.", { routes: ["oral","IM","IV","nasal"], sourceKeys: ["dailymed","label_ibuprofen","ema","fda"], warnings: [warn("boxed","Short-term use only; GI/renal/bleeding risk","major","Systemic ketorolac limited to short courses (e.g., ≤5 days) in labeling."), warn("contraindication","Labor/delivery / significant renal impairment / high bleeding risk","major","See label.")] }),
  base("Enalapril", ["Vasotec", "Renitec"], "ACE inhibitor", "ACE inhibition reducing angiotensin II.", { sourceKeys: ["dailymed","aha_hypertension","esc_hf","ema"] }),
  base("Perindopril", ["Coversyl", "Aceon"], "ACE inhibitor", "ACE inhibition.", { sourceKeys: ["dailymed","aha_hypertension","esc_hf","ema","nice"] }),
  base("Benazepril", ["Lotensin"], "ACE inhibitor", "ACE inhibition.", { sourceKeys: ["dailymed","aha_hypertension","ema"] }),
  base("Valsartan", ["Diovan"], "Angiotensin II receptor blocker (ARB)", "AT1 receptor blockade.", { sourceKeys: ["dailymed","aha_hypertension","esc_hf","ema"], benefitsSummary: "ARB for hypertension and HFrEF as labeled; historically subject to nitrosamine recalls — use current approved products." }),
  base("Irbesartan", ["Avapro", "Aprovel"], "Angiotensin II receptor blocker (ARB)", "AT1 receptor blockade.", { sourceKeys: ["dailymed","aha_hypertension","ema"], indications: [ind("Hypertension"), ind("Diabetic nephropathy in type 2 diabetes with hypertension")] }),
  base("Olmesartan", ["Benicar", "Olmetec"], "Angiotensin II receptor blocker (ARB)", "AT1 receptor blockade.", { sourceKeys: ["dailymed","aha_hypertension","ema","fda"], warnings: [warn("warning","Sprue-like enteropathy","moderate","Rare severe chronic diarrhea/weight loss — discontinue if suspected."), warn("boxed","Pregnancy fetal toxicity","major","Discontinue when pregnancy detected.")] }),
  base("Telmisartan", ["Micardis"], "Angiotensin II receptor blocker (ARB)", "AT1 receptor blockade.", { sourceKeys: ["dailymed","aha_hypertension","ema"] }),
  base("Carvedilol", ["Coreg"], "Beta blocker (nonselective with alpha-1 blockade)", "Nonselective beta blockade plus alpha-1 blockade.", { sourceKeys: ["dailymed","esc_hf","aha_hypertension","ema"], benefitsSummary: "Evidence-based HFrEF beta blocker; also used for hypertension and post-MI as labeled.", indications: [ind("HFrEF"), ind("Hypertension"), ind("Post-MI LV dysfunction as labeled")] }),
  base("Propranolol", ["Inderal"], "Beta blocker (nonselective)", "Nonselective beta-adrenergic blockade.", { sourceKeys: ["dailymed","ema","nice","bnf"], indications: [ind("Hypertension / angina / arrhythmia as labeled"), ind("Migraine prophylaxis"), ind("Essential tremor"), ind("Performance anxiety (off-label common)", "moderate", false), ind("Thyrotoxicosis symptomatic control", "moderate")], whyStillPrescribed: "CNS-penetrant nonselective agent useful for migraine, tremor, and portal hypertension variceal bleeding prophylaxis contexts despite asthma contraindications." }),
  base("Nebivolol", ["Bystolic", "Nebilet"], "Beta-1 selective blocker", "Beta-1 selective blockade with nitric oxide–mediated vasodilation.", { sourceKeys: ["dailymed","aha_hypertension","ema"] }),
  base("Labetalol", ["Trandate"], "Beta blocker (combined alpha/beta)", "Combined alpha-1 and beta blockade.", { routes: ["oral","IV"], sourceKeys: ["dailymed","aha_hypertension","acog","nice"], benefitsSummary: "Frequently used for hypertension in pregnancy and acute hypertensive management IV.", whyStillPrescribed: "Preferred agent in many pregnancy hypertension protocols." }),
  base("Nifedipine", ["Adalat", "Procardia"], "Dihydropyridine calcium channel blocker", "L-type calcium channel blockade — arterial vasodilation.", { sourceKeys: ["dailymed","aha_hypertension","acog","ema"], benefitsSummary: "Long-acting nifedipine used for hypertension including pregnancy contexts; avoid short-acting capsules for acute BP misuse." }),
  base("Felodipine", ["Plendil"], "Dihydropyridine calcium channel blocker", "Vascular-selective DHP CCB.", { sourceKeys: ["dailymed","aha_hypertension","ema"] }),
  base("Chlorthalidone", ["Thalitone"], "Thiazide-like diuretic", "Inhibits distal convoluted tubule sodium reabsorption.", { sourceKeys: ["dailymed","aha_hypertension","nice"], benefitsSummary: "Potent thiazide-like diuretic with strong guideline support for hypertension; more hypokalemia than HCTZ often.", whyStillPrescribed: "Preferred thiazide-like agent in many hypertension guidelines due to outcome trial heritage." }),
  base("Indapamide", ["Lozol", "Natrilix"], "Thiazide-like diuretic", "Distal tubule sodium inhibition with some vasodilating properties.", { sourceKeys: ["dailymed","aha_hypertension","nice","ema"] }),
  base("Bumetanide", ["Bumex"], "Loop diuretic", "Inhibits NKCC2 in thick ascending limb.", { sourceKeys: ["dailymed","esc_hf","ema"] }),
  base("Torsemide", ["Demadex"], "Loop diuretic", "Loop diuretic with longer half-life than furosemide.", { sourceKeys: ["dailymed","esc_hf","ema"] }),
  base("Eplerenone", ["Inspra"], "Mineralocorticoid receptor antagonist", "Selective mineralocorticoid receptor blockade.", { sourceKeys: ["dailymed","esc_hf","ema"], benefitsSummary: "MRA for HFrEF/post-MI with less gynecomastia than spironolactone; hyperkalemia remains key risk." }),
  base("Pravastatin", ["Pravachol"], "HMG-CoA reductase inhibitor (statin)", "HMG-CoA reductase inhibition.", { sourceKeys: ["dailymed","label_atorvastatin","ema","nice"], benefitsSummary: "Hydrophilic statin with fewer CYP3A4 interactions — useful when interacting drugs present." }),
  base("Lovastatin", ["Mevacor"], "HMG-CoA reductase inhibitor (statin)", "HMG-CoA reductase inhibition (CYP3A4 substrate).", { sourceKeys: ["dailymed","label_atorvastatin","ema"], warnings: [warn("warning","Strong CYP3A4 inhibitors","major","Many combinations contraindicated — myopathy risk."), warn("contraindication","Pregnancy","major","Avoid.")] }),
  base("Pitavastatin", ["Livalo"], "HMG-CoA reductase inhibitor (statin)", "HMG-CoA reductase inhibition.", { sourceKeys: ["dailymed","ema","nice"] }),
  base("Dapagliflozin", ["Farxiga", "Forxiga"], "SGLT2 inhibitor", "Inhibits SGLT2 in proximal tubule — glucosuria; cardiorenal benefits.", { sourceKeys: ["dailymed","ada_diabetes","esc_hf","ema","nice"] }),
  base("Canagliflozin", ["Invokana"], "SGLT2 inhibitor", "SGLT2 inhibition.", { sourceKeys: ["dailymed","ada_diabetes","ema","fda"], warnings: [warn("warning","Lower limb amputation risk historically labeled","major","Assess feet; counsel."), warn("warning","Bone fracture risk signal","moderate","Labeled historically."), warn("warning","DKA risk","major","Euglycemic DKA possible.")] }),
  base("Liraglutide", ["Victoza", "Saxenda"], "GLP-1 receptor agonist", "GLP-1 receptor agonism — glucose-dependent insulin, satiety, delayed gastric emptying.", { routes: ["subcutaneous"], sourceKeys: ["dailymed","ada_diabetes","ema","fda"], benefitsSummary: "T2DM (Victoza) and chronic weight management (Saxenda) — dose/product-specific; CV benefit in T2DM with CVD for Victoza." }),
  base("Dulaglutide", ["Trulicity"], "GLP-1 receptor agonist", "Once-weekly GLP-1 RA.", { routes: ["subcutaneous"], sourceKeys: ["dailymed","ada_diabetes","ema"] }),
  base("Tirzepatide", ["Mounjaro", "Zepbound"], "Dual GIP/GLP-1 receptor agonist", "Dual incretin receptor agonism improving glycemia and weight.", { routes: ["subcutaneous"], sourceKeys: ["dailymed","ada_diabetes","ema","fda"], benefitsSummary: "Potent glycemic and weight effects for T2DM (Mounjaro) and weight management (Zepbound); GI AEs and MTC boxed warning similar to GLP-1 class concepts.", indications: [ind("Type 2 diabetes mellitus"), ind("Chronic weight management (Zepbound — labeled)", "high"), ind("Obstructive sleep apnea with obesity (selected labeled expansion)", "moderate", true, "Check current labeling")] }),
  base("Citalopram", ["Celexa"], "SSRI", "Selective serotonin reuptake inhibition.", { sourceKeys: ["dailymed","label_sertraline","ema","mhra","nice"], warnings: [warn("boxed","Suicidality in young people","major","Monitor."), warn("warning","Dose-dependent QT prolongation","major","Max dose limits especially >60 years; avoid other QT drugs.")] }),
  base("Paroxetine", ["Paxil", "Seroxat"], "SSRI", "Potent SSRI with significant anticholinergic/CYP2D6 effects.", { sourceKeys: ["dailymed","label_sertraline","ema","nice"], whyStillPrescribed: "Effective SSRI/anxiety agent but higher discontinuation syndrome and pregnancy cardiac concern discussions lead many clinicians to prefer alternatives.", withdrawal: "Among SSRIs most associated with discontinuation syndrome — slow taper." }),
  base("Fluvoxamine", ["Luvox"], "SSRI", "SSRI with strong CYP1A2/2C19 inhibition.", { sourceKeys: ["dailymed","ema","nice"], indications: [ind("Obsessive-compulsive disorder"), ind("Social anxiety (some regions)", "moderate"), ind("Depression (jurisdiction-specific)", "moderate")] }),
  base("Duloxetine", ["Cymbalta"], "SNRI", "Serotonin-norepinephrine reuptake inhibition.", { sourceKeys: ["dailymed","ema","nice","bnf"], benefitsSummary: "SNRI for MDD, GAD, and multiple chronic pain indications (diabetic neuropathy, fibromyalgia, chronic musculoskeletal pain) as labeled." }),
  base("Desvenlafaxine", ["Pristiq"], "SNRI", "Active metabolite of venlafaxine — SNRI.", { sourceKeys: ["dailymed","ema"] }),
  base("Moxifloxacin", ["Avelox"], "Fluoroquinolone antibiotic", "Inhibits bacterial DNA gyrase/topoisomerase IV.", { sourceKeys: ["dailymed","fda_fluoroquinolone","ema","mhra"], warnings: [warn("boxed","Tendinopathy, neuropathy, CNS effects","major","Class boxed warnings."), warn("warning","QT prolongation more prominent","major","Avoid with other QT drugs / in long QT.")] }),
  base("Ofloxacin", ["Floxin"], "Fluoroquinolone antibiotic", "Fluoroquinolone antimicrobial.", { sourceKeys: ["dailymed","fda_fluoroquinolone","ema"] }),
  base("Dabigatran", ["Pradaxa"], "Direct thrombin inhibitor DOAC", "Direct thrombin (factor IIa) inhibition.", { sourceKeys: ["dailymed","label_apixaban","ema","nice"], benefitsSummary: "DOAC for NVAF and VTE; idarucizumab available as specific reversal agent in many systems; not for mechanical valves." }),
  base("Edoxaban", ["Lixiana", "Savaysa"], "Factor Xa inhibitor DOAC", "Factor Xa inhibition.", { sourceKeys: ["dailymed","ema","nice"], warnings: [warn("boxed","Reduced efficacy in NVAF with CrCl >95 mL/min (US)", "major","US label warning — prefer other agents if very high CrCl."), warn("boxed","Premature discontinuation increases thrombotic risk","major","See label.")] }),
  base("Prasugrel", ["Effient", "Efient"], "P2Y12 inhibitor antiplatelet", "Irreversible P2Y12 ADP receptor blockade.", { sourceKeys: ["dailymed","ema","nice"], warnings: [warn("boxed","Bleeding","major","Not recommended in patients ≥75 years generally; contraindicated if prior TIA/stroke."), warn("contraindication","Active bleeding / prior TIA/stroke","major","See label.")] }),
  base("Ticagrelor", ["Brilinta", "Brilique"], "P2Y12 inhibitor antiplatelet", "Reversible P2Y12 inhibition.", { sourceKeys: ["dailymed","ema","nice"], adverse: [ae("Bleeding","serious"), ae("Dyspnea","common"), ae("Bradyarrhythmias / ventricular pauses","moderate"), ae("Elevated uric acid","moderate","moderate")] }),
  base("Lorazepam", ["Ativan"], "Benzodiazepine", "GABA-A positive allosteric modulation.", { routes: ["oral","IV","IM"], sourceKeys: ["dailymed","fda","ema","nice"], benefitsSummary: "Preferred benzodiazepine in cirrhosis (no active metabolites) for acute anxiety/seizures/alcohol withdrawal protocols." }),
  base("Alprazolam", ["Xanax"], "Benzodiazepine", "Short-acting benzodiazepine.", { sourceKeys: ["dailymed","fda","ema","nice"], whyStillPrescribed: "Rapid anxiolytic effect for panic; high dependence/misuse liability leads guidelines to prefer alternatives for chronic anxiety." }),
  base("Clonazepam", ["Klonopin", "Rivotril"], "Benzodiazepine", "Longer-acting benzodiazepine.", { sourceKeys: ["dailymed","fda","ema","nice"], indications: [ind("Seizure disorders as labeled"), ind("Panic disorder"), ind("REM sleep behavior / akathisia (off-label)", "moderate", false)] }),
  base("Temazepam", ["Restoril"], "Benzodiazepine", "Benzodiazepine hypnotic.", { sourceKeys: ["dailymed","fda","ema","nice","bnf"] }),
  base("Oxycodone", ["OxyContin", "Percocet (combo)"], "Opioid analgesic", "Mu-opioid receptor agonism.", { sourceKeys: ["dailymed","fda","ema","nice","who"], benefitsSummary: "Potent opioid for severe pain; combination with acetaminophen requires total acetaminophen accounting." }),
  base("Hydrocodone", ["Vicodin (combo)", "Hysingla"], "Opioid analgesic", "Mu-opioid agonism (often acetaminophen combo).", { sourceKeys: ["dailymed","fda","ema"], warnings: [warn("boxed","Opioid class warnings + acetaminophen hepatotoxicity in combos","major","Account for all acetaminophen sources.")] }),
  base("Hydromorphone", ["Dilaudid"], "Opioid analgesic", "Potent mu-opioid agonism.", { routes: ["oral","IV","IM","SC"], sourceKeys: ["dailymed","fda","ema"] }),
  base("Fentanyl", ["Duragesic", "Actiq"], "Opioid analgesic", "High-potency mu-opioid agonism.", { routes: ["transdermal","buccal","IV","nasal"], sourceKeys: ["dailymed","fda","ema","mhra"], warnings: [warn("boxed","Addiction, respiratory depression; accidental exposure; CYP3A4 interactions; heat increasing patch absorption","major","Transdermal only for opioid-tolerant chronic pain in labeled settings.")] }),
  base("Buprenorphine", ["Subutex", "Suboxone (with naloxone)", "Butrans"], "Partial opioid agonist", "Partial mu agonist / kappa antagonist — analgesia and OUD treatment.", { routes: ["SL","buccal","transdermal","SC depot"], sourceKeys: ["dailymed","fda","ema","nice","who"], benefitsSummary: "Cornerstone of opioid use disorder treatment (with/without naloxone) and analgesic for selected chronic pain; ceiling on respiratory depression vs full agonists (not absolute safety).", indications: [ind("Opioid use disorder"), ind("Moderate-severe pain (selected formulations)"), ind("Neonatal opioid withdrawal protocols (off-label/specialist)", "moderate", false)], whyStillPrescribed: "Mortality-reducing OUD therapy with extensive evidence; access barriers remain a public health issue." }),
  base("Naloxone", ["Narcan", "Nyxoid"], "Opioid antagonist", "Competitive mu-opioid receptor antagonism — reverses opioid overdose.", { routes: ["intranasal","IM","IV","SC"], sourceKeys: ["dailymed","fda","who","ema","nice"], indications: [ind("Known/suspected opioid overdose"), ind("Take-home naloxone harm reduction")], adverse: [ae("Precipitated withdrawal","common"), ae("Agitation, sweating, tachycardia","common"), ae("Pulmonary edema (rare reports)","serious","low")], warnings: [warn("warning","Effects may wear off before opioid — repeat doses / emergency care","major","Observe after reversal."), warn("warning","Not a substitute for emergency medical care","major","Call emergency services.")], benefitsSummary: "Essential overdose reversal agent; expanding community access is guideline-supported.", whyStillPrescribed: "Saves lives in opioid overdose; should be available alongside opioid therapy when risk present." }),
  base("Methylprednisolone", ["Medrol", "Solu-Medrol"], "Systemic corticosteroid", "Glucocorticoid anti-inflammatory/immunosuppressive effects.", { routes: ["oral","IV","IM"], sourceKeys: ["dailymed","gina_asthma","ema","nice"] }),
  base("Dexamethasone", ["Decadron"], "Systemic corticosteroid", "Long-acting potent glucocorticoid.", { routes: ["oral","IV","IM"], sourceKeys: ["dailymed","who","ema","nice","gina_asthma"], benefitsSummary: "Used in inflammation, oncology antiemesis, altitude illness, and evidence-based COVID-19 oxygen-requiring protocols; also fetal lung maturation (antenatal)." }),
  base("Budesonide (inhaled)", ["Pulmicort"], "Inhaled corticosteroid", "Local glucocorticoid activity in airways.", { routes: ["inhaled"], sourceKeys: ["dailymed","gina_asthma","nice","ema"] }),
  base("Beclomethasone (inhaled)", ["Qvar"], "Inhaled corticosteroid", "Inhaled glucocorticoid.", { routes: ["inhaled"], sourceKeys: ["dailymed","gina_asthma","nice","ema"] }),
  base("Fluticasone/salmeterol", ["Advair", "Seretide"], "ICS/LABA combination inhaler", "ICS anti-inflammatory plus LABA bronchodilation.", { routes: ["inhaled"], sourceKeys: ["dailymed","gina_asthma","gold_copd","nice"] }),
  base("Umeclidinium/vilanterol", ["Anoro Ellipta"], "LAMA/LABA combination inhaler", "Long-acting muscarinic antagonist + long-acting beta-2 agonist.", { routes: ["inhaled"], sourceKeys: ["dailymed","gold_copd","nice","ema"], indications: [ind("COPD maintenance"), ind("Not for asthma as primary labeled use for this combo — check label", "moderate", true)], adverse: [ae("Nasopharyngitis, headache","common","moderate"), ae("Paradoxical bronchospasm","serious","low"), ae("Urinary retention / dry mouth","moderate"), ae("Cardiovascular effects of LABA","moderate","moderate")] }),
  base("Ipratropium", ["Atrovent"], "Short-acting muscarinic antagonist (SAMA)", "Antimuscarinic bronchodilation.", { routes: ["inhaled","nebulized"], sourceKeys: ["dailymed","gold_copd","gina_asthma","nice"], indications: [ind("COPD maintenance / exacerbation nebulized regimens"), ind("Asthma exacerbation adjunct nebulized with SABA", "moderate")], adverse: [ae("Dry mouth","common"), ae("Bitter taste","common","moderate"), ae("Urinary retention / glaucoma risk if mist in eyes","serious","moderate")] }),
  base("Fexofenadine", ["Allegra", "Telfast"], "Second-generation H1 antihistamine", "Peripheral H1 antagonism — minimally sedating.", { sourceKeys: ["dailymed","ema","nice","bnf"] }),
  base("Desloratadine", ["Clarinex", "Aerius"], "Second-generation H1 antihistamine", "Active metabolite of loratadine.", { sourceKeys: ["dailymed","ema","nice"] }),
  base("Levocetirizine", ["Xyzal"], "Second-generation H1 antihistamine", "Active enantiomer of cetirizine.", { sourceKeys: ["dailymed","ema","nice"] }),
  base("Diphenhydramine", ["Benadryl"], "First-generation H1 antihistamine", "Central and peripheral H1 antagonism — sedating.", { sourceKeys: ["dailymed","ema","fda","bnf"], indications: [ind("Allergic reactions"), ind("Insomnia (short-term OTC — not preferred in elderly)", "moderate"), ind("Motion sickness / antitussive combos", "moderate")], adverse: [ae("Marked sedation, anticholinergic effects","common"), ae("Delirium / falls in elderly","serious"), ae("Impaired driving next day","serious","moderate")], warnings: [warn("precaution","Elderly (Beers Criteria — avoid)","major","High anticholinergic burden."), warn("warning","Children — paradoxical excitation / overdose risk","major","Avoid for sleep in young children.")], whyStillPrescribed: "Widely available for acute allergy/insomnia but safer second-generation antihistamines preferred for allergic rhinitis; avoid for sleep in older adults." }),
  base("Minocycline", ["Minocin"], "Tetracycline antibiotic", "30S ribosomal inhibition.", { sourceKeys: ["dailymed","cdc_stis","ema"], adverse: [ae("Vestibular side effects","common"), ae("Pigmentation / autoimmune hepatitis rare","serious","moderate"), ae("Photosensitivity","common","moderate"), ae("Tooth discoloration class risk","serious","moderate")] }),
  base("Clindamycin", ["Cleocin", "Dalacin"], "Lincosamide antibiotic", "50S ribosomal inhibition — anaerobic/gram-positive coverage.", { routes: ["oral","IV","topical"], sourceKeys: ["dailymed","idsa","ema","bnf"], indications: [ind("Skin/soft tissue infections including some MRSA"), ind("Anaerobic infections / dental"), ind("Bacterial vaginosis (selected regimens)", "moderate"), ind("Acne (topical/oral)", "moderate")], adverse: [ae("Diarrhea","common"), ae("C. difficile colitis (classic association)","serious","high"), ae("Rash / hypersensitivity","moderate"), ae("Hepatotoxicity rare","serious","low")], warnings: [warn("boxed","C. difficile–associated diarrhea","major","Reserve use; counsel on severe diarrhea."), warn("warning","Not for meningitis (poor CNS penetration of some infections)", "moderate","See label.")] }),
  base("Nitrofurantoin", ["Macrobid", "Furadantin"], "Nitrofuran antibiotic", "Multiple bacterial enzyme/DNA damage mechanisms — urinary concentrations.", { sourceKeys: ["dailymed","ema","nice","bnf","idsa"], indications: [ind("Uncomplicated lower UTI"), ind("UTI prophylaxis (selected)", "moderate")], adverse: [ae("Nausea, headache","common"), ae("Pulmonary toxicity (acute/chronic)","serious"), ae("Peripheral neuropathy","serious","moderate"), ae("Hepatotoxicity rare","serious","low"), ae("Hemolysis in G6PD deficiency","serious","moderate")], warnings: [warn("contraindication","Significant renal impairment (thresholds region-specific)","major","Inadequate urine levels + toxicity risk."), warn("warning","Pregnancy at term / neonates — hemolytic risk","major","Avoid near term."), warn("warning","Long-term prophylaxis — monitor pulmonary/hepatic/neuro","moderate","Beers caution in elderly for long-term.")], whyStillPrescribed: "First-line for many uncomplicated cystitis cases with low collateral resistance impact when renal function adequate." }),
  base("Fosfomycin", ["Monurol"], "Phosphonic acid antibiotic", "Inhibits bacterial cell wall synthesis (MurA).", { sourceKeys: ["dailymed","ema","idsa","nice"], indications: [ind("Uncomplicated cystitis in women (single-dose sachet regimens)")], adverse: [ae("Diarrhea, headache, vaginitis","common"), ae("Hypersensitivity rare","serious","low")], warnings: [warn("warning","Not for pyelonephritis","major","Inadequate tissue levels for upper tract."), warn("precaution","Resistance patterns vary by region","moderate","Use susceptibility when available.")] }),
  base("Aztreonam", ["Azactam"], "Monobactam antibiotic", "Inhibits penicillin-binding proteins — gram-negative coverage.", { routes: ["IV","IM","inhaled"], sourceKeys: ["dailymed","idsa","ema"], indications: [ind("Serious gram-negative infections including Pseudomonas"), ind("Inhaled for CF Pseudomonas (Cayston)", "high")], adverse: [ae("Rash, GI upset","common","moderate"), ae("Injection-site reactions","common"), ae("Rare severe hypersensitivity","serious","low")], warnings: [warn("precaution","Cross-reactivity with ceftazidime side chain possible","moderate","Allergy history matters."), warn("warning","Superinfection / resistance","moderate","Stewardship.")] }),
  base("Linezolid", ["Zyvox"], "Oxazolidinone antibiotic", "Inhibits bacterial protein synthesis (50S).", { sourceKeys: ["dailymed","idsa","ema","fda"], indications: [ind("VRE infections"), ind("MRSA pneumonia / SSTI as labeled"), ind("Drug-resistant TB regimens (specialist)", "moderate")], adverse: [ae("Myelosuppression with prolonged use","serious"), ae("Peripheral/optic neuropathy prolonged use","serious"), ae("Serotonin syndrome with serotonergic drugs","serious"), ae("Lactic acidosis rare","serious","low")], warnings: [warn("warning","MAO inhibition — avoid with MAOIs / caution SSRIs","major","Serotonin syndrome."), warn("warning","Monitor CBC with courses >2 weeks","major","Thrombocytopenia/anemia.")] }),
  base("Rifaximin", ["Xifaxan", "Xifaxanta"], "Rifamycin antibiotic (non-absorbed)", "Inhibits bacterial RNA synthesis — minimal systemic absorption.", { sourceKeys: ["dailymed","ema","nice","idsa"], indications: [ind("Traveler's diarrhea (non-invasive)"), ind("Hepatic encephalopathy reduction of recurrence"), ind("IBS-D (labeled US)", "high")], adverse: [ae("Peripheral edema, nausea, dizziness","common","moderate"), ae("C. difficile rare","serious","low")], warnings: [warn("warning","Not for invasive diarrhea with fever/blood","major","Need systemic agents."), warn("precaution","Severe hepatic impairment — HE indication still used carefully","moderate","See label.")] }),
  base("Topiramate", ["Topamax"], "Anticonvulsant / migraine prophylactic", "Multiple mechanisms (Na channels, GABA, carbonic anhydrase).", { sourceKeys: ["dailymed","ema","nice","fda"], indications: [ind("Epilepsy"), ind("Migraine prophylaxis"), ind("Weight / binge-eating off-label contexts", "moderate", false)], adverse: [ae("Paresthesias, cognitive slowing, word-finding difficulty","common"), ae("Nephrolithiasis","serious","moderate"), ae("Angle-closure glaucoma (acute myopia rare)","serious","low"), ae("Metabolic acidosis","moderate"), ae("Oligohidrosis / hyperthermia (esp children)","serious","moderate"), ae("Teratogenicity (oral clefts)","serious")], warnings: [warn("warning","Fetal toxicity — contraception counseling","major","Avoid in pregnancy for migraine."), warn("warning","Cognitive/psychiatric effects","moderate","Counsel."), warn("warning","Visual symptoms — urgent evaluation","major","Rare glaucoma.")], special: { pregnancy: "Avoid for migraine prophylaxis; epilepsy specialist decision.", renal: "Stones / acidosis — hydrate." }, monitoring: ["Bicarbonate periodically", "Weight", "Mood/cognition", "Pregnancy prevention"], withdrawal: "Taper — seizure risk if abrupt stop." }),
  base("Levetiracetam", ["Keppra"], "Anticonvulsant", "SV2A modulation — broad-spectrum antiseizure.", { sourceKeys: ["dailymed","ema","nice","bnf"], indications: [ind("Focal and generalized seizures as labeled"), ind("Status epilepticus IV (guideline use)", "moderate")], adverse: [ae("Somnolence, dizziness","common"), ae("Behavioral changes / irritability / depression","common"), ae("Suicidal thoughts (antiepileptic class)","serious","moderate")], warnings: [warn("warning","Psychiatric/behavioral adverse reactions","major","Counsel patients/caregivers."), warn("warning","Abrupt withdrawal — seizures","major","Taper.")], special: { pregnancy: "Relatively favorable registry data vs some ASMs — still specialist care.", renal: "Dose adjust." }, monitoring: ["Mood/behavior", "Renal dosing", "Seizure frequency"] }),
  base("Phenytoin", ["Dilantin", "Epanutin"], "Anticonvulsant", "Voltage-gated sodium channel blockade.", { sourceKeys: ["dailymed","ema","nice","bnf","fda"], indications: [ind("Focal and generalized tonic-clonic seizures"), ind("Status epilepticus (IV fosphenytoin/phenytoin protocols)")], adverse: [ae("Gingival hyperplasia, hirsutism, acne","common"), ae("Osteomalacia long-term","moderate"), ae("SJS/TEN / DRESS","serious"), ae("Hepatotoxicity","serious"), ae("Cerebellar toxicity / nystagmus with high levels","serious"), ae("Purple glove syndrome (IV phenytoin)","serious","moderate")], warnings: [warn("boxed","Cardiovascular risk with rapid IV infusion","major","Infuse carefully; prefer fosphenytoin in many protocols."), warn("warning","HLA-B*1502 / serious rash risk","major","Screen at-risk ancestries."), warn("warning","Narrow therapeutic index / many interactions","major","Monitor levels.")], monitoring: ["Serum levels", "LFTs/CBC", "Dental care", "Bone health", "Albumin-adjusted interpretation"], whyStillPrescribed: "Still used globally for seizures and status protocols despite interaction burden and chronic toxicity — many prefer levetiracetam/newer ASMs when accessible." }),
  base("Gabapentin enacarbil", ["Horizant"], "Gabapentinoid", "Prodrug of gabapentin — restless legs / postherpetic neuralgia.", { sourceKeys: ["dailymed","fda","ema"], indications: [ind("Restless legs syndrome"), ind("Postherpetic neuralgia")] }),
  base("Zopiclone", ["Imovane", "Zimovane"], "Non-benzodiazepine hypnotic (Z-drug)", "GABA-A modulation via benzodiazepine site — hypnotic.", { sourceKeys: ["ema","mhra","nice","bnf"], indications: [ind("Short-term insomnia")], adverse: [ae("Bitter taste, dry mouth","common"), ae("Next-day impairment","common"), ae("Complex sleep behaviors","serious","moderate"), ae("Dependence with prolonged use","serious","moderate")], warnings: [warn("warning","Short-term use only","major","Tolerance/dependence."), warn("warning","Avoid alcohol/CNS depressants","major","Respiratory/cognitive risk.")] }),
  base("Eszopiclone", ["Lunesta"], "Non-benzodiazepine hypnotic (Z-drug)", "GABA-A modulation — hypnotic.", { sourceKeys: ["dailymed","fda","ema"], indications: [ind("Insomnia")], adverse: [ae("Dysgeusia, headache","common"), ae("Next-day impairment","common"), ae("Complex sleep behaviors","serious"), ae("Dependence potential","serious","moderate")], warnings: [warn("boxed","Complex sleep behaviors","major","Discontinue if occur."), warn("warning","CNS depression","major","Lower starting doses in elderly/debilitated.")] }),
  base("Mirtazapine", ["Remeron"], "Tetracyclic antidepressant (NaSSA)", "Central alpha-2 antagonism enhancing NE/5-HT; H1 antagonism.", { sourceKeys: ["dailymed","ema","nice","bnf"], indications: [ind("Major depressive disorder"), ind("Insomnia / appetite stimulation off-label common", "moderate", false)], adverse: [ae("Sedation, increased appetite, weight gain","common"), ae("Dry mouth, constipation","common"), ae("Agranulocytosis rare","serious","low"), ae("Suicidality boxed warning in young","serious")], warnings: [warn("boxed","Suicidality in children/young adults","major","Monitor."), warn("warning","MAOI washout","major","See label."), warn("precaution","Obesity / OSA — weight/sedation","moderate","Clinical judgment.")], special: { pregnancy: "Discuss alternatives.", geriatric: "Often used for depression with insomnia/poor appetite — fall/sedation watch." }, monitoring: ["Weight", "Suicidality", "Sedation/falls"], withdrawal: "Taper — anxiety/insomnia rebound possible." }),
  base("Bupropion", ["Wellbutrin", "Zyban"], "NDRI antidepressant / smoking cessation", "Norepinephrine-dopamine reuptake inhibition.", { sourceKeys: ["dailymed","ema","nice","fda"], indications: [ind("Major depressive disorder"), ind("Seasonal affective disorder"), ind("Smoking cessation (Zyban)"), ind("ADHD off-label", "moderate", false)], adverse: [ae("Insomnia, dry mouth, headache","common"), ae("Seizures (dose-related)","serious"), ae("Hypertension","moderate"), ae("Suicidality boxed warning in young","serious"), ae("Neuropsychiatric events in smoking cessation","serious","moderate")], warnings: [warn("boxed","Suicidality in young people","major","Monitor."), warn("contraindication","Seizure disorder / abrupt alcohol-benzo withdrawal / bulimia-anorexia history","major","Seizure risk."), warn("warning","MAOI washout","major","Hypertensive reactions.")], special: { pregnancy: "Discuss; smoking cessation benefits may matter.", renal: "Dose adjust XR.", hepatic: "Caution." }, monitoring: ["Seizure risk factors / dose limits", "BP", "Mood", "Smoking status if Zyban"] }),
  base("Trazodone", ["Desyrel"], "Serotonin modulator antidepressant", "5-HT2A antagonism / weak SRI — sedating.", { sourceKeys: ["dailymed","ema","nice"], indications: [ind("Major depressive disorder"), ind("Insomnia off-label very common", "moderate", false)], adverse: [ae("Sedation, dizziness, orthostasis","common"), ae("Priapism (rare)","serious","low"), ae("Cardiac arrhythmias rare","serious","low"), ae("Serotonin syndrome with combinations","serious","moderate")], warnings: [warn("boxed","Suicidality in young","major","Monitor."), warn("warning","Priapism — seek emergency care","major","Rare but labeled."), warn("precaution","Falls in elderly","moderate","Orthostasis.")], withdrawal: "Taper when possible." }),
  base("Aripiprazole", ["Abilify"], "Atypical antipsychotic", "Partial D2/5-HT1A agonist; 5-HT2A antagonist.", { sourceKeys: ["dailymed","fda","ema","nice"], indications: [ind("Schizophrenia"), ind("Bipolar I"), ind("Adjunct MDD"), ind("Irritability in autistic disorder (pediatric labeled)", "moderate"), ind("Tourette disorder (labeled)", "moderate")] }),
  base("Olanzapine", ["Zyprexa"], "Atypical antipsychotic", "Multi-receptor antagonism (D2/5-HT2 etc.).", { sourceKeys: ["dailymed","fda","ema","nice"], whyStillPrescribed: "Highly effective for psychosis/mania but among highest metabolic risk — metabolic monitoring mandatory.", adverse: [ae("Marked weight gain / dyslipidemia / diabetes risk","serious"), ae("Sedation","common"), ae("Orthostasis","moderate"), ae("DRESS rare","serious","low")] }),
  base("Risperidone", ["Risperdal"], "Atypical antipsychotic", "D2/5-HT2A antagonism.", { sourceKeys: ["dailymed","fda","ema","nice"], adverse: [ae("Hyperprolactinemia","common"), ae("EPS / tardive dyskinesia risk","serious","moderate"), ae("Weight gain / metabolic effects","serious","moderate"), ae("Orthostasis","moderate")] }),
  base("Clozapine", ["Clozaril", "Leponex"], "Atypical antipsychotic", "Multi-receptor antipsychotic reserved for treatment-resistant schizophrenia.", { sourceKeys: ["dailymed","fda","ema","nice","mhra"], indications: [ind("Treatment-resistant schizophrenia"), ind("Reduction of recurrent suicidal behavior in schizophrenia/schizoaffective", "high")], adverse: [ae("Agranulocytosis / neutropenia","serious","high","REMS/registry monitoring"), ae("Myocarditis / cardiomyopathy","serious"), ae("Seizures dose-related","serious"), ae("Severe constipation / GI hypomotility","serious"), ae("Metabolic syndrome / sialorrhea / sedation","common")], warnings: [warn("boxed","Severe neutropenia; orthostatic hypotension/bradycardia/syncope; seizures; myocarditis; increased dementia mortality","major","Mandatory blood monitoring programs."), warn("warning","Smoking cessation raises levels","moderate","Dose adjust.")], monitoring: ["ANC per REMS schedule", "Troponin/CRP early if myocarditis suspected", "Constipation bowel plans", "Metabolic labs", "Troponin protocols per local guidance"], whyStillPrescribed: "Most effective antipsychotic for treatment-resistant schizophrenia and unique antisuicidal evidence — toxicity managed with structured monitoring." }),
  base("Atomoxetine", ["Strattera"], "Selective norepinephrine reuptake inhibitor (ADHD)", "NET inhibition — non-stimulant ADHD therapy.", { sourceKeys: ["dailymed","ema","nice","fda"], indications: [ind("ADHD (children/adults as labeled)")], adverse: [ae("GI upset, decreased appetite, dry mouth","common"), ae("Increased HR/BP","moderate"), ae("Suicidal ideation boxed warning in children/adolescents","serious"), ae("Severe liver injury rare","serious","low"), ae("Urinary retention","moderate","moderate")], warnings: [warn("boxed","Suicidal ideation in children/adolescents","major","Monitor."), warn("warning","Severe liver injury","moderate","Discontinue if jaundice/dark urine."), warn("contraindication","MAOIs / narrow-angle glaucoma (selected)","major","See label.")], special: { pregnancy: "Limited data — discuss.", hepatic: "Dose adjust.", "cardiovascular": "Screen for CV disease." }, monitoring: ["HR/BP", "Growth in children", "Mood/suicidality", "Liver symptoms"] }),
  base("Methylphenidate", ["Ritalin", "Concerta"], "CNS stimulant (ADHD)", "Blocks reuptake of dopamine/norepinephrine.", { sourceKeys: ["dailymed","ema","nice","fda"], indications: [ind("ADHD"), ind("Narcolepsy (selected products)")], adverse: [ae("Decreased appetite, insomnia, anxiety","common"), ae("Increased HR/BP","moderate"), ae("Growth suppression concerns in children","moderate"), ae("Psychosis/mania rare at high doses","serious","moderate"), ae("Priapism rare","serious","low"), ae("Dependence/misuse potential","serious")], warnings: [warn("boxed","Abuse and dependence","major","Assess risk."), warn("warning","CV disease screening","major","Sudden death reports in structural heart disease."), warn("contraindication","MAOIs / significant anxiety/glaucoma/tics product-specific","major","See label.")], monitoring: ["HR/BP", "Growth/weight", "Sleep/appetite", "Misuse risk"], withdrawal: "Fatigue/depression on abrupt stop after heavy use — medical supervision." }),
  base("Amphetamine salts (mixed)", ["Adderall"], "CNS stimulant (ADHD)", "Increases synaptic DA/NE via release and reuptake effects.", { sourceKeys: ["dailymed","fda","ema"], indications: [ind("ADHD"), ind("Narcolepsy")], adverse: [ae("Appetite loss, insomnia, anxiety","common"), ae("Hypertension/tachycardia","moderate"), ae("Misuse/dependence","serious"), ae("Psychosis at high doses","serious","moderate")], warnings: [warn("boxed","Abuse and dependence","major","C-II controlled."), warn("warning","CV risk screening","major","Avoid in significant structural heart disease.")] }),
  base("Allopurinol", null, null, null), // already exists - skip duplicates in runner
];

// Filter null stubs and apply class templates
export const NEW_MEDS = stubs
  .filter((s) => s && s.genericName && s.mechanism)
  .map(withClass)
  .map((m) => {
    // Ensure floors
    if (m.indications.length < 2) {
      m.indications.push(ind("Additional labeled / guideline uses — see SmPC/PI", "moderate"));
    }
    if (m.adverse.length < 3) {
      m.adverse.push(ae("Hypersensitivity reactions", "serious", "moderate"));
      m.adverse.push(ae("Class-related adverse effects — review labeling", "moderate", "moderate"));
    }
    if (!m.warnings?.length) {
      m.warnings = [warn("warning", "Full labeling review required", "moderate", "Interactions and contraindications are product-specific.")];
    }
    return m;
  });
