export type SourceSeed = {
  key: string;
  title: string;
  organization: string;
  publicationDate?: string;
  evidenceType: string;
  url?: string;
  jurisdiction?: string;
};

export const SOURCE_SEEDS: SourceSeed[] = [
  {
    key: "dailymed",
    title: "DailyMed — FDA Labeling Database",
    organization: "U.S. National Library of Medicine / FDA",
    evidenceType: "regulatory",
    url: "https://dailymed.nlm.nih.gov/dailymed/",
    jurisdiction: "US",
  },
  {
    key: "fda",
    title: "FDA Drug Databases & Safety Communications",
    organization: "U.S. Food and Drug Administration",
    evidenceType: "regulatory",
    url: "https://www.fda.gov/drugs",
    jurisdiction: "US",
  },
  {
    key: "ema",
    title: "EMA Medicines — European Public Assessment Reports & SmPC concepts",
    organization: "European Medicines Agency",
    evidenceType: "regulatory",
    url: "https://www.ema.europa.eu/en/medicines",
    jurisdiction: "EU",
  },
  {
    key: "nice",
    title: "NICE Guidance",
    organization: "National Institute for Health and Care Excellence",
    evidenceType: "guideline",
    url: "https://www.nice.org.uk/guidance",
    jurisdiction: "UK",
  },
  {
    key: "mhra",
    title: "MHRA Product Information & Safety Updates",
    organization: "Medicines and Healthcare products Regulatory Agency",
    evidenceType: "regulatory",
    url: "https://www.gov.uk/government/organisations/medicines-and-healthcare-products-regulatory-agency",
    jurisdiction: "UK",
  },
  {
    key: "swissmedic",
    title: "Swissmedic Product Information",
    organization: "Swissmedic",
    evidenceType: "regulatory",
    url: "https://www.swissmedic.ch/swissmedic/en/home.html",
    jurisdiction: "CH",
  },
  {
    key: "who",
    title: "WHO Model List of Essential Medicines",
    organization: "World Health Organization",
    evidenceType: "guideline",
    url: "https://www.who.int/groups/expert-committee-on-selection-and-use-of-essential-medicines/essential-medicines-lists",
  },
  {
    key: "aha_hypertension",
    title: "Guideline for the Prevention, Detection, Evaluation, and Management of High Blood Pressure",
    organization: "American College of Cardiology / American Heart Association",
    evidenceType: "guideline",
    url: "https://www.acc.org/guidelines",
    jurisdiction: "US",
  },
  {
    key: "ada_diabetes",
    title: "Standards of Care in Diabetes",
    organization: "American Diabetes Association",
    evidenceType: "guideline",
    url: "https://diabetesjournals.org/care",
    jurisdiction: "US",
  },
  {
    key: "fda_ppi_magnesium",
    title: "FDA Drug Safety Communication: Low magnesium levels associated with long-term PPI use",
    organization: "U.S. Food and Drug Administration",
    publicationDate: "2011-03-02",
    evidenceType: "regulatory",
    url: "https://www.fda.gov/drugs/drug-safety-and-availability/fda-drug-safety-communication-low-magnesium-levels-can-be-associated-long-term-use-proton-pump",
    jurisdiction: "US",
  },
  {
    key: "fda_fluoroquinolone",
    title: "FDA reinforces safety information about serious side effects of fluoroquinolones",
    organization: "U.S. Food and Drug Administration",
    evidenceType: "regulatory",
    url: "https://www.fda.gov/drugs/drug-safety-and-availability/fda-reinforces-safety-information-about-serious-side-effects-fluoroquinolone-antibiotics",
    jurisdiction: "US",
  },
  {
    key: "fda_warfarin",
    title: "Warfarin sodium prescribing information (boxed warning — bleeding)",
    organization: "U.S. Food and Drug Administration / DailyMed",
    evidenceType: "regulatory",
    url: "https://dailymed.nlm.nih.gov/dailymed/",
    jurisdiction: "US",
  },
  {
    key: "bnf",
    title: "British National Formulary (BNF)",
    organization: "NICE / BMJ / RPS",
    evidenceType: "guideline",
    url: "https://bnf.nice.org.uk/",
    jurisdiction: "UK",
  },
  {
    key: "cdc_stis",
    title: "CDC STI Treatment Guidelines",
    organization: "Centers for Disease Control and Prevention",
    evidenceType: "guideline",
    url: "https://www.cdc.gov/std/treatment-guidelines/",
    jurisdiction: "US",
  },
  {
    key: "gold_copd",
    title: "Global Strategy for Prevention, Diagnosis and Management of COPD",
    organization: "Global Initiative for Chronic Obstructive Lung Disease (GOLD)",
    evidenceType: "guideline",
    url: "https://goldcopd.org/",
  },
  {
    key: "gina_asthma",
    title: "Global Strategy for Asthma Management and Prevention",
    organization: "Global Initiative for Asthma (GINA)",
    evidenceType: "guideline",
    url: "https://ginasthma.org/",
  },
  {
    key: "esc_hf",
    title: "ESC Guidelines for the diagnosis and treatment of acute and chronic heart failure",
    organization: "European Society of Cardiology",
    evidenceType: "guideline",
    url: "https://www.escardio.org/Guidelines",
    jurisdiction: "EU",
  },
  {
    key: "acog",
    title: "ACOG Clinical Guidance",
    organization: "American College of Obstetricians and Gynecologists",
    evidenceType: "guideline",
    url: "https://www.acog.org/clinical",
    jurisdiction: "US",
  },
  {
    key: "label_omeprazole",
    title: "Omeprazole delayed-release capsules — prescribing information",
    organization: "FDA / DailyMed",
    evidenceType: "regulatory",
    url: "https://dailymed.nlm.nih.gov/dailymed/",
    jurisdiction: "US",
  },
  {
    key: "label_ibuprofen",
    title: "Ibuprofen — prescribing information (NSAID boxed warning)",
    organization: "FDA / DailyMed",
    evidenceType: "regulatory",
    url: "https://dailymed.nlm.nih.gov/dailymed/",
    jurisdiction: "US",
  },
  {
    key: "label_paracetamol",
    title: "Acetaminophen / Paracetamol labeling — hepatotoxicity warning",
    organization: "FDA / EMA / MHRA",
    evidenceType: "regulatory",
    url: "https://www.fda.gov/drugs/drug-safety-and-availability",
  },
  {
    key: "label_sertraline",
    title: "Sertraline — prescribing information (boxed warning suicidality)",
    organization: "FDA / DailyMed",
    evidenceType: "regulatory",
    url: "https://dailymed.nlm.nih.gov/dailymed/",
    jurisdiction: "US",
  },
  {
    key: "label_metformin",
    title: "Metformin hydrochloride — prescribing information",
    organization: "FDA / DailyMed",
    evidenceType: "regulatory",
    url: "https://dailymed.nlm.nih.gov/dailymed/",
    jurisdiction: "US",
  },
  {
    key: "label_atorvastatin",
    title: "Atorvastatin calcium — prescribing information",
    organization: "FDA / DailyMed",
    evidenceType: "regulatory",
    url: "https://dailymed.nlm.nih.gov/dailymed/",
    jurisdiction: "US",
  },
  {
    key: "label_amoxicillin",
    title: "Amoxicillin — prescribing information",
    organization: "FDA / DailyMed",
    evidenceType: "regulatory",
    url: "https://dailymed.nlm.nih.gov/dailymed/",
    jurisdiction: "US",
  },
  {
    key: "label_levothyroxine",
    title: "Levothyroxine sodium — prescribing information",
    organization: "FDA / DailyMed",
    evidenceType: "regulatory",
    url: "https://dailymed.nlm.nih.gov/dailymed/",
    jurisdiction: "US",
  },
  {
    key: "label_apixaban",
    title: "Apixaban — prescribing information (boxed warning)",
    organization: "FDA / DailyMed",
    evidenceType: "regulatory",
    url: "https://dailymed.nlm.nih.gov/dailymed/",
    jurisdiction: "US",
  },
  {
    key: "label_ciprofloxacin",
    title: "Ciprofloxacin — prescribing information (fluoroquinolone boxed warnings)",
    organization: "FDA / DailyMed",
    evidenceType: "regulatory",
    url: "https://dailymed.nlm.nih.gov/dailymed/",
    jurisdiction: "US",
  },
  {
    key: "cochrane_overview",
    title: "Cochrane Library — systematic reviews (methodology reference)",
    organization: "Cochrane",
    evidenceType: "guideline",
    url: "https://www.cochranelibrary.com/",
  },
  {
    key: "uptodate_style_note",
    title: "Clinical knowledge bases synthesize label + guideline evidence (architecture note)",
    organization: "MedEvidence editorial note",
    evidenceType: "expert_opinion",
    url: "https://www.who.int/",
  },
];
