import { med, I, A, W, US_OK } from "./helpers.mjs";

// Cardiovascular, smoking cessation, oncology, immunology, urology, misc
export const MEDS_E = [
  med({
    name: "Ivabradine",
    brands: ["Procoralan", "Corlanor"],
    cls: "If (funny-current) channel inhibitor",
    mech: "Selectively inhibits the sinoatrial node If current, lowering heart rate without affecting contractility.",
    reg: { US: US_OK + " (heart failure only)", EU: "Centrally authorised (EMA) — see EPAR" },
    eq: "SHIFT RCT: reduced HF hospitalisation in HFrEF with sinus rhythm and HR ≥70; no benefit on outcomes in stable angina without HF (SIGNIFY).",
    ben: "Heart-rate-lowering add-on in HFrEF when heart rate stays high despite beta-blockers.",
    ind: [
      I("Chronic heart failure with reduced ejection fraction, sinus rhythm, resting HR ≥70–75 bpm"),
      I("Symptomatic stable angina in sinus rhythm (EU)", "moderate"),
    ],
    ae: [
      A("Luminous visual phenomena (phosphenes)", "common"),
      A("Bradycardia", "common"),
      A("Atrial fibrillation (increased risk)", "serious"),
      A("Blurred vision; blood-pressure elevation", "moderate", "moderate"),
    ],
    warn: [
      W("contraindication", "Strong CYP3A4 inhibitors; verapamil or diltiazem", "major", "Excess bradycardia."),
      W("contraindication", "Pregnancy; sick sinus syndrome; 3rd-degree AV block; acute decompensated HF; low resting heart rate", "major", "See label."),
    ],
    special: {
      pregnancy: "Contraindicated (fetal toxicity) — effective contraception required.",
      lactation: "Contraindicated.",
      hepatic: "Contraindicated in severe impairment.",
    },
    mon: ["Resting heart rate", "ECG / AF symptoms", "Visual symptoms"],
    src: ["dailymed", "ema", "esc_hf", "nice"],
  }),
  med({
    name: "Flecainide",
    brands: ["Tambocor"],
    cls: "Class Ic antiarrhythmic",
    mech: "Blocks cardiac sodium channels, slowing conduction.",
    routes: ["oral", "IV"],
    reg: { US: US_OK + " (boxed warning: CAST mortality)" },
    eq: "Effective rhythm control in structurally normal hearts; CAST trial showed increased mortality after MI.",
    ben: "Rhythm-control option for AF/SVT in people without structural heart disease.",
    ind: [
      I("Prevention of paroxysmal AF/flutter in patients without structural heart disease"),
      I("Paroxysmal supraventricular tachycardias"),
      I("Life-threatening ventricular arrhythmias (specialist)", "moderate"),
    ],
    ae: [
      A("Dizziness, visual disturbance (blurred vision)", "common"),
      A("Proarrhythmia (ventricular arrhythmias)", "boxed"),
      A("Worsening heart failure", "serious"),
      A("Conduction abnormalities (QRS widening, AV block)", "serious"),
      A("Atrial flutter with 1:1 conduction (without AV-nodal blocker)", "serious", "moderate"),
    ],
    warn: [
      W("boxed", "Post-myocardial infarction / structural heart disease", "major", "Excess mortality in CAST — contraindicated."),
      W("precaution", "AF treatment without an AV-nodal blocking drug", "major", "Risk of rapid 1:1 flutter conduction."),
      W("precaution", "Renal impairment; electrolyte disturbance", "moderate", "Accumulation; correct potassium."),
    ],
    special: {
      pregnancy: "Specialist use only.",
      lactation: "Passes into milk.",
      renal: "Dose reduction; plasma levels.",
      geriatric: "Renal function decline.",
    },
    mon: ["ECG (QRS, PR) after initiation and dose changes", "Plasma levels in renal/hepatic impairment", "Electrolytes"],
    src: ["dailymed", "esc_hf", "aha_af", "bnf"],
  }),
  med({
    name: "Sotalol",
    brands: ["Sotalex", "Betapace"],
    cls: "Class III antiarrhythmic with non-selective beta-blockade",
    mech: "Blocks potassium channels (prolongs repolarisation) and beta-adrenergic receptors.",
    reg: { US: US_OK + " (boxed warning: initiation with ECG monitoring)" },
    eq: "Effective for maintaining sinus rhythm and ventricular arrhythmias; dose-related torsades risk.",
    ben: "Rhythm-control drug requiring careful initiation and renal dosing.",
    ind: [
      I("Life-threatening ventricular arrhythmias"),
      I("Maintenance of sinus rhythm in AF/atrial flutter"),
    ],
    ae: [
      A("Fatigue, bradycardia, dyspnoea, dizziness", "common"),
      A("Torsades de pointes (QT prolongation)", "boxed"),
      A("Bronchospasm", "serious", "moderate"),
      A("Heart failure exacerbation", "serious", "moderate"),
    ],
    warn: [
      W("boxed", "Initiation/re-initiation", "major", "Start in a facility with ECG monitoring and creatinine clearance calculation (US)."),
      W("contraindication", "Asthma, bradycardia/heart block, long QT, hypokalaemia, severe renal impairment", "major", "See label."),
      W("warning", "Other QT-prolonging drugs", "major", "Additive torsades risk."),
    ],
    special: {
      pregnancy: "Specialist use.",
      lactation: "High milk levels — monitor infant.",
      renal: "Dose interval adjustment; contraindicated in severe impairment for some indications.",
      geriatric: "Renal decline.",
    },
    mon: ["QTc at initiation and dose changes", "Renal function", "Potassium and magnesium"],
    wd: "Abrupt withdrawal of beta-blockade can precipitate angina or arrhythmia — changes should be clinician-guided.",
    src: ["dailymed", "aha_af", "bnf", "ema"],
  }),
  med({
    name: "Varenicline",
    brands: ["Champix", "Chantix"],
    cls: "Nicotinic receptor partial agonist (smoking cessation)",
    mech: "Partial agonist at alpha4beta2 nicotinic receptors — reduces craving and the reward from smoking.",
    reg: {
      US: US_OK + " (boxed neuropsychiatric warning removed in 2016; supply affected by nitrosamine recalls since 2021)",
      EU: "Centrally authorised (EMA); availability affected by nitrosamine-impurity recalls — check local supply",
    },
    eq: "RCTs (incl. EAGLES) show varenicline is among the most effective single smoking-cessation medicines.",
    ben: "Substantially increases quit rates compared with placebo when combined with support.",
    ind: [
      I("Smoking cessation in adults"),
      I("Gradual-reduction approach to quitting (US labelling)", "moderate"),
      I("Vaping/e-cigarette cessation", "low", false, "Emerging evidence; off-label"),
    ],
    ae: [
      A("Nausea (very common)", "common"),
      A("Abnormal dreams, insomnia, headache", "common"),
      A("Neuropsychiatric events (mood change, agitation) — not increased in EAGLES, but monitoring advised", "serious", "moderate"),
      A("Seizures (rare)", "serious", "low"),
      A("Possible small increase in CV events in established CVD (label)", "serious", "low"),
    ],
    warn: [
      W("warning", "Psychiatric history", "moderate", "Monitor mood and behaviour; seek help if concerning changes."),
      W("precaution", "Alcohol", "moderate", "Reduced alcohol tolerance and unusual behaviour reported."),
      W("precaution", "Severe renal impairment", "moderate", "Dose adjustment."),
    ],
    special: {
      pregnancy: "Limited data — behavioural support and NRT are usually preferred.",
      lactation: "Not recommended.",
      renal: "Dose reduction in severe impairment.",
    },
    mon: ["Mood and behaviour", "Smoking status / quit date", "Nausea tolerance"],
    src: ["dailymed", "ema", "nice", "who"],
  }),
  med({
    name: "Nicotine replacement therapy",
    brands: ["Nicorette", "NiQuitin", "Nicotinell"],
    cls: "Smoking-cessation aid (nicotine)",
    mech: "Provides nicotine without tobacco smoke, reducing withdrawal and craving.",
    routes: ["transdermal", "oromucosal", "intranasal", "inhalation"],
    reg: { US: US_OK + " (OTC patches, gum, lozenges; Rx spray/inhaler)" },
    eq: "Cochrane reviews: all forms increase quit rates; combining a patch with a fast-acting form is more effective than one form.",
    ben: "Far safer than smoking; increases the chance of quitting, especially with behavioural support.",
    ind: [
      I("Smoking cessation"),
      I("Reducing smoking / temporary abstinence as a step towards quitting", "moderate"),
    ],
    ae: [
      A("Local irritation (skin with patches; mouth/throat with gum, lozenge, spray)", "common"),
      A("Nausea, hiccups, headache, dizziness", "common"),
      A("Sleep disturbance / vivid dreams (24-hour patches)", "common", "moderate"),
      A("Palpitations", "moderate", "moderate"),
      A("Nicotine poisoning if products are swallowed by children or pets (keep out of reach; used patches still contain nicotine)", "serious", "high"),
    ],
    warn: [
      W("precaution", "Recent MI, unstable angina, recent stroke or serious arrhythmia", "moderate", "Discuss with a clinician — NRT is usually much safer than continued smoking."),
      W("warning", "Children and pets", "major", "Nicotine products can cause serious poisoning if swallowed — store safely (CH: Tox Info Suisse 145)."),
    ],
    special: {
      pregnancy: "If behavioural support alone fails, NRT is generally preferred over smoking (clinician advice).",
      lactation: "Preferable to smoking.",
      pediatric: "Adolescents: product-specific guidance.",
    },
    mon: ["Withdrawal symptoms and cravings", "Smoking status"],
    src: ["nice", "who", "cochrane_overview", "nhs_medicines"],
  }),
  med({
    name: "Tamoxifen",
    brands: ["Nolvadex", "Soltamox"],
    cls: "Selective estrogen receptor modulator (SERM)",
    mech: "Blocks estrogen receptors in breast tissue (partial agonist in endometrium and bone).",
    reg: { US: US_OK },
    eq: "Very strong RCT/meta-analysis evidence: adjuvant tamoxifen reduces recurrence and death in ER-positive breast cancer.",
    ben: "Core endocrine therapy for ER-positive breast cancer, including premenopausal women.",
    ind: [
      I("Adjuvant treatment of ER-positive early breast cancer"),
      I("Metastatic ER-positive breast cancer"),
      I("Risk reduction in women at high risk of breast cancer"),
      I("Ductal carcinoma in situ (US label)", "moderate"),
    ],
    ae: [
      A("Hot flushes, vaginal discharge, irregular periods", "common"),
      A("Venous thromboembolism", "serious"),
      A("Endometrial hyperplasia / uterine cancer", "boxed"),
      A("Stroke", "serious", "moderate"),
      A("Cataracts", "moderate", "moderate"),
    ],
    warn: [
      W("boxed", "Uterine malignancies, stroke, pulmonary embolism (risk-reduction/DCIS settings, US)", "major", "Weigh benefits/risks."),
      W("contraindication", "Pregnancy", "major", "Use effective non-hormonal contraception."),
      W("precaution", "Strong CYP2D6 inhibitors (e.g., paroxetine, fluoxetine)", "moderate", "May reduce formation of the active metabolite endoxifen; outcome data mixed."),
    ],
    special: {
      pregnancy: "Contraindicated.",
      lactation: "Contraindicated.",
      geriatric: "VTE/stroke risk.",
    },
    mon: ["Prompt evaluation of abnormal vaginal bleeding", "Eye exam if visual changes", "VTE symptoms"],
    src: ["dailymed", "nice", "ema", "uspstf"],
  }),
  med({
    name: "Letrozole",
    brands: ["Femara"],
    cls: "Aromatase inhibitor",
    mech: "Non-steroidal aromatase inhibition, suppressing estrogen synthesis in postmenopausal women.",
    reg: { US: US_OK },
    eq: "RCTs (e.g., BIG 1-98) show benefit in postmenopausal HR-positive breast cancer; RCT evidence supports ovulation induction in PCOS (off-label).",
    ben: "Endocrine therapy for postmenopausal hormone-receptor-positive breast cancer.",
    ind: [
      I("Adjuvant treatment of HR-positive early breast cancer in postmenopausal women"),
      I("Extended adjuvant therapy after tamoxifen"),
      I("Advanced/metastatic HR-positive breast cancer"),
      I("Ovulation induction in PCOS", "moderate", false, "Off-label in many countries; guideline-supported"),
    ],
    ae: [
      A("Hot flushes, arthralgia, myalgia", "common"),
      A("Fatigue, sweating", "common"),
      A("Bone loss / osteoporosis and fractures", "serious"),
      A("Hypercholesterolaemia", "moderate", "moderate"),
    ],
    warn: [
      W("contraindication", "Premenopausal endocrine status (as monotherapy), pregnancy, breastfeeding", "major", "See label."),
      W("precaution", "Bone health", "moderate", "Assess BMD; bone protection per guidelines."),
    ],
    special: {
      pregnancy: "Contraindicated.",
      lactation: "Contraindicated.",
      hepatic: "Caution in severe impairment.",
    },
    mon: ["Bone mineral density", "Lipids", "Musculoskeletal symptoms"],
    src: ["dailymed", "nice", "ema", "asrm"],
  }),
  med({
    name: "Adalimumab",
    brands: ["Humira", "Amgevita", "Hyrimoz", "Imraldi"],
    cls: "TNF-alpha inhibitor (monoclonal antibody)",
    mech: "Binds TNF-alpha, blocking its pro-inflammatory signalling.",
    routes: ["subcutaneous"],
    reg: { US: US_OK + " (boxed warning: serious infections, malignancy)", EU: "Centrally authorised (EMA) — originator and several biosimilars" },
    eq: "Extensive RCT evidence across inflammatory arthritis, IBD, psoriasis and HS; biosimilars show equivalent efficacy.",
    ben: "Highly effective biologic for many immune-mediated diseases; infection screening and monitoring are essential.",
    ind: [
      I("Rheumatoid arthritis, psoriatic arthritis, axial spondyloarthritis"),
      I("Crohn's disease and ulcerative colitis"),
      I("Plaque psoriasis and hidradenitis suppurativa"),
      I("Non-infectious uveitis; juvenile idiopathic arthritis"),
    ],
    ae: [
      A("Injection-site reactions, upper respiratory infections", "common"),
      A("Serious infections including TB reactivation and opportunistic infections", "boxed"),
      A("Malignancy including lymphoma", "boxed"),
      A("Demyelinating disease, worsening heart failure", "serious", "moderate"),
      A("Hepatitis B reactivation; lupus-like syndrome", "serious", "moderate"),
    ],
    warn: [
      W("boxed", "Serious infections and malignancy", "major", "Screen for latent TB and hepatitis B before starting."),
      W("contraindication", "Active TB or severe infections; moderate–severe heart failure (NYHA III/IV, EU)", "major", "See label."),
      W("precaution", "Live vaccines", "moderate", "Avoid during treatment."),
    ],
    special: {
      pregnancy: "Often continued in pregnancy in IBD/rheumatology under specialist advice; infant live vaccines may need delay.",
      lactation: "Minimal transfer; generally considered compatible.",
      geriatric: "Higher infection risk.",
    },
    mon: ["TB and hepatitis B screening before treatment", "Infection signs", "Skin cancer checks", "Blood count/LFTs per specialist"],
    src: ["dailymed", "ema", "acr_ra", "nice"],
  }),
  med({
    name: "Tacrolimus",
    brands: ["Prograf", "Advagraf", "Envarsus", "Protopic"],
    cls: "Calcineurin inhibitor immunosuppressant",
    mech: "Binds FKBP-12, inhibiting calcineurin and T-cell activation (IL-2 transcription).",
    routes: ["oral", "IV", "topical"],
    reg: { US: US_OK + " (boxed warning: malignancies and serious infections)", EU: "Centrally authorised (EMA) — formulations not interchangeable" },
    eq: "Standard-of-care immunosuppressant after solid-organ transplantation; narrow therapeutic index.",
    ben: "Prevents transplant rejection; requires trough-level monitoring and strict brand/formulation consistency.",
    ind: [
      I("Prophylaxis of organ rejection (kidney, liver, heart)"),
      I("Treatment of allograft rejection resistant to other immunosuppressants"),
      I("Moderate–severe atopic dermatitis (topical ointment, Protopic)"),
    ],
    ae: [
      A("Tremor, headache, insomnia", "common"),
      A("Nephrotoxicity", "serious"),
      A("New-onset diabetes after transplant / hyperglycaemia", "serious"),
      A("Hypertension, hyperkalaemia, hypomagnesaemia", "common"),
      A("Serious infections and malignancy (lymphoma, skin cancer)", "boxed"),
      A("Neurotoxicity incl. PRES; QT prolongation", "serious", "moderate"),
      A("Skin burning/itching at application site (ointment)", "common", "moderate"),
    ],
    warn: [
      W("boxed", "Malignancies and serious infections", "major", "Specialist-supervised immunosuppression."),
      W("warning", "Formulation switching (immediate- vs prolonged-release)", "major", "Medication errors have led to rejection/toxicity — no substitution without specialist oversight."),
      W("warning", "CYP3A4/P-gp interactions", "major", "Azoles, macrolides, ritonavir, grapefruit raise levels; rifampicin, St John's wort lower them."),
    ],
    special: {
      pregnancy: "Used in transplant recipients under specialist care; monitor levels.",
      lactation: "Low infant exposure reported; specialist decision.",
      renal: "Monitor closely (nephrotoxicity).",
      hepatic: "Dose reduction in hepatic impairment.",
    },
    mon: ["Trough blood levels", "Renal function, potassium, magnesium", "Glucose", "Blood pressure", "Skin checks"],
    src: ["dailymed", "ema", "kdigo", "mhra"],
  }),
  med({
    name: "Hydroxyzine",
    brands: ["Atarax", "Vistaril"],
    cls: "First-generation H1 antihistamine (sedating)",
    mech: "H1-receptor antagonist with sedative, anxiolytic and anticholinergic properties.",
    routes: ["oral", "IM"],
    reg: { US: US_OK, EU: "Authorised nationally; EMA (2015) restricted use because of QT prolongation risk" },
    eq: "Effective for itch and short-term anxiety relief; EMA 2015 review confirmed a small QT/arrhythmia risk.",
    ben: "Sedating antihistamine for itch and short-term anxiety; QT and anticholinergic risks limit use in older people.",
    ind: [
      I("Pruritus (urticaria, atopic dermatitis)"),
      I("Symptomatic relief of anxiety (short-term)", "moderate"),
      I("Premedication / sedation before procedures", "moderate"),
    ],
    ae: [
      A("Drowsiness, dry mouth, headache", "common"),
      A("QT prolongation / torsades de pointes", "serious"),
      A("Confusion and falls in older adults", "serious", "moderate"),
      A("Acute generalised exanthematous pustulosis (rare)", "serious", "low"),
    ],
    warn: [
      W("contraindication", "Known QT prolongation or risk factors; other QT-prolonging drugs", "major", "EMA 2015 restrictions."),
      W("precaution", "Older adults", "major", "Avoid where possible (anticholinergic, sedation, QT)."),
      W("contraindication", "Pregnancy (EU product information)", "major", "See SmPC."),
    ],
    special: {
      pregnancy: "Contraindicated in EU product information.",
      lactation: "Avoid.",
      hepatic: "Dose reduction.",
      renal: "Dose reduction.",
      geriatric: "Beers criteria — avoid.",
    },
    mon: ["ECG in at-risk patients", "Sedation"],
    src: ["ema_hydroxyzine", "dailymed", "bnf", "ema"],
  }),
  med({
    name: "Lidocaine",
    brands: ["Xylocaine", "Versatis", "Lidoderm"],
    cls: "Amide local anaesthetic / class Ib antiarrhythmic",
    mech: "Blocks voltage-gated sodium channels in nerve and cardiac tissue.",
    routes: ["topical", "local injection", "IV", "transdermal patch"],
    reg: { US: US_OK + " (many products; viscous 2% boxed warning against teething use)" },
    eq: "Established local anaesthetic; patch evidence for postherpetic neuralgia is moderate.",
    ben: "Widely used for numbing skin and mucosa, nerve blocks and some neuropathic pain.",
    ind: [
      I("Local and regional anaesthesia (infiltration, nerve block)"),
      I("Topical anaesthesia of skin and mucous membranes"),
      I("Temporary relief of pain from minor burns and sunburn (selected non-prescription topical products, e.g., US OTC gels/sprays)", "low", true, "Product-specific labelling; check the individual product's leaflet."),
      I("Postherpetic neuralgia (5% patch)", "moderate"),
      I("Ventricular arrhythmias (IV, specialist)", "moderate"),
    ],
    ae: [
      A("Local irritation, redness (topical/patch)", "common"),
      A("Systemic toxicity — perioral numbness, tinnitus, confusion, seizures, arrhythmia, cardiac arrest", "serious"),
      A("Methaemoglobinaemia (especially infants, topical overuse)", "serious", "moderate"),
      A("Allergic reactions (rare for amides)", "serious", "low"),
    ],
    warn: [
      W("boxed", "Viscous lidocaine for infant teething (US)", "major", "Seizures and deaths reported — not for teething pain."),
      W("warning", "Maximum dose limits / large-area topical use", "major", "Systemic toxicity risk."),
      W("precaution", "Heart block, severe hepatic impairment", "moderate", "Accumulation and cardiac effects."),
    ],
    special: {
      pregnancy: "Local anaesthesia widely used in pregnancy.",
      lactation: "Compatible.",
      hepatic: "Reduced clearance.",
      pediatric: "Weight-based limits; teething warning.",
    },
    mon: ["Signs of systemic toxicity during procedures", "ECG with IV use"],
    src: ["dailymed", "fda", "bnf", "nice", "label_lidocaine_burn"],
  }),
  med({
    name: "Solifenacin",
    brands: ["Vesicare"],
    cls: "Antimuscarinic (bladder)",
    mech: "M3 muscarinic receptor antagonist relaxing the detrusor muscle.",
    reg: { US: US_OK },
    eq: "RCTs show modest reductions in urgency/incontinence episodes; anticholinergic burden is a concern in older adults.",
    ben: "Once-daily OAB treatment; mirabegron is an alternative with less anticholinergic burden.",
    ind: [
      I("Overactive bladder (urgency, urge incontinence, frequency)"),
      I("Neurogenic detrusor overactivity in children (US oral suspension)", "moderate"),
    ],
    ae: [
      A("Dry mouth (very common), constipation", "common"),
      A("Blurred vision", "common", "moderate"),
      A("Urinary retention", "serious"),
      A("Cognitive impairment / confusion in older adults (anticholinergic burden)", "serious", "moderate"),
      A("QT prolongation (high doses)", "moderate", "low"),
    ],
    warn: [
      W("contraindication", "Urinary or gastric retention, uncontrolled narrow-angle glaucoma, myasthenia gravis", "major", "See label."),
      W("precaution", "Older adults and dementia", "moderate", "Cumulative anticholinergic burden."),
      W("precaution", "Strong CYP3A4 inhibitors; hepatic/renal impairment", "moderate", "Dose limits."),
    ],
    special: {
      pregnancy: "Avoid.",
      lactation: "Avoid.",
      renal: "Dose limit in severe impairment.",
      hepatic: "Dose limit in moderate; avoid in severe.",
      geriatric: "Anticholinergic burden.",
    },
    mon: ["Symptom benefit at about 4–12 weeks", "Post-void residual if retention symptoms", "Cognition in older adults"],
    src: ["dailymed", "nice", "ema", "bnf"],
  }),
  med({
    name: "Dutasteride",
    brands: ["Avodart"],
    cls: "5-alpha reductase inhibitor (type 1 and 2)",
    mech: "Inhibits conversion of testosterone to dihydrotestosterone, shrinking the prostate.",
    reg: { US: US_OK },
    eq: "RCTs show reduced prostate volume, acute urinary retention and BPH surgery; combination with tamsulosin more effective than either alone (CombAT).",
    ben: "Long-term BPH therapy for enlarged prostates; benefits take months.",
    ind: [
      I("Symptomatic benign prostatic hyperplasia (enlarged prostate)"),
      I("Reduction of risk of acute urinary retention and BPH surgery"),
      I("Combination with tamsulosin for BPH"),
    ],
    ae: [
      A("Erectile dysfunction, decreased libido, ejaculation disorders", "common"),
      A("Breast enlargement/tenderness", "common", "moderate"),
      A("Possible increased risk of high-grade prostate cancer (label)", "serious", "moderate"),
      A("Depressed mood (reported)", "moderate", "low"),
    ],
    warn: [
      W("warning", "PSA interpretation", "major", "Lowers PSA by about 50% — values must be interpreted accordingly."),
      W("contraindication", "Women who are or may become pregnant; children", "major", "Should not handle leaking capsules (fetal male genital risk)."),
      W("precaution", "Blood donation", "moderate", "Do not donate until 6 months after the last dose."),
    ],
    special: {
      pregnancy: "Contraindicated (not for women).",
      hepatic: "Caution.",
      geriatric: "Primary population.",
    },
    mon: ["PSA with adjusted interpretation", "Urinary symptoms"],
    src: ["dailymed", "nice", "ema", "bnf"],
  }),
];
