import { med, I, A, W, US_OK, US_NO } from "./helpers.mjs";

// Analgesics, anticoagulants, GI, anti-infectives
export const MEDS_A = [
  med({
    name: "Metamizole (Dipyrone)",
    brands: ["Novalgin", "Minalgin", "Nolotil"],
    cls: "Non-opioid analgesic / antipyretic (pyrazolone)",
    mech: "Prodrug; active metabolites (e.g., 4-methylaminoantipyrine) inhibit prostaglandin synthesis, largely centrally; also spasmolytic. Mechanism not fully characterised.",
    routes: ["oral", "IV", "IM", "rectal"],
    reg: {
      US: "Not FDA-approved — removed from the US market in 1977 because of agranulocytosis risk",
      EU: "Nationally authorised in many EU member states; EMA harmonised dosing/pregnancy warnings (2019) and strengthened agranulocytosis warnings (2024)",
      UK: "Not licensed in the UK",
      CH: "Marketed in Switzerland (e.g., Novalgin, Minalgin) — verify current product information on swissmedicinfo.ch",
    },
    eq: "Effective analgesic/antipyretic with decades of use in continental Europe and Latin America; the key uncertainty is the incidence of agranulocytosis, which varies widely between studies and populations.",
    ben: "Used for moderate–severe pain, colicky pain and high fever when other analgesics are unsuitable or insufficient. Not an NSAID-type gastric/renal risk profile, but carries a rare, unpredictable risk of agranulocytosis.",
    why: "Frequently used in Switzerland, Germany and Austria as an alternative when NSAIDs are contraindicated (e.g., renal impairment, GI bleeding risk, anticoagulation), despite the agranulocytosis risk.",
    ind: [
      I("Severe acute or chronic pain when other analgesics are contraindicated or ineffective", "moderate"),
      I("High fever not responding to other measures", "moderate"),
      I("Colicky / spasmodic visceral pain (e.g., renal or biliary colic)", "moderate"),
    ],
    ae: [
      A("Agranulocytosis — can occur at any time, including after previous uneventful use; not dose-related; may be fatal", "serious", "high", "Rare to very rare; incidence estimates vary"),
      A("Hypotension / circulatory reactions, especially with rapid IV injection", "serious", "high"),
      A("Hypersensitivity reactions including anaphylaxis and bronchospasm (analgesic-intolerance asthma)", "serious", "high"),
      A("Severe cutaneous reactions (SJS/TEN, DRESS)", "serious", "moderate"),
      A("Drug-induced liver injury", "serious", "moderate"),
      A("Harmless red discoloration of urine (rubazonic acid metabolite)", "common", "moderate"),
    ],
    warn: [
      W("warning", "Anyone taking metamizole", "major", "Stop and seek immediate medical care (urgent blood count) if fever, chills, sore throat or painful mouth/nose/genital sores develop during or shortly after treatment (EMA 2024)."),
      W("contraindication", "Previous agranulocytosis with metamizole/pyrazolones, bone-marrow disorders or haematopoietic disease", "major", "Must not be used (EMA 2024)."),
      W("contraindication", "Third trimester of pregnancy; breastfeeding", "major", "EMA-harmonised contraindications (2019)."),
      W("contraindication", "Acute hepatic porphyria; G6PD deficiency; known analgesic-induced asthma/urticaria", "major", "See product information."),
      W("precaution", "IV administration", "moderate", "Risk of hypotension — slow injection, patient lying down, haemodynamic monitoring."),
    ],
    special: {
      pregnancy: "Limited data. EMA (2019): single doses in the first 6 months may be acceptable if other analgesics cannot be used; contraindicated in the last 3 months (fetal kidney/ductus effects).",
      lactation: "Should not be used during breastfeeding (EMA 2019) — metabolites pass into milk in relevant amounts.",
      renal: "Caution; avoid high doses in renal impairment.",
      hepatic: "Caution; liver injury has been reported.",
      geriatric: "Caution — consider lower doses; agranulocytosis may present atypically.",
      pediatric: "Product-specific age/weight limits; not for infants under 3 months or under 5 kg.",
    },
    mon: ["Urgent differential blood count if fever, sore throat or mucosal sores develop", "Blood pressure during IV administration", "Liver tests if symptoms of liver injury"],
    src: ["ema_metamizole_2024", "ema_metamizole_2019", "swissmedic_pi", "compendium_ch"],
  }),
  med({
    name: "Phenprocoumon",
    brands: ["Marcoumar", "Marcumar", "Falithrom"],
    cls: "Vitamin K antagonist anticoagulant",
    mech: "Inhibits vitamin K epoxide reductase (VKORC1), reducing synthesis of clotting factors II, VII, IX, X and proteins C and S. Very long half-life (about 5–6 days).",
    reg: {
      US: "Not approved in the US",
      EU: "Nationally authorised in some EU countries (e.g., Germany, Netherlands)",
      UK: "Not licensed in the UK",
      CH: "Marketed in Switzerland as Marcoumar — verify current product information on swissmedicinfo.ch",
    },
    eq: "Long-established VKA; efficacy extrapolated from VKA trials and decades of use. DOACs are now preferred for many non-valvular AF/VTE patients, but VKAs remain required for mechanical valves.",
    ben: "Oral anticoagulant with INR-guided dosing; the standard VKA in Switzerland and Germany. Its long half-life gives stable INR in some patients but slow offset/reversal.",
    why: "Required for mechanical heart valves and some patients unsuitable for DOACs (e.g., antiphospholipid syndrome, severe renal impairment, cost/coverage).",
    ind: [
      I("Prevention and treatment of venous thromboembolism (DVT / pulmonary embolism)"),
      I("Stroke and systemic embolism prevention in atrial fibrillation"),
      I("Mechanical heart valve thromboprophylaxis"),
    ],
    ae: [
      A("Bleeding (minor to life-threatening, including intracranial and GI bleeding)", "serious"),
      A("Hepatitis / liver injury (reported with phenprocoumon)", "serious", "moderate"),
      A("Coumarin-induced skin necrosis (rare, early in therapy)", "serious", "moderate"),
      A("Hair loss", "moderate", "moderate"),
      A("Nausea, loss of appetite", "common", "moderate"),
    ],
    warn: [
      W("contraindication", "Pregnancy", "major", "Coumarin embryopathy and fetal bleeding risk."),
      W("contraindication", "Active bleeding or high bleeding risk; severe hepatic impairment", "major", "See product information."),
      W("warning", "Drug, food and supplement interactions", "major", "NSAIDs, antiplatelets, many antibiotics, azole antifungals, amiodarone, St John's wort and diet changes alter INR or bleeding risk."),
      W("precaution", "Long half-life", "moderate", "Effect persists for days to weeks after the last dose; reversal (vitamin K / clotting factors) must be clinician-managed."),
    ],
    special: {
      pregnancy: "Contraindicated (teratogenic; fetal haemorrhage).",
      lactation: "Small amounts pass into milk; product information advises vitamin K prophylaxis for the infant — clinician decision.",
      renal: "Can be used with caution; bleeding risk higher in renal impairment.",
      hepatic: "Contraindicated in severe hepatic impairment; liver function monitoring recommended.",
      geriatric: "Higher bleeding and fall-related risk; frequent INR checks.",
    },
    mon: ["INR regularly (more often at start and after changes)", "Liver function tests", "Signs of bleeding", "Interaction review whenever a medicine is started or stopped"],
    wd: "Do not stop on your own — stopping raises clot and stroke risk. Because of the long half-life the effect wears off slowly over 1–2 weeks; peri-procedural interruption must be planned by the treating clinician.",
    src: ["swissmedic_pi", "compendium_ch", "esc_hf", "chest_vte"],
  }),
  med({
    name: "Acenocoumarol",
    brands: ["Sintrom", "Sinthrome"],
    cls: "Vitamin K antagonist anticoagulant",
    mech: "Inhibits VKORC1, reducing vitamin K-dependent clotting factors (II, VII, IX, X) and proteins C/S. Shorter half-life (about 8–11 h) than warfarin or phenprocoumon.",
    reg: {
      US: "Not approved in the US",
      EU: "Nationally authorised in several EU countries (e.g., Spain, France, Netherlands)",
      UK: "Listed in BNF (Sinthrome) — check MHRA product information",
      CH: "Marketed in Switzerland (Sintrom) — verify current product information on swissmedicinfo.ch",
    },
    eq: "Established VKA; efficacy extrapolated from VKA class evidence. Shorter half-life can produce more INR variability.",
    ben: "INR-guided oral anticoagulant used in several European countries; same core indications and risks as other VKAs.",
    ind: [
      I("Prevention and treatment of venous thromboembolism"),
      I("Stroke prevention in atrial fibrillation"),
      I("Mechanical heart valve thromboprophylaxis"),
    ],
    ae: [
      A("Bleeding (minor to life-threatening)", "serious"),
      A("Skin necrosis (rare)", "serious", "moderate"),
      A("Allergic skin reactions / rash", "moderate", "moderate"),
      A("Hair loss", "moderate", "low"),
      A("Nausea, vomiting, diarrhoea", "common", "moderate"),
    ],
    warn: [
      W("contraindication", "Pregnancy", "major", "Teratogenic (coumarin embryopathy)."),
      W("contraindication", "Active bleeding / high bleeding risk; severe hepatic impairment", "major", "See product information."),
      W("warning", "Numerous drug interactions", "major", "NSAIDs, antiplatelets, co-trimoxazole, azoles, amiodarone and enzyme inducers change INR/bleeding risk."),
    ],
    special: {
      pregnancy: "Contraindicated.",
      lactation: "Generally considered compatible with monitoring; follow product information.",
      hepatic: "Contraindicated in severe hepatic impairment.",
      geriatric: "Higher bleeding risk; close INR monitoring.",
    },
    mon: ["INR regularly", "Signs of bleeding", "Interaction review"],
    wd: "Do not stop without the prescriber — stopping increases clot and stroke risk.",
    src: ["swissmedic_pi", "compendium_ch", "bnf", "chest_vte"],
  }),
  med({
    name: "Mefenamic acid",
    brands: ["Ponstan", "Ponstel"],
    cls: "NSAID (fenamate)",
    mech: "Non-selective COX-1/COX-2 inhibition reducing prostaglandin synthesis.",
    reg: { US: US_OK },
    eq: "Label-supported for short-term pain and primary dysmenorrhoea; comparative advantage over other NSAIDs not established.",
    ben: "Short-term NSAID option commonly used for period pain; shares NSAID class GI, CV and renal risks.",
    ind: [
      I("Mild to moderate acute pain (short-term)"),
      I("Primary dysmenorrhoea (period pain)"),
      I("Heavy menstrual bleeding (selected labels, e.g., UK)", "moderate"),
    ],
    ae: [
      A("Diarrhoea (stop if it occurs), nausea, dyspepsia", "common"),
      A("GI ulceration and bleeding", "serious"),
      A("Cardiovascular thrombotic events (NSAID class)", "boxed"),
      A("Acute kidney injury", "serious", "moderate"),
      A("Haemolytic anaemia (rare)", "serious", "low"),
    ],
    warn: [
      W("boxed", "Cardiovascular and GI risk (US NSAID boxed warning)", "major", "Avoid after CABG surgery; risk increases with dose and duration."),
      W("contraindication", "Active GI ulcer/bleeding, inflammatory bowel disease, severe renal impairment", "major", "See label."),
      W("warning", "Third trimester of pregnancy", "major", "NSAIDs can cause premature ductus closure and fetal renal problems."),
    ],
    special: {
      pregnancy: "Avoid, especially from 20 weeks (oligohydramnios) and in the third trimester.",
      lactation: "Generally avoid or use alternatives with more data.",
      renal: "Avoid in significant renal impairment.",
      geriatric: "Higher GI bleeding and renal risk.",
    },
    mon: ["Signs of GI bleeding", "Renal function and BP if used repeatedly or in at-risk patients"],
    src: ["dailymed", "fda_nsaid_boxed", "bnf", "swissmedic_pi"],
  }),
  med({
    name: "Etoricoxib",
    brands: ["Arcoxia"],
    cls: "NSAID (COX-2 selective inhibitor)",
    mech: "Selective COX-2 inhibition reducing inflammatory prostaglandins with less COX-1 (gastric/platelet) effect.",
    reg: { US: "Not FDA-approved (US application not approved in 2007)" },
    eq: "RCT evidence for arthritis and gout pain; CV safety program (MEDAL) informed contraindications in established cardiovascular disease.",
    ben: "COX-2 selective option with lower ulcer risk than non-selective NSAIDs but with CV and blood-pressure risks.",
    ind: [
      I("Osteoarthritis and rheumatoid arthritis symptoms"),
      I("Ankylosing spondylitis"),
      I("Acute gouty arthritis (short-term)"),
      I("Short-term moderate postoperative dental pain (selected labels)", "moderate"),
    ],
    ae: [
      A("Hypertension, oedema", "common"),
      A("Cardiovascular thrombotic events (MI, stroke)", "serious"),
      A("GI ulceration/bleeding (lower than non-selective NSAIDs but present)", "serious"),
      A("Renal impairment, hyperkalaemia", "serious", "moderate"),
      A("Elevated liver enzymes", "moderate", "moderate"),
    ],
    warn: [
      W("contraindication", "Uncontrolled hypertension; ischaemic heart disease, peripheral arterial or cerebrovascular disease; heart failure (NYHA II–IV)", "major", "EU product information."),
      W("warning", "Blood pressure", "major", "BP should be checked within about two weeks of starting and periodically."),
      W("contraindication", "Active peptic ulcer/GI bleeding; severe hepatic impairment; CrCl <30 mL/min", "major", "See SmPC."),
    ],
    special: {
      pregnancy: "Contraindicated in the third trimester; avoid in pregnancy.",
      lactation: "Not recommended.",
      renal: "Contraindicated with CrCl <30 mL/min.",
      hepatic: "Dose limits in mild–moderate; contraindicated in severe impairment.",
      geriatric: "Higher CV/renal/GI risk.",
    },
    mon: ["Blood pressure (early and periodically)", "Renal function in at-risk patients", "Signs of GI bleeding"],
    src: ["ema", "bnf", "swissmedic_pi", "acr_gout"],
  }),
  med({
    name: "Tapentadol",
    brands: ["Palexia", "Nucynta"],
    cls: "Opioid analgesic (mu-opioid agonist + noradrenaline reuptake inhibitor)",
    mech: "Mu-opioid receptor agonism combined with noradrenaline reuptake inhibition.",
    routes: ["oral"],
    reg: { US: US_OK },
    eq: "RCTs support efficacy in acute and chronic pain; some data suggest less GI intolerance than pure opioids, but class risks of dependence and respiratory depression apply.",
    ben: "Strong analgesic for pain not controlled by non-opioids; carries opioid class risks.",
    ind: [
      I("Moderate to severe acute pain (immediate-release)"),
      I("Severe chronic pain requiring long-term opioid treatment (prolonged-release)"),
      I("Painful diabetic peripheral neuropathy (US extended-release label)", "moderate"),
    ],
    ae: [
      A("Nausea, dizziness, somnolence, constipation, headache", "common"),
      A("Respiratory depression", "boxed"),
      A("Addiction, abuse and misuse", "boxed"),
      A("Serotonin syndrome with serotonergic drugs", "serious", "moderate"),
      A("Seizures (lowered threshold)", "serious", "moderate"),
    ],
    warn: [
      W("boxed", "Addiction, respiratory depression, accidental ingestion; neonatal opioid withdrawal", "major", "US boxed warnings for opioids."),
      W("boxed", "Concomitant benzodiazepines or other CNS depressants", "major", "Profound sedation, respiratory depression, coma, death."),
      W("contraindication", "MAOIs within 14 days", "major", "Hypertensive/serotonergic risk."),
    ],
    special: {
      pregnancy: "Prolonged use can cause neonatal opioid withdrawal syndrome.",
      lactation: "Not recommended.",
      renal: "Not recommended in severe renal impairment.",
      hepatic: "Dose adjustment in moderate; avoid in severe impairment.",
      geriatric: "Start low; falls and sedation risk.",
    },
    mon: ["Pain and function goals", "Sedation and respiratory status", "Signs of misuse", "Bowel function"],
    wd: "Withdrawal symptoms (anxiety, sweating, insomnia, rigors, pain, diarrhoea) can occur on abrupt stopping after regular use — tapering should be clinician-guided.",
    src: ["dailymed", "fda", "ema", "bnf"],
  }),
  med({
    name: "Oxazepam",
    brands: ["Seresta", "Serax"],
    cls: "Benzodiazepine",
    mech: "Positive allosteric modulation of GABA-A receptors. Metabolised by glucuronidation without active metabolites.",
    reg: { US: US_OK },
    eq: "Established short-term anxiolytic; long-term benefit not established and dependence risk is well documented.",
    ben: "Shorter-acting benzodiazepine sometimes chosen in older adults or liver disease because it lacks active metabolites; dependence and falls risks remain.",
    ind: [
      I("Short-term treatment of anxiety"),
      I("Alcohol withdrawal symptoms"),
      I("Insomnia associated with anxiety (short-term, selected labels)", "moderate"),
    ],
    ae: [
      A("Drowsiness, dizziness, impaired coordination", "common"),
      A("Falls and fractures in older adults", "serious"),
      A("Dependence and withdrawal reactions", "boxed"),
      A("Respiratory depression with opioids/alcohol", "serious"),
      A("Paradoxical agitation (rare)", "moderate", "moderate"),
    ],
    warn: [
      W("boxed", "Concomitant opioids", "major", "Profound sedation, respiratory depression, coma and death."),
      W("boxed", "Abuse, misuse, addiction, dependence and withdrawal", "major", "US benzodiazepine class boxed warning (2020)."),
      W("contraindication", "Severe respiratory insufficiency, sleep apnoea, myasthenia gravis", "major", "See product information."),
    ],
    special: {
      pregnancy: "Avoid if possible; neonatal sedation/withdrawal near term.",
      lactation: "Passes into milk; monitor infant sedation — clinician decision.",
      hepatic: "Often preferred over long-acting benzodiazepines in liver disease, but caution in severe impairment/encephalopathy.",
      geriatric: "Beers criteria — avoid where possible; falls, cognitive impairment.",
    },
    mon: ["Sedation and falls risk", "Duration of use / dependence", "Concomitant CNS depressants"],
    wd: "Abrupt stopping after regular use can cause rebound anxiety, insomnia and, rarely, seizures — taper with clinician guidance.",
    src: ["dailymed", "fda_benzo", "swissmedic_pi", "bnf"],
  }),
  med({
    name: "Domperidone",
    brands: ["Motilium"],
    cls: "Peripheral dopamine D2 antagonist (antiemetic / prokinetic)",
    mech: "Blocks dopamine D2 receptors in the chemoreceptor trigger zone (outside the blood–brain barrier) and upper GI tract.",
    reg: {
      US: "Not FDA-approved (only restricted investigational access)",
      EU: "Authorised nationally; restricted in 2014 to short-term relief of nausea/vomiting at the lowest dose (EMA referral)",
      CH: "Check current Swiss product information (swissmedicinfo.ch) — cardiac restrictions apply",
    },
    eq: "Effective antiemetic; EMA 2014 review confirmed small increased risk of serious ventricular arrhythmia / sudden cardiac death, especially at higher doses and age >60.",
    ben: "Antiemetic with fewer central extrapyramidal effects than metoclopramide, but with QT/cardiac risk and many contraindicated combinations.",
    ind: [
      I("Short-term relief of nausea and vomiting", "moderate"),
      I("Gastroparesis symptoms", "low", false, "Not an EU-authorised indication after 2014; US access only via restricted programs"),
      I("Stimulation of breast-milk supply", "low", false, "Off-label; cardiac risk to the mother must be weighed"),
    ],
    ae: [
      A("QT prolongation, serious ventricular arrhythmia, sudden cardiac death", "serious", "high", "Higher risk >30 mg/day or age >60"),
      A("Hyperprolactinaemia — breast enlargement, galactorrhoea, menstrual changes", "moderate"),
      A("Dry mouth, headache", "common", "moderate"),
      A("Extrapyramidal effects (rare)", "moderate", "low"),
    ],
    warn: [
      W("contraindication", "QT-prolonging drugs and potent CYP3A4 inhibitors (e.g., clarithromycin, ritonavir-boosted regimens)", "major", "EMA 2014 restrictions."),
      W("contraindication", "Moderate–severe hepatic impairment; known QT prolongation, significant electrolyte disturbance or cardiac disease", "major", "See SmPC."),
      W("warning", "Duration and dose", "major", "EU: lowest effective dose for the shortest time (generally not longer than one week)."),
    ],
    special: {
      pregnancy: "Limited data — avoid unless clearly needed.",
      lactation: "Passes into milk in small amounts; maternal cardiac risk is the main concern.",
      renal: "Dose frequency reduction in severe renal impairment.",
      hepatic: "Contraindicated in moderate–severe impairment.",
      geriatric: "Higher risk of sudden cardiac death >60 years.",
    },
    mon: ["ECG/QT and electrolytes in at-risk patients", "Interaction review before starting"],
    src: ["ema_domperidone", "ema", "mhra", "swissmedic_pi"],
  }),
  med({
    name: "Metoclopramide",
    brands: ["Paspertin", "Primperan", "Reglan", "Maxolon"],
    cls: "Dopamine D2 antagonist (antiemetic / prokinetic)",
    mech: "Central D2 blockade (chemoreceptor trigger zone) and peripheral prokinetic effects (5-HT4 agonism, D2 blockade).",
    routes: ["oral", "IV", "IM"],
    reg: {
      US: US_OK,
      EU: "Authorised nationally; EMA 2013 restricted use to short-term (up to 5 days) because of neurological risks",
    },
    eq: "Effective antiemetic and prokinetic; EMA (2013) and FDA (boxed warning, 2009) emphasise neurological risks with longer use.",
    ben: "Widely used short-term antiemetic, including migraine-associated nausea; tardive dyskinesia risk limits duration.",
    ind: [
      I("Short-term prevention/treatment of nausea and vomiting (incl. postoperative, chemotherapy-delayed, migraine-associated)"),
      I("Diabetic gastroparesis (US label; short courses)", "moderate"),
      I("Symptomatic GERD in adults not responding to other therapy (US label, short-term)", "moderate"),
    ],
    ae: [
      A("Tardive dyskinesia (risk rises with duration and cumulative dose)", "boxed"),
      A("Acute dystonic reactions (more common in young people)", "serious"),
      A("Drowsiness, restlessness/akathisia, fatigue", "common"),
      A("Neuroleptic malignant syndrome (rare)", "serious", "moderate"),
      A("Depression", "moderate", "moderate"),
    ],
    warn: [
      W("boxed", "Treatment longer than 12 weeks (US)", "major", "Tardive dyskinesia — often irreversible."),
      W("contraindication", "GI obstruction/perforation/haemorrhage, phaeochromocytoma, epilepsy, Parkinson's disease or levodopa/dopamine agonist therapy", "major", "See product information."),
      W("contraindication", "Children under 1 year (EU)", "major", "Extrapyramidal risk; restricted use in older children."),
    ],
    special: {
      pregnancy: "Large datasets do not show major malformation risk; avoid near term repeatedly (neonatal EPS).",
      lactation: "Small amounts in milk; short-term use generally acceptable — clinician decision.",
      renal: "Dose reduction in moderate–severe renal impairment.",
      hepatic: "Dose reduction in severe impairment.",
      geriatric: "Higher tardive dyskinesia risk.",
      pediatric: "Restricted (EU: not under 1 year; second-line in older children).",
    },
    mon: ["Abnormal movements (stop if they appear)", "Duration of therapy"],
    src: ["ema_metoclopramide", "dailymed", "bnf", "swissmedic_pi"],
  }),
  med({
    name: "Butylscopolamine (Hyoscine butylbromide)",
    brands: ["Buscopan"],
    cls: "Antimuscarinic antispasmodic (quaternary)",
    mech: "Blocks muscarinic receptors on GI/genitourinary smooth muscle; quaternary structure limits CNS penetration and oral absorption.",
    routes: ["oral", "IV", "IM", "rectal"],
    reg: { US: US_NO },
    eq: "Some RCT evidence for abdominal cramping/IBS symptoms; injection widely used for colic and radiology, with MHRA (2017) warnings about cardiac adverse effects.",
    ben: "Common over-the-counter antispasmodic for abdominal cramps in Europe; injection used in hospital for colic and imaging.",
    ind: [
      I("Abdominal cramping / GI smooth-muscle spasm", "moderate"),
      I("IBS-related cramping (selected labels)", "moderate"),
      I("Renal or biliary colic and as an adjunct in GI imaging (injection)", "moderate"),
    ],
    ae: [
      A("Dry mouth, constipation", "common"),
      A("Tachycardia, palpitations", "moderate"),
      A("Urinary retention, blurred vision", "moderate"),
      A("Serious reactions after injection — anaphylaxis, and tachycardia/hypotension in patients with heart disease", "serious", "moderate"),
    ],
    warn: [
      W("warning", "Injection in patients with cardiac disease", "major", "MHRA 2017: can cause serious adverse effects including tachycardia, hypotension and anaphylaxis — monitor; use with caution."),
      W("contraindication", "Myasthenia gravis, megacolon, untreated narrow-angle glaucoma, tachyarrhythmia, mechanical GI stenosis", "major", "See product information."),
      W("precaution", "Prostatic enlargement / urinary retention", "moderate", "Anticholinergic effects."),
    ],
    special: {
      pregnancy: "Limited data — avoid unless clearly needed.",
      lactation: "Limited data; low oral absorption.",
      geriatric: "Anticholinergic effects (retention, constipation, tachycardia).",
    },
    mon: ["Heart rate/BP after injection in cardiac patients", "Urinary retention in at-risk men"],
    src: ["mhra", "bnf", "swissmedic_pi", "compendium_ch"],
  }),
  med({
    name: "Mesalazine (Mesalamine)",
    brands: ["Asacol", "Pentasa", "Salofalk", "Lialda"],
    cls: "Aminosalicylate (5-ASA)",
    mech: "Topical anti-inflammatory action on colonic mucosa (multiple mechanisms incl. PPAR-gamma, prostaglandin/leukotriene modulation).",
    routes: ["oral", "rectal"],
    reg: { US: US_OK + " (as mesalamine)" },
    eq: "High-quality RCT evidence for induction and maintenance of remission in mild–moderate ulcerative colitis; limited benefit in Crohn's disease.",
    ben: "First-line therapy for mild–moderate ulcerative colitis; generally well tolerated with rare renal and hypersensitivity risks.",
    ind: [
      I("Induction of remission in mild–moderate ulcerative colitis"),
      I("Maintenance of remission in ulcerative colitis"),
      I("Distal / proctitis disease via suppositories or enemas"),
      I("Crohn's disease", "low", false, "Benefit not well established"),
    ],
    ae: [
      A("Headache, nausea, abdominal pain, diarrhoea", "common"),
      A("Interstitial nephritis / renal impairment", "serious", "moderate"),
      A("Pancreatitis, myocarditis/pericarditis (rare)", "serious", "moderate"),
      A("Blood dyscrasias (rare)", "serious", "moderate"),
      A("Severe cutaneous reactions (SJS/TEN, DRESS) and kidney stones (rare)", "serious", "moderate"),
    ],
    warn: [
      W("warning", "Renal function", "major", "Check renal function before and periodically during treatment."),
      W("contraindication", "Salicylate hypersensitivity; severe renal or hepatic impairment", "major", "See label."),
      W("precaution", "Mesalazine-induced acute intolerance syndrome", "moderate", "Can mimic a colitis flare (cramping, bloody diarrhoea, fever)."),
    ],
    special: {
      pregnancy: "Generally considered compatible; continue under specialist advice.",
      lactation: "Generally compatible; rare infant diarrhoea reported.",
      renal: "Avoid in severe impairment; monitor.",
      hepatic: "Caution.",
      geriatric: "Monitor renal function and blood counts.",
    },
    mon: ["Renal function (creatinine/eGFR) at baseline and periodically", "Blood count if symptoms suggestive of dyscrasia"],
    src: ["dailymed", "ema", "nice", "bnf"],
  }),
  med({
    name: "Macrogol (Polyethylene glycol)",
    brands: ["Movicol", "MiraLAX", "Laxido"],
    cls: "Osmotic laxative",
    mech: "Non-absorbed polymer retains water in the bowel lumen, softening stool and increasing volume.",
    routes: ["oral"],
    reg: { US: US_OK + " (PEG 3350, OTC)" },
    eq: "RCTs and guidelines support macrogol as first-line osmotic laxative for chronic constipation in adults and children.",
    ben: "Effective, generally well-tolerated laxative; also used in high doses for faecal impaction and as part of bowel-cleansing preparations.",
    ind: [
      I("Chronic constipation"),
      I("Faecal impaction (higher-dose regimens, selected products)"),
      I("Bowel cleansing before colonoscopy (electrolyte-containing preparations)"),
    ],
    ae: [
      A("Bloating, abdominal discomfort, flatulence", "common"),
      A("Diarrhoea", "common"),
      A("Nausea", "common", "moderate"),
      A("Electrolyte/fluid disturbance with large-volume bowel preparations", "serious", "moderate"),
      A("Hypersensitivity (rare)", "serious", "low"),
    ],
    warn: [
      W("contraindication", "Intestinal obstruction or perforation, ileus, severe inflammatory bowel disease/toxic megacolon", "major", "See product information."),
      W("precaution", "Frail, elderly or renally impaired patients using bowel-prep volumes", "moderate", "Risk of dehydration and electrolyte imbalance."),
      W("precaution", "Persistent constipation or new change in bowel habit", "moderate", "Warrants medical assessment for underlying cause."),
    ],
    special: {
      pregnancy: "Minimal absorption — commonly used.",
      lactation: "Compatible.",
      pediatric: "Paediatric formulations exist; follow product-specific age limits.",
      geriatric: "Watch hydration.",
    },
    mon: ["Fluid and electrolytes when used in large volumes or in frail patients"],
    src: ["dailymed", "nice", "bnf", "nhs_medicines"],
  }),
  med({
    name: "Lactulose",
    brands: ["Duphalac", "Kristalose"],
    cls: "Osmotic laxative / ammonia-lowering agent",
    mech: "Non-absorbed disaccharide fermented by colonic bacteria to organic acids; draws water into the bowel and traps ammonia as ammonium.",
    routes: ["oral", "rectal"],
    reg: { US: US_OK },
    eq: "Established for constipation; strong guideline support for hepatic encephalopathy treatment and secondary prevention.",
    ben: "Laxative also central to hepatic encephalopathy management; flatulence and bloating are common.",
    ind: [
      I("Constipation"),
      I("Treatment of hepatic encephalopathy"),
      I("Prevention of recurrent hepatic encephalopathy"),
    ],
    ae: [
      A("Flatulence, bloating, abdominal cramps", "common"),
      A("Diarrhoea (dose-related)", "common"),
      A("Fluid/electrolyte imbalance (hypokalaemia, hypernatraemia) with excessive diarrhoea", "serious", "moderate"),
      A("Nausea", "common", "moderate"),
    ],
    warn: [
      W("contraindication", "Galactosaemia; GI obstruction or perforation", "major", "See product information."),
      W("precaution", "Lactose intolerance; diabetes (contains small amounts of lactose/galactose)", "moderate", "Usually not significant at laxative doses."),
      W("precaution", "Excessive diarrhoea in hepatic encephalopathy", "moderate", "Can cause dehydration/electrolyte disturbance that worsens encephalopathy."),
    ],
    special: {
      pregnancy: "Not absorbed — considered compatible.",
      lactation: "Compatible.",
      pediatric: "Used in children; product-specific dosing.",
      geriatric: "Watch electrolytes with prolonged use.",
    },
    mon: ["Electrolytes with prolonged/high-dose use", "Stool frequency target in hepatic encephalopathy (clinician-set)"],
    src: ["dailymed", "bnf", "nice", "ema"],
  }),
  med({
    name: "Bisacodyl",
    brands: ["Dulcolax"],
    cls: "Stimulant laxative",
    mech: "Converted to an active metabolite that stimulates colonic motility and secretion.",
    routes: ["oral", "rectal"],
    reg: { US: US_OK + " (OTC)" },
    eq: "RCT evidence supports short-term efficacy in chronic constipation.",
    ben: "Fast-acting stimulant laxative for short-term use and bowel preparation; cramping is common.",
    ind: [
      I("Constipation (short-term)"),
      I("Bowel preparation before procedures (as part of regimens)"),
      I("Opioid-induced constipation (guideline-supported)", "moderate"),
    ],
    ae: [
      A("Abdominal cramps and discomfort", "common"),
      A("Diarrhoea", "common"),
      A("Fluid and electrolyte disturbance with overuse", "serious", "moderate"),
      A("Rectal irritation (suppositories)", "common", "moderate"),
    ],
    warn: [
      W("contraindication", "Ileus, intestinal obstruction, acute abdomen (e.g., appendicitis), severe dehydration", "major", "See product information."),
      W("precaution", "Prolonged daily use without medical advice", "moderate", "Persistent constipation needs assessment."),
    ],
    special: {
      pregnancy: "Short-term use generally considered acceptable — ask a clinician.",
      lactation: "Not excreted in meaningful amounts.",
      pediatric: "Product-specific age limits.",
      geriatric: "Watch hydration and electrolytes.",
    },
    mon: ["Electrolytes if used heavily or in frail patients"],
    src: ["dailymed", "bnf", "nhs_medicines", "nice"],
  }),
  med({
    name: "Ursodeoxycholic acid",
    brands: ["Ursofalk", "Actigall", "Urso"],
    cls: "Hydrophilic bile acid",
    mech: "Replaces more toxic hydrophobic bile acids, improves bile flow and reduces cholesterol saturation of bile.",
    reg: { US: US_OK + " (as ursodiol)" },
    eq: "Guideline first-line therapy for primary biliary cholangitis; established for dissolution of small cholesterol gallstones in selected patients.",
    ben: "Well-tolerated bile acid used long-term in PBC and for selected gallstone patients.",
    ind: [
      I("Primary biliary cholangitis (PBC)"),
      I("Dissolution of small radiolucent cholesterol gallstones in a functioning gallbladder"),
      I("Prevention of gallstones during rapid weight loss (US label)", "moderate"),
    ],
    ae: [
      A("Diarrhoea, loose stools", "common"),
      A("Right upper abdominal pain", "common", "moderate"),
      A("Pruritus", "moderate", "moderate"),
      A("Hepatic decompensation in advanced cirrhosis (rare)", "serious", "moderate"),
    ],
    warn: [
      W("contraindication", "Calcified/radio-opaque stones, non-functioning gallbladder, acute cholecystitis/cholangitis, biliary obstruction", "major", "See product information."),
      W("precaution", "Advanced (decompensated) cirrhosis", "major", "Monitor closely."),
    ],
    special: {
      pregnancy: "Used in intrahepatic cholestasis of pregnancy (specialist); otherwise limited data.",
      lactation: "Limited data; generally considered low risk.",
      hepatic: "Caution in decompensated cirrhosis.",
    },
    mon: ["Liver function tests periodically", "Gallstone imaging during dissolution therapy"],
    src: ["dailymed", "ema", "bnf", "nice"],
  }),
  med({
    name: "Trimethoprim",
    brands: ["Monotrim", "Primsol"],
    cls: "Dihydrofolate reductase inhibitor antibacterial",
    mech: "Inhibits bacterial dihydrofolate reductase, blocking folate synthesis.",
    reg: { US: US_OK },
    eq: "Long-used first-line option for uncomplicated cystitis where local resistance is acceptable; resistance rates vary regionally.",
    ben: "Inexpensive oral antibiotic for uncomplicated UTI; hyperkalaemia and folate antagonism are key safety issues.",
    ind: [
      I("Uncomplicated lower urinary tract infection (cystitis)"),
      I("Prophylaxis of recurrent urinary tract infection", "moderate"),
      I("Pneumocystis pneumonia (with dapsone, specialist use)", "moderate", false, "Off-label in many jurisdictions"),
    ],
    ae: [
      A("Rash, pruritus", "common"),
      A("Nausea, vomiting", "common", "moderate"),
      A("Hyperkalaemia (especially elderly, renal impairment, with ACEI/ARB/spironolactone)", "serious"),
      A("Bone-marrow suppression / megaloblastic anaemia (folate antagonism)", "serious", "moderate"),
      A("Severe skin reactions (rare)", "serious", "low"),
    ],
    warn: [
      W("warning", "First trimester of pregnancy", "major", "Folate antagonist — avoid unless benefits outweigh risks."),
      W("warning", "Hyperkalaemia risk with potassium-raising drugs", "major", "ACE inhibitors, ARBs, spironolactone."),
      W("precaution", "Renal impairment; folate deficiency; blood dyscrasias", "moderate", "Dose adjustment/avoid as per label. Creatinine may rise without true GFR change."),
    ],
    special: {
      pregnancy: "Avoid in first trimester (folate antagonism).",
      lactation: "Short courses generally acceptable.",
      renal: "Dose reduction in renal impairment; hyperkalaemia risk.",
      geriatric: "Hyperkalaemia risk.",
    },
    mon: ["Potassium in at-risk patients", "Blood count with prolonged use"],
    src: ["dailymed", "nice", "bnf", "who_aWaRe"],
  }),
  med({
    name: "Cefuroxime",
    brands: ["Zinnat", "Ceftin", "Zinacef"],
    cls: "Second-generation cephalosporin antibiotic",
    mech: "Beta-lactam inhibiting bacterial cell-wall synthesis (PBP binding).",
    routes: ["oral", "IV", "IM"],
    reg: { US: US_OK },
    eq: "Label- and guideline-supported for common respiratory, urinary and skin infections where susceptible.",
    ben: "Broad-spectrum oral/IV cephalosporin; C. difficile and hypersensitivity are key risks.",
    ind: [
      I("Respiratory tract infections (sinusitis, otitis media, pharyngitis/tonsillitis, community-acquired pneumonia)"),
      I("Uncomplicated urinary tract infections"),
      I("Skin and soft-tissue infections"),
      I("Early Lyme disease (cefuroxime axetil)"),
    ],
    ae: [
      A("Diarrhoea, nausea", "common"),
      A("Clostridioides difficile-associated diarrhoea", "serious"),
      A("Hypersensitivity reactions including anaphylaxis", "serious"),
      A("Transient liver enzyme elevation, eosinophilia", "moderate", "moderate"),
      A("Jarisch–Herxheimer reaction when treating Lyme disease", "moderate", "moderate"),
    ],
    warn: [
      W("contraindication", "History of severe immediate hypersensitivity to beta-lactams", "major", "Cross-reactivity risk."),
      W("warning", "C. difficile", "major", "Seek care for severe or persistent diarrhoea."),
      W("precaution", "Renal impairment", "moderate", "Dose adjustment for IV formulation."),
    ],
    special: {
      pregnancy: "Cephalosporins generally considered compatible.",
      lactation: "Generally compatible.",
      renal: "Dose adjust (IV).",
    },
    mon: ["Clinical response", "Diarrhoea"],
    src: ["dailymed", "ema", "bnf", "who_aWaRe"],
  }),
  med({
    name: "Cefalexin (Cephalexin)",
    brands: ["Keflex"],
    cls: "First-generation cephalosporin antibiotic",
    mech: "Beta-lactam inhibiting bacterial cell-wall synthesis.",
    reg: { US: US_OK + " (as cephalexin)" },
    eq: "Long-established oral cephalosporin with label support for skin, urinary and respiratory infections.",
    ben: "Common oral antibiotic for skin/soft-tissue infections and some UTIs.",
    ind: [
      I("Skin and soft-tissue infections"),
      I("Urinary tract infections"),
      I("Respiratory tract infections and otitis media (susceptible organisms)"),
      I("Bone infections (selected labels)", "moderate"),
    ],
    ae: [
      A("Diarrhoea, nausea, dyspepsia", "common"),
      A("Rash", "common", "moderate"),
      A("C. difficile-associated diarrhoea", "serious"),
      A("Anaphylaxis (rare)", "serious"),
    ],
    warn: [
      W("contraindication", "Cephalosporin allergy; caution with severe penicillin allergy", "major", "Cross-reactivity risk."),
      W("precaution", "Renal impairment", "moderate", "Dose adjustment."),
    ],
    special: {
      pregnancy: "Generally considered compatible.",
      lactation: "Generally compatible.",
      renal: "Dose adjustment.",
    },
    mon: ["Clinical response", "Diarrhoea"],
    src: ["dailymed", "bnf", "nice", "who_aWaRe"],
  }),
  med({
    name: "Phenoxymethylpenicillin (Penicillin V)",
    brands: [],
    cls: "Narrow-spectrum penicillin antibiotic",
    mech: "Beta-lactam inhibiting bacterial cell-wall synthesis; acid-stable oral penicillin.",
    reg: { US: US_OK + " (penicillin V potassium)" },
    eq: "First-line, WHO Access-group antibiotic for streptococcal pharyngitis in many guidelines.",
    ben: "Narrow-spectrum oral penicillin favoured in antibiotic stewardship for strep throat and some skin infections.",
    ind: [
      I("Streptococcal pharyngitis / tonsillitis"),
      I("Mild–moderate skin infections such as erysipelas (streptococcal)", "moderate"),
      I("Prevention of rheumatic fever recurrence"),
      I("Pneumococcal prophylaxis in asplenia / sickle cell disease", "moderate"),
    ],
    ae: [
      A("Nausea, diarrhoea", "common"),
      A("Rash, urticaria", "common", "moderate"),
      A("Anaphylaxis", "serious"),
      A("C. difficile-associated diarrhoea", "serious", "moderate"),
    ],
    warn: [
      W("contraindication", "Penicillin allergy", "major", "Risk of anaphylaxis."),
      W("precaution", "Severe renal impairment", "moderate", "Dose interval adjustment may be needed."),
    ],
    special: {
      pregnancy: "Considered compatible.",
      lactation: "Compatible.",
      renal: "Adjust in severe impairment.",
    },
    mon: ["Clinical response", "Allergic reactions"],
    src: ["bnf", "nice", "who_aWaRe", "dailymed"],
  }),
  med({
    name: "Flucloxacillin",
    brands: ["Floxapen"],
    cls: "Penicillinase-resistant penicillin antibiotic",
    mech: "Beta-lactam stable to staphylococcal penicillinase; inhibits cell-wall synthesis.",
    routes: ["oral", "IV", "IM"],
    reg: { US: US_NO + " (floxacillin)" },
    eq: "Standard UK/European agent for staphylococcal skin and soft-tissue infections; guideline-supported.",
    ben: "Anti-staphylococcal penicillin; cholestatic liver injury (sometimes delayed) is a notable risk.",
    ind: [
      I("Staphylococcal skin and soft-tissue infections (cellulitis, impetigo, infected eczema)"),
      I("Osteomyelitis and septic arthritis (susceptible staphylococci)", "moderate"),
      I("Staphylococcal endocarditis (IV, combination regimens)", "moderate"),
    ],
    ae: [
      A("Nausea, diarrhoea", "common"),
      A("Cholestatic hepatitis/jaundice — may appear up to 2 months after stopping", "serious", "high", "More likely in older patients and courses >14 days"),
      A("Hypersensitivity including anaphylaxis", "serious"),
      A("High anion gap metabolic acidosis when combined with paracetamol in at-risk patients", "serious", "moderate"),
      A("C. difficile-associated diarrhoea", "serious", "moderate"),
    ],
    warn: [
      W("contraindication", "Penicillin allergy; previous flucloxacillin-associated jaundice/hepatic dysfunction", "major", "See SmPC."),
      W("warning", "Concomitant paracetamol in severe illness, malnutrition, renal impairment", "major", "MHRA-highlighted risk of high anion gap metabolic acidosis (pyroglutamic acidosis)."),
      W("precaution", "Hepatic impairment; elderly; prolonged courses", "moderate", "Higher hepatotoxicity risk."),
    ],
    special: {
      pregnancy: "Penicillins generally considered compatible.",
      lactation: "Compatible.",
      hepatic: "Caution — hepatotoxicity.",
      renal: "Dose reduction in severe impairment.",
      geriatric: "Higher risk of cholestatic jaundice.",
    },
    mon: ["Liver function in prolonged courses or risk factors", "Acid–base status if combined with paracetamol in at-risk patients"],
    src: ["bnf", "mhra", "nice", "ema"],
  }),
  med({
    name: "Valaciclovir (Valacyclovir)",
    brands: ["Valtrex"],
    cls: "Nucleoside analogue antiviral (aciclovir prodrug)",
    mech: "Converted to aciclovir; aciclovir triphosphate inhibits herpesvirus DNA polymerase.",
    reg: { US: US_OK + " (as valacyclovir)" },
    eq: "RCT evidence for herpes zoster, genital herpes and herpes labialis; better oral bioavailability than aciclovir.",
    ben: "Less frequent dosing than aciclovir for herpes infections; renal and neurological adverse effects in at-risk patients.",
    ind: [
      I("Herpes zoster (shingles)"),
      I("Genital herpes — treatment of episodes and suppression"),
      I("Herpes labialis (cold sores)"),
      I("CMV prophylaxis after organ transplantation (selected labels)", "moderate"),
    ],
    ae: [
      A("Headache, nausea, abdominal pain", "common"),
      A("Acute kidney injury (especially dehydration, elderly, renal impairment)", "serious"),
      A("Neurotoxicity — confusion, hallucinations, agitation (elderly / renal impairment)", "serious"),
      A("Thrombotic microangiopathy (TTP/HUS) at high doses in immunocompromised patients", "serious", "moderate"),
    ],
    warn: [
      W("precaution", "Renal impairment and older adults", "major", "Dose adjustment; ensure hydration."),
      W("warning", "Nephrotoxic co-medication", "moderate", "Additive renal risk."),
    ],
    special: {
      pregnancy: "Aciclovir/valaciclovir data reassuring; used when indicated.",
      lactation: "Aciclovir passes into milk at low levels; generally compatible.",
      renal: "Dose reduction required.",
      geriatric: "Higher neurotoxicity/renal risk.",
    },
    mon: ["Renal function in at-risk patients", "Mental status in elderly/renal impairment"],
    src: ["dailymed", "ema", "bnf", "cdc_stis"],
  }),
  med({
    name: "Clotrimazole",
    brands: ["Canesten", "Lotrimin", "Gyne-Lotrimin"],
    cls: "Imidazole antifungal (topical / vaginal)",
    mech: "Inhibits fungal ergosterol synthesis (lanosterol 14-alpha-demethylase).",
    routes: ["topical", "vaginal", "oromucosal"],
    reg: { US: US_OK + " (several OTC products)" },
    eq: "Established, guideline-supported topical treatment for vulvovaginal candidiasis and dermatophyte infections.",
    ben: "Widely available topical antifungal; minimal systemic absorption.",
    ind: [
      I("Vulvovaginal candidiasis (vaginal thrush)"),
      I("Tinea pedis, cruris and corporis (athlete's foot, jock itch, ringworm)"),
      I("Cutaneous candidiasis"),
      I("Oropharyngeal candidiasis (troches, US)", "moderate"),
    ],
    ae: [
      A("Local burning, stinging or irritation", "common"),
      A("Itching, redness", "common"),
      A("Allergic contact dermatitis", "moderate", "moderate"),
      A("Lower abdominal cramps (vaginal products)", "moderate", "low"),
      A("Systemic hypersensitivity (rare)", "serious", "low"),
    ],
    warn: [
      W("precaution", "Vaginal products and latex", "moderate", "May damage latex condoms and diaphragms."),
      W("warning", "First episode, recurrent (≥4/year) symptoms, pregnancy, abnormal bleeding or fever", "moderate", "Seek clinical assessment before self-treatment."),
    ],
    special: {
      pregnancy: "Topical/vaginal azoles are generally preferred in pregnancy (applicator use with care) — clinician advice.",
      lactation: "Compatible.",
      pediatric: "Product-specific age limits for OTC use.",
    },
    mon: ["Symptom resolution; seek care if not improved"],
    src: ["dailymed", "cdc_stis", "nhs_medicines", "bnf"],
  }),
  med({
    name: "Mebendazole",
    brands: ["Vermox", "Emverm"],
    cls: "Benzimidazole anthelmintic",
    mech: "Binds parasite beta-tubulin, inhibiting microtubule formation and glucose uptake.",
    reg: { US: US_OK + " (chewable tablets)" },
    eq: "Established, WHO-listed anthelmintic for common intestinal worms.",
    ben: "Short-course treatment for threadworm and other gut worms; minimal absorption.",
    ind: [
      I("Threadworm / pinworm (Enterobius vermicularis)"),
      I("Roundworm, whipworm and hookworm infections"),
      I("Mixed intestinal helminth infections"),
    ],
    ae: [
      A("Abdominal pain, diarrhoea, flatulence", "common"),
      A("Rash, urticaria, angioedema", "moderate", "moderate"),
      A("Neutropenia/agranulocytosis with prolonged high-dose use (rare)", "serious", "moderate"),
      A("Convulsions in infants (rare)", "serious", "low"),
      A("SJS/TEN (rare; reported with concomitant metronidazole)", "serious", "low"),
    ],
    warn: [
      W("precaution", "Pregnancy (especially first trimester) and children under 2 years", "moderate", "Product-specific restrictions."),
      W("warning", "Concomitant metronidazole", "moderate", "SJS/TEN reported — avoid combination."),
    ],
    special: {
      pregnancy: "Avoid in first trimester unless advised.",
      lactation: "Minimal absorption; generally considered compatible.",
      pediatric: "Limited data under 2 years.",
      hepatic: "Caution with prolonged high doses.",
    },
    mon: ["Blood count and liver tests only with prolonged high-dose regimens"],
    src: ["dailymed", "who", "bnf", "nhs_medicines"],
  }),
];
