import { med, I, A, W, US_OK, US_NO } from "./helpers.mjs";

// Bone, gout, endocrine/metabolic, women's health, dermatology, haematology
export const MEDS_B = [
  med({
    name: "Febuxostat",
    brands: ["Adenuric", "Uloric"],
    cls: "Xanthine oxidase inhibitor",
    mech: "Non-purine selective inhibitor of xanthine oxidase, lowering uric acid production.",
    reg: { US: US_OK + " (boxed warning: cardiovascular death)", EU: "Centrally authorised (EMA) — see EPAR" },
    eq: "Effective urate lowering; the CARES trial found higher cardiovascular and all-cause mortality vs allopurinol in patients with CV disease, leading to a US boxed warning (2019).",
    ben: "Urate-lowering alternative when allopurinol is not tolerated or ineffective; CV risk must be weighed.",
    ind: [
      I("Chronic hyperuricaemia in gout (typically when allopurinol is unsuitable)"),
      I("Prevention/treatment of hyperuricaemia in tumour lysis risk (higher-dose EU product)", "moderate"),
    ],
    ae: [
      A("Gout flares after starting (urate mobilisation)", "common"),
      A("Liver function abnormalities", "common"),
      A("Diarrhoea, nausea, rash", "common", "moderate"),
      A("Cardiovascular death (CARES trial; boxed warning in US)", "boxed", "moderate"),
      A("Severe hypersensitivity incl. SJS/TEN/DRESS", "serious", "moderate"),
    ],
    warn: [
      W("boxed", "Established cardiovascular disease", "major", "Higher CV death rate vs allopurinol in CARES — reserve for patients where allopurinol is unsuitable."),
      W("contraindication", "Azathioprine or mercaptopurine therapy", "major", "Xanthine oxidase inhibition can cause severe myelotoxicity."),
      W("precaution", "Flare prophylaxis", "moderate", "Flares are common at initiation; prophylaxis is usually given (clinician decision)."),
    ],
    special: {
      pregnancy: "No adequate data — avoid.",
      lactation: "Not recommended.",
      hepatic: "Caution; monitor LFTs.",
      renal: "Limited data in severe renal impairment.",
    },
    mon: ["Serum urate to target", "Liver function tests", "Cardiovascular symptoms"],
    src: ["dailymed", "ema", "acr_gout", "fda"],
  }),
  med({
    name: "Denosumab",
    brands: ["Prolia", "Xgeva"],
    cls: "RANKL inhibitor (monoclonal antibody)",
    mech: "Binds RANK ligand, inhibiting osteoclast formation and bone resorption.",
    routes: ["subcutaneous"],
    reg: { US: US_OK + " (Prolia boxed warning: severe hypocalcaemia in advanced CKD, 2024)", EU: "Centrally authorised (EMA) — see EPARs (Prolia, Xgeva)" },
    eq: "High-quality RCT evidence (FREEDOM) for fracture reduction in postmenopausal osteoporosis; rebound vertebral fractures after stopping are well documented.",
    ben: "Six-monthly injection reducing vertebral, hip and non-vertebral fractures; must not be stopped without a follow-on plan.",
    ind: [
      I("Postmenopausal osteoporosis at high fracture risk (Prolia)"),
      I("Osteoporosis in men at high fracture risk; bone loss with hormone ablation for prostate/breast cancer (Prolia)"),
      I("Glucocorticoid-induced osteoporosis (Prolia)", "moderate"),
      I("Prevention of skeletal-related events in bone metastases (Xgeva)"),
    ],
    ae: [
      A("Musculoskeletal / back pain, limb pain", "common"),
      A("Hypocalcaemia (severe in advanced CKD)", "boxed"),
      A("Osteonecrosis of the jaw", "serious"),
      A("Atypical femoral fractures", "serious", "moderate"),
      A("Multiple vertebral fractures after stopping or delaying doses", "serious"),
      A("Skin infections / cellulitis", "moderate", "moderate"),
    ],
    warn: [
      W("boxed", "Advanced chronic kidney disease (especially dialysis)", "major", "Severe, sometimes fatal hypocalcaemia — assess for CKD-mineral bone disorder first (FDA 2024)."),
      W("warning", "Discontinuation", "major", "Rebound bone loss and multiple vertebral fractures — transition to another antiresorptive is usually planned."),
      W("precaution", "Dental health", "moderate", "Dental check before starting; good oral hygiene (ONJ risk)."),
    ],
    special: {
      pregnancy: "Contraindicated (Prolia) — contraception per label.",
      lactation: "Not recommended.",
      renal: "No dose adjustment but much higher hypocalcaemia risk in advanced CKD.",
      geriatric: "Commonly used; check calcium/vitamin D.",
    },
    mon: ["Calcium and vitamin D before and during treatment", "Renal function", "Dental status", "On-time dosing every 6 months"],
    wd: "Do not stop or delay injections without a clinician plan — rapid bone loss and multiple vertebral fractures can follow discontinuation.",
    src: ["dailymed", "ema", "nice", "fda"],
  }),
  med({
    name: "Zoledronic acid",
    brands: ["Aclasta", "Reclast", "Zometa"],
    cls: "Bisphosphonate (intravenous)",
    mech: "Binds bone mineral and inhibits osteoclast-mediated bone resorption (farnesyl pyrophosphate synthase).",
    routes: ["IV"],
    reg: { US: US_OK, EU: "Centrally authorised (EMA) — see EPARs (Aclasta, Zometa)" },
    eq: "RCT evidence (HORIZON) for fracture reduction with yearly infusion; established in malignancy-related bone disease.",
    ben: "Once-yearly infusion for osteoporosis; also used in cancer-related bone disease and hypercalcaemia.",
    ind: [
      I("Osteoporosis in postmenopausal women and men (yearly infusion)"),
      I("Paget's disease of bone"),
      I("Hypercalcaemia of malignancy"),
      I("Prevention of skeletal-related events in bone metastases / multiple myeloma"),
    ],
    ae: [
      A("Acute-phase reaction (fever, myalgia, flu-like symptoms) after infusion", "common"),
      A("Renal toxicity", "serious"),
      A("Hypocalcaemia", "serious", "moderate"),
      A("Osteonecrosis of the jaw", "serious"),
      A("Atypical femoral fractures", "serious", "moderate"),
    ],
    warn: [
      W("contraindication", "Severe renal impairment (osteoporosis product: CrCl <35 mL/min) and hypocalcaemia", "major", "See product information."),
      W("precaution", "Hydration and infusion time", "major", "Renal toxicity risk rises with dehydration and fast infusion."),
      W("precaution", "Dental health", "moderate", "Dental check before treatment (ONJ)."),
    ],
    special: {
      pregnancy: "Contraindicated.",
      lactation: "Contraindicated.",
      renal: "Creatinine check before each dose; contraindicated in severe impairment (osteoporosis indication).",
    },
    mon: ["Serum creatinine before each infusion", "Calcium and vitamin D status", "Dental status"],
    src: ["dailymed", "ema", "nice", "bnf"],
  }),
  med({
    name: "Risedronate",
    brands: ["Actonel", "Atelvia"],
    cls: "Bisphosphonate (oral)",
    mech: "Inhibits osteoclast-mediated bone resorption.",
    reg: { US: US_OK },
    eq: "RCT evidence for vertebral and non-vertebral fracture reduction in postmenopausal osteoporosis.",
    ben: "Oral weekly/monthly bisphosphonate alternative to alendronate.",
    ind: [
      I("Postmenopausal osteoporosis"),
      I("Osteoporosis in men", "moderate"),
      I("Glucocorticoid-induced osteoporosis"),
      I("Paget's disease of bone"),
    ],
    ae: [
      A("Dyspepsia, abdominal pain, oesophagitis", "common"),
      A("Musculoskeletal pain", "common", "moderate"),
      A("Osteonecrosis of the jaw (rare)", "serious"),
      A("Atypical femoral fractures (rare)", "serious", "moderate"),
      A("Hypocalcaemia", "moderate", "moderate"),
    ],
    warn: [
      W("contraindication", "Hypocalcaemia; inability to stand/sit upright for 30 minutes; oesophageal abnormalities delaying emptying", "major", "See label."),
      W("precaution", "Severe renal impairment (CrCl <30 mL/min)", "moderate", "Not recommended."),
    ],
    special: {
      pregnancy: "Not for use.",
      lactation: "Not for use.",
      renal: "Not recommended with CrCl <30 mL/min.",
    },
    mon: ["Calcium/vitamin D status", "Periodic review of treatment duration", "Dental status"],
    src: ["dailymed", "nice", "bnf", "ema"],
  }),
  med({
    name: "Insulin degludec",
    brands: ["Tresiba"],
    cls: "Ultra-long-acting basal insulin analogue",
    mech: "Forms soluble multi-hexamers after injection, giving slow, flat insulin absorption (>24 h action).",
    routes: ["subcutaneous"],
    reg: { US: US_OK, EU: "Centrally authorised (EMA) — see EPAR" },
    eq: "RCTs (incl. DEVOTE) show non-inferior CV safety vs glargine and lower rates of severe/nocturnal hypoglycaemia.",
    ben: "Basal insulin with flexible daily timing and lower nocturnal hypoglycaemia risk vs older basal insulins.",
    ind: [
      I("Type 1 diabetes (with mealtime insulin)"),
      I("Type 2 diabetes requiring insulin"),
      I("Fixed combination with liraglutide (IDegLira) for type 2 diabetes", "moderate"),
    ],
    ae: [
      A("Hypoglycaemia", "serious"),
      A("Weight gain", "common"),
      A("Injection-site reactions, lipodystrophy / localized cutaneous amyloidosis", "common", "moderate"),
      A("Hypokalaemia", "moderate", "moderate"),
      A("Peripheral oedema (especially with pioglitazone)", "moderate", "moderate"),
    ],
    warn: [
      W("warning", "Hypoglycaemia", "major", "Risk with dose changes, missed meals, exercise, alcohol, renal/hepatic impairment."),
      W("warning", "Never share pens", "major", "Blood-borne infection risk even with new needles."),
      W("precaution", "Combination with thiazolidinediones", "moderate", "Fluid retention / heart failure."),
    ],
    special: {
      pregnancy: "Insulin is the preferred glucose-lowering therapy in pregnancy; specialist management.",
      lactation: "Compatible.",
      renal: "Hypoglycaemia risk higher.",
      pediatric: "Licensed from 1 year (product information).",
    },
    mon: ["Blood glucose / CGM", "HbA1c", "Hypoglycaemia episodes", "Injection sites"],
    src: ["dailymed", "ema", "ada_diabetes", "easd_ada"],
  }),
  med({
    name: "Insulin lispro",
    brands: ["Humalog", "Admelog", "Lyumjev"],
    cls: "Rapid-acting insulin analogue",
    mech: "Modified human insulin with faster absorption for mealtime glucose control.",
    routes: ["subcutaneous", "IV"],
    reg: { US: US_OK, EU: "Centrally authorised (EMA) — see EPAR" },
    eq: "Established mealtime insulin; used in multiple-daily-injection and pump regimens.",
    ben: "Mealtime/correction insulin for type 1 and insulin-requiring type 2 diabetes.",
    ind: [
      I("Type 1 diabetes (mealtime and correction insulin)"),
      I("Type 2 diabetes requiring prandial insulin"),
      I("Continuous subcutaneous insulin infusion (pump therapy)"),
    ],
    ae: [
      A("Hypoglycaemia", "serious"),
      A("Weight gain", "common"),
      A("Injection-site reactions / lipodystrophy", "common", "moderate"),
      A("Hypokalaemia", "moderate", "moderate"),
    ],
    warn: [
      W("warning", "Hypoglycaemia", "major", "Timing relative to meals matters; risk with mismatched carbohydrate intake."),
      W("warning", "Never share pens; check insulin type/concentration", "major", "Medication-error risk with different concentrations (e.g., U-200)."),
    ],
    special: {
      pregnancy: "Used in pregnancy under specialist care.",
      lactation: "Compatible.",
      renal: "Requirements may decrease.",
    },
    mon: ["Blood glucose / CGM", "HbA1c", "Hypoglycaemia"],
    src: ["dailymed", "ema", "ada_diabetes", "nice"],
  }),
  med({
    name: "Glimepiride",
    brands: ["Amaryl"],
    cls: "Sulfonylurea",
    mech: "Closes pancreatic beta-cell K-ATP channels, stimulating insulin release.",
    reg: { US: US_OK },
    eq: "Lowers HbA1c effectively; no proven CV benefit, and hypoglycaemia/weight gain are class limitations.",
    ben: "Low-cost oral glucose-lowering option; hypoglycaemia risk especially in older adults.",
    ind: [
      I("Type 2 diabetes (adjunct to diet and exercise)"),
      I("Type 2 diabetes in combination with metformin or insulin"),
    ],
    ae: [
      A("Hypoglycaemia (can be prolonged)", "serious"),
      A("Weight gain", "common"),
      A("Nausea, GI upset", "common", "moderate"),
      A("Rash / photosensitivity", "moderate", "moderate"),
      A("Haemolytic anaemia in G6PD deficiency", "serious", "low"),
    ],
    warn: [
      W("warning", "Older adults, renal impairment, irregular meals", "major", "Higher risk of severe/prolonged hypoglycaemia."),
      W("contraindication", "Type 1 diabetes, diabetic ketoacidosis, severe hepatic/renal impairment", "major", "See label."),
      W("precaution", "CYP2C9 inhibitors (e.g., fluconazole)", "moderate", "May increase hypoglycaemia risk."),
    ],
    special: {
      pregnancy: "Insulin preferred.",
      lactation: "Not recommended.",
      renal: "Caution; avoid in severe impairment.",
      geriatric: "Beers: sulfonylureas carry high hypoglycaemia risk.",
    },
    mon: ["Blood glucose", "HbA1c", "Renal function"],
    src: ["dailymed", "ada_diabetes", "easd_ada", "bnf"],
  }),
  med({
    name: "Linagliptin",
    brands: ["Trajenta", "Tradjenta"],
    cls: "DPP-4 inhibitor",
    mech: "Inhibits DPP-4, raising active incretin (GLP-1/GIP) levels and glucose-dependent insulin secretion.",
    reg: { US: US_OK, EU: "Centrally authorised (EMA) — see EPAR" },
    eq: "Moderate HbA1c lowering; CARMELINA showed CV and renal safety (neutral) in high-risk patients.",
    ben: "Weight-neutral oral agent with low hypoglycaemia risk; no renal dose adjustment required.",
    ind: [
      I("Type 2 diabetes monotherapy (when metformin unsuitable)"),
      I("Type 2 diabetes in combination with other glucose-lowering agents"),
    ],
    ae: [
      A("Nasopharyngitis", "common", "moderate"),
      A("Hypoglycaemia when combined with sulfonylurea or insulin", "moderate"),
      A("Acute pancreatitis", "serious", "moderate"),
      A("Bullous pemphigoid", "serious", "moderate"),
      A("Severe joint pain (DPP-4 class warning)", "moderate", "low"),
    ],
    warn: [
      W("warning", "History of pancreatitis", "major", "Stop if pancreatitis suspected."),
      W("warning", "Bullous pemphigoid", "moderate", "Stop if blisters/erosions appear; dermatology review."),
    ],
    special: {
      pregnancy: "Avoid; insulin preferred.",
      lactation: "Not recommended.",
      renal: "No dose adjustment required.",
      hepatic: "No dose adjustment required.",
    },
    mon: ["HbA1c", "Abdominal pain symptoms", "Skin blistering"],
    src: ["dailymed", "ema", "ada_diabetes", "easd_ada"],
  }),
  med({
    name: "Pioglitazone",
    brands: ["Actos"],
    cls: "Thiazolidinedione (PPAR-gamma agonist)",
    mech: "Activates PPAR-gamma, improving insulin sensitivity in muscle, fat and liver.",
    reg: { US: US_OK + " (boxed warning: congestive heart failure)" },
    eq: "Lowers HbA1c; PROactive suggested some CV benefit on secondary endpoints; HF, fracture and possible bladder cancer risks limit use.",
    ben: "Insulin sensitiser with low hypoglycaemia risk; fluid retention and heart failure risk require selection.",
    ind: [
      I("Type 2 diabetes (monotherapy or combination)"),
      I("Type 2 diabetes in combination with insulin (selected labels)", "moderate"),
      I("Metabolic dysfunction-associated steatohepatitis (MASH/NASH)", "moderate", false, "Off-label; guideline-mentioned in selected patients"),
    ],
    ae: [
      A("Weight gain, oedema", "common"),
      A("Heart failure (new or worsening)", "boxed"),
      A("Bone fractures (especially in women)", "serious", "moderate"),
      A("Bladder cancer (small possible increased risk)", "serious", "moderate"),
      A("Macular oedema", "moderate", "low"),
    ],
    warn: [
      W("boxed", "Heart failure", "major", "Contraindicated in NYHA III/IV (US) / any heart failure history (EU)."),
      W("contraindication", "Active or history of bladder cancer; uninvestigated macroscopic haematuria", "major", "EU SmPC."),
      W("precaution", "Liver disease", "moderate", "Check liver enzymes before starting."),
    ],
    special: {
      pregnancy: "Not recommended.",
      lactation: "Not recommended.",
      hepatic: "Avoid if ALT >2.5× ULN.",
      geriatric: "Fracture and HF risk.",
    },
    mon: ["Weight and oedema", "Heart failure symptoms", "Liver enzymes", "Haematuria"],
    src: ["dailymed", "ema", "ada_diabetes", "easd_ada"],
  }),
  med({
    name: "Evolocumab",
    brands: ["Repatha"],
    cls: "PCSK9 inhibitor (monoclonal antibody)",
    mech: "Binds PCSK9, preventing LDL-receptor degradation and markedly lowering LDL cholesterol.",
    routes: ["subcutaneous"],
    reg: { US: US_OK, EU: "Centrally authorised (EMA) — see EPAR" },
    eq: "FOURIER RCT: reduced major CV events in patients with established atherosclerotic CVD on statins.",
    ben: "Lowers LDL-C by roughly 60% on top of statins; used in very-high-risk patients not at goal.",
    ind: [
      I("Established atherosclerotic cardiovascular disease — to reduce CV events"),
      I("Primary hypercholesterolaemia including heterozygous familial hypercholesterolaemia"),
      I("Homozygous familial hypercholesterolaemia"),
    ],
    ae: [
      A("Nasopharyngitis, upper respiratory tract infection", "common"),
      A("Injection-site reactions", "common"),
      A("Back pain, arthralgia", "common", "moderate"),
      A("Hypersensitivity reactions (rash, urticaria, angioedema)", "serious", "moderate"),
    ],
    warn: [
      W("warning", "Hypersensitivity", "moderate", "Stop if serious allergic reactions occur."),
      W("precaution", "Pregnancy", "moderate", "Limited data; monoclonal antibodies cross the placenta in later pregnancy."),
    ],
    special: {
      pregnancy: "Limited data — avoid unless clearly needed.",
      lactation: "Unknown.",
      renal: "No adjustment in mild–moderate impairment.",
    },
    mon: ["LDL cholesterol response", "Injection technique/adherence"],
    src: ["dailymed", "ema", "aha_cholesterol", "nice"],
  }),
  med({
    name: "Estradiol",
    brands: ["Estrofem", "Estrace", "Vagifem", "Oestrogel"],
    cls: "Estrogen (menopausal hormone therapy)",
    mech: "Activates estrogen receptors, replacing declining endogenous estrogen.",
    routes: ["oral", "transdermal", "vaginal"],
    reg: { US: US_OK + " (class boxed warnings)" },
    eq: "Strong evidence for vasomotor symptom relief and GSM; WHI and observational data inform VTE, stroke and breast cancer risks, which vary by regimen, route and age.",
    ben: "Most effective treatment for menopausal hot flushes; vaginal estrogen for local symptoms has minimal systemic exposure.",
    ind: [
      I("Moderate–severe menopausal vasomotor symptoms"),
      I("Genitourinary syndrome of menopause / vulvovaginal atrophy (vaginal products)"),
      I("Prevention of postmenopausal osteoporosis (when other options unsuitable)"),
      I("Hypoestrogenism due to hypogonadism or primary ovarian insufficiency"),
    ],
    ae: [
      A("Breast tenderness, nausea, headache, breakthrough bleeding", "common"),
      A("Venous thromboembolism (higher with oral than transdermal routes in observational data)", "serious"),
      A("Stroke", "serious", "moderate"),
      A("Endometrial hyperplasia/cancer if unopposed in women with a uterus", "boxed"),
      A("Breast cancer (small increase with longer combined therapy)", "serious", "moderate"),
    ],
    warn: [
      W("boxed", "Endometrial cancer, cardiovascular disorders, breast cancer, probable dementia (US class warning)", "major", "Women with a uterus need a progestogen."),
      W("contraindication", "Current/past breast cancer, active or past VTE, undiagnosed vaginal bleeding, active liver disease, recent arterial thrombosis", "major", "See product information."),
      W("precaution", "Migraine with aura, high VTE risk", "moderate", "Transdermal route often preferred — clinician decision."),
    ],
    special: {
      pregnancy: "Not indicated.",
      lactation: "Not indicated.",
      hepatic: "Contraindicated in active liver disease.",
      geriatric: "Starting systemic therapy >60 years or >10 years after menopause carries higher risks.",
    },
    mon: ["Annual review of indication and risks", "Abnormal vaginal bleeding", "Blood pressure", "Breast screening per programme"],
    src: ["dailymed", "nice", "ema", "acog"],
  }),
  med({
    name: "Progesterone (micronised)",
    brands: ["Utrogestan", "Prometrium", "Crinone"],
    cls: "Progestogen (natural progesterone)",
    mech: "Activates progesterone receptors; transforms estrogen-primed endometrium to secretory phase.",
    routes: ["oral", "vaginal"],
    reg: { US: US_OK },
    eq: "Established endometrial protection in estrogen HRT; luteal support in assisted reproduction is standard practice; preterm-birth prevention evidence is mixed by population.",
    ben: "Body-identical progestogen used with estrogen HRT and in fertility treatment.",
    ind: [
      I("Endometrial protection during estrogen therapy in women with a uterus"),
      I("Luteal phase support in assisted reproduction (vaginal products)"),
      I("Secondary amenorrhoea (US label)", "moderate"),
      I("Prevention of preterm birth in selected women with short cervix (vaginal)", "moderate", false, "Guideline-dependent; evidence mixed"),
    ],
    ae: [
      A("Drowsiness, dizziness (oral; often taken at bedtime)", "common"),
      A("Breast tenderness, bloating, headache", "common"),
      A("Irregular vaginal bleeding", "common", "moderate"),
      A("Venous thromboembolism (with combined HRT)", "serious", "moderate"),
      A("Hypersensitivity — some oral capsules contain peanut (arachis) oil", "serious", "moderate"),
    ],
    warn: [
      W("contraindication", "Peanut allergy (products containing arachis oil, e.g., Prometrium)", "major", "Check excipients."),
      W("contraindication", "Undiagnosed vaginal bleeding, breast cancer, active VTE, severe liver disease", "major", "See product information."),
      W("precaution", "Driving", "moderate", "Oral form can cause drowsiness/dizziness."),
    ],
    special: {
      pregnancy: "Used therapeutically in fertility/obstetric settings under specialist care.",
      lactation: "Small amounts in milk.",
      hepatic: "Contraindicated in severe liver disease.",
    },
    mon: ["Bleeding pattern on HRT", "Annual HRT review"],
    src: ["dailymed", "nice", "acog", "ema"],
  }),
  med({
    name: "Desogestrel (progestogen-only pill)",
    brands: ["Cerazette", "Hana", "Lovima"],
    cls: "Progestogen-only contraceptive pill",
    mech: "Inhibits ovulation (desogestrel 75 µg) and thickens cervical mucus.",
    reg: {
      US: "Desogestrel-only pill not FDA-approved (desogestrel is approved only in combined pills)",
      UK: "Licensed; available from pharmacies without prescription (e.g., Hana, Lovima) since 2021",
    },
    eq: "Typical-use effectiveness similar to combined pills; strong evidence base for safety when estrogen is contraindicated.",
    ben: "Estrogen-free contraception suitable for many people who cannot take estrogen (e.g., migraine with aura, breastfeeding, smokers over 35).",
    ind: [
      I("Contraception"),
      I("Contraception when estrogen is contraindicated or not tolerated"),
    ],
    ae: [
      A("Irregular bleeding, spotting or amenorrhoea", "common"),
      A("Acne, headache, breast tenderness", "common"),
      A("Mood changes / depressed mood", "moderate", "moderate"),
      A("Functional ovarian cysts", "moderate", "moderate"),
      A("Ectopic pregnancy if method fails", "serious", "moderate"),
    ],
    warn: [
      W("warning", "Enzyme-inducing drugs (carbamazepine, rifampicin, St John's wort etc.)", "major", "Reduced contraceptive efficacy — additional/alternative method needed."),
      W("contraindication", "Current breast cancer; severe liver disease/liver tumours; undiagnosed vaginal bleeding; active VTE", "major", "See product information."),
    ],
    special: {
      pregnancy: "Not indicated.",
      lactation: "Suitable during breastfeeding.",
      hepatic: "Contraindicated in severe liver disease.",
    },
    mon: ["Blood pressure periodically", "Bleeding pattern", "Interacting medicines"],
    src: ["mhra", "ema", "bnf", "who"],
  }),
  med({
    name: "Ulipristal acetate",
    brands: ["ellaOne", "ella", "Esmya"],
    cls: "Selective progesterone receptor modulator (emergency contraception)",
    mech: "Delays or inhibits ovulation, including shortly before the LH peak.",
    reg: {
      US: US_OK + " (ella, prescription)",
      EU: "Centrally authorised (ellaOne, non-prescription); 5 mg Esmya restricted after liver-injury review (EMA)",
    },
    eq: "RCT evidence that ulipristal is at least as effective as levonorgestrel EC and effective up to 120 hours.",
    ben: "Emergency contraception effective up to 5 days after unprotected sex; a copper IUD remains the most effective EC.",
    ind: [
      I("Emergency contraception within 120 hours (5 days) of unprotected intercourse or contraceptive failure"),
      I("Uterine fibroid symptoms (5 mg, Esmya)", "moderate", true, "Severely restricted in the EU after rare serious liver injury"),
    ],
    ae: [
      A("Headache, nausea, abdominal pain", "common"),
      A("Change in timing of next period, dysmenorrhoea", "common"),
      A("Dizziness, fatigue", "common", "moderate"),
      A("Serious liver injury (reported with long-term 5 mg Esmya, not single-dose EC)", "serious", "moderate"),
    ],
    warn: [
      W("warning", "Hormonal contraception started within 5 days after ulipristal", "major", "May reduce ulipristal's effect — follow product timing advice; use barrier method."),
      W("warning", "Enzyme-inducing medicines (within last 4 weeks)", "major", "Reduced efficacy — copper IUD or alternative EC advised."),
      W("precaution", "Breastfeeding", "moderate", "Product information advises not breastfeeding for one week after a dose."),
    ],
    special: {
      pregnancy: "Not for use in known pregnancy (does not terminate an established pregnancy).",
      lactation: "Avoid breastfeeding for 1 week after the dose (express and discard).",
      hepatic: "Not recommended in severe hepatic impairment.",
    },
    mon: ["Pregnancy test if period is >7 days late or unusual"],
    src: ["ema", "ema_ulipristal_5mg", "dailymed", "who"],
  }),
  med({
    name: "Medroxyprogesterone acetate",
    brands: ["Depo-Provera", "Sayana Press", "Provera"],
    cls: "Progestogen (injectable contraceptive / oral progestogen)",
    mech: "Suppresses gonadotropins and ovulation; transforms endometrium.",
    routes: ["IM", "subcutaneous", "oral"],
    reg: { US: US_OK + " (boxed warning: bone mineral density loss, injectable)" },
    eq: "Highly effective long-acting contraception; BMD loss is well documented and largely reversible after stopping.",
    ben: "Three-monthly contraceptive injection; oral tablets used for abnormal uterine bleeding and endometrial protection.",
    ind: [
      I("Contraception (3-monthly injection)"),
      I("Endometriosis-associated pain (subcutaneous product, US)", "moderate"),
      I("Abnormal uterine bleeding / secondary amenorrhoea (oral)", "moderate"),
      I("Endometrial protection during estrogen therapy (oral)", "moderate"),
    ],
    ae: [
      A("Irregular bleeding or amenorrhoea", "common"),
      A("Weight gain", "common"),
      A("Loss of bone mineral density with long-term injectable use", "boxed"),
      A("Delayed return of fertility after stopping injections", "common", "high", "Can take up to about a year or longer"),
      A("Meningioma with long-term high-dose use (EMA 2024 review)", "serious", "moderate"),
      A("Mood changes", "moderate", "moderate"),
    ],
    warn: [
      W("boxed", "Bone mineral density loss (injectable)", "major", "Consider risks/benefits beyond 2 years of use, especially adolescents."),
      W("contraindication", "Known/suspected breast cancer, undiagnosed vaginal bleeding, active thromboembolic disease, severe liver disease", "major", "See label."),
      W("precaution", "History of meningioma", "moderate", "Stop if meningioma diagnosed (EMA 2024)."),
    ],
    special: {
      pregnancy: "Not indicated.",
      lactation: "Injectable contraception compatible with breastfeeding.",
      hepatic: "Contraindicated in severe liver disease.",
      pediatric: "Adolescents: BMD considerations.",
    },
    mon: ["Review of continued use (BMD risk) periodically", "Blood pressure", "Injection timing"],
    src: ["dailymed", "ema", "who", "bnf"],
  }),
  med({
    name: "Isotretinoin",
    brands: ["Roaccutane", "Absorica", "Accutane (historical US brand)"],
    cls: "Oral retinoid",
    mech: "Reduces sebaceous gland size and sebum production, normalises follicular keratinisation, and reduces C. acnes.",
    reg: {
      US: US_OK + " — restricted distribution under the iPLEDGE REMS",
      EU: "Authorised nationally with a mandatory Pregnancy Prevention Programme (EMA retinoid review, 2018)",
    },
    eq: "Highly effective for severe acne with durable remission; teratogenicity is absolute and neuropsychiatric effects are monitored.",
    ben: "The most effective acne treatment for severe/scarring acne; strict pregnancy prevention required.",
    ind: [
      I("Severe recalcitrant nodular acne"),
      I("Severe acne (e.g., nodular/conglobate or at risk of scarring) resistant to adequate systemic antibacterial plus topical therapy"),
      I("Other dermatoses (e.g., rosacea, hidradenitis)", "low", false, "Off-label; limited evidence"),
    ],
    ae: [
      A("Dry lips, skin, eyes and nosebleeds", "common"),
      A("Severe birth defects if taken during pregnancy", "boxed"),
      A("Depression, mood changes, suicidal ideation (causality debated)", "serious", "moderate"),
      A("Raised triglycerides and liver enzymes", "moderate"),
      A("Idiopathic intracranial hypertension (especially with tetracyclines)", "serious"),
      A("Sexual dysfunction (reported; UK review 2023)", "moderate", "low"),
    ],
    warn: [
      W("boxed", "Pregnancy", "major", "Contraindicated; Pregnancy Prevention Programme (EU) / iPLEDGE (US) with pregnancy testing and effective contraception."),
      W("contraindication", "Concomitant tetracyclines", "major", "Risk of intracranial hypertension."),
      W("warning", "Psychiatric symptoms", "major", "Monitor mood; seek help for depression or suicidal thoughts."),
      W("precaution", "Blood donation", "moderate", "Do not donate blood during treatment and for 1 month after."),
    ],
    special: {
      pregnancy: "Contraindicated — highly teratogenic.",
      lactation: "Contraindicated.",
      hepatic: "Contraindicated in hepatic impairment.",
      pediatric: "Not before puberty; additional UK safeguards for under-18s.",
    },
    mon: ["Pregnancy tests before, monthly during and after treatment (per programme)", "Liver enzymes and lipids at baseline and during", "Mood and mental health"],
    src: ["ema_retinoids", "ipledge", "mhra", "dailymed"],
  }),
  med({
    name: "Tranexamic acid",
    brands: ["Cyklokapron", "Lysteda"],
    cls: "Antifibrinolytic",
    mech: "Blocks lysine-binding sites on plasminogen, inhibiting fibrinolysis.",
    routes: ["oral", "IV", "topical"],
    reg: { US: US_OK },
    eq: "Large RCTs: CRASH-2 (trauma) and WOMAN (postpartum haemorrhage) showed reduced bleeding deaths when given early; RCT support for heavy menstrual bleeding and surgical blood loss.",
    ben: "Reduces bleeding in heavy periods, trauma, surgery and postpartum haemorrhage without being an anticoagulant reversal agent.",
    ind: [
      I("Heavy menstrual bleeding (oral)"),
      I("Trauma-related haemorrhage (early IV administration)"),
      I("Reduction of surgical blood loss (e.g., cardiac, orthopaedic)"),
      I("Postpartum haemorrhage (WHO-recommended)"),
      I("Dental procedures in haemophilia (adjunct)", "moderate"),
    ],
    ae: [
      A("Nausea, diarrhoea, headache", "common"),
      A("Thromboembolic events (rare; risk debated)", "serious", "moderate"),
      A("Seizures (high-dose IV, especially cardiac surgery)", "serious"),
      A("Visual disturbances — stop and seek eye examination", "serious", "moderate"),
      A("Hypersensitivity (rare)", "serious", "low"),
    ],
    warn: [
      W("contraindication", "Active thromboembolic disease; history of seizures (IV)", "major", "See label."),
      W("warning", "Wrong-route (intrathecal) administration errors", "major", "Serious harm/death reported — injection is for IV use only (FDA/EMA warnings)."),
      W("precaution", "Combined hormonal contraceptives; renal impairment", "moderate", "Possible additive thrombosis risk; dose adjustment in renal impairment."),
    ],
    special: {
      pregnancy: "Used for postpartum haemorrhage; otherwise clinician decision.",
      lactation: "Small amounts in milk; generally compatible.",
      renal: "Dose reduction required.",
    },
    mon: ["Signs of thrombosis", "Renal function for repeated IV dosing", "Vision with prolonged use"],
    src: ["dailymed", "who", "nice", "ema"],
  }),
  med({
    name: "Folic acid",
    brands: [],
    cls: "Vitamin (B9)",
    mech: "Synthetic folate converted to tetrahydrofolate, a cofactor for DNA synthesis and methylation.",
    reg: { US: US_OK + " (prescription strengths; lower doses as supplements)" },
    eq: "RCTs established that periconceptional folic acid substantially reduces neural tube defects; standard therapy for folate deficiency.",
    ben: "Prevents neural tube defects when taken before conception and in early pregnancy; treats folate-deficiency anaemia.",
    ind: [
      I("Prevention of neural tube defects (before conception and in early pregnancy)"),
      I("Folate-deficiency megaloblastic anaemia"),
      I("Reduction of toxicity with low-dose methotrexate (guideline-supported)", "moderate"),
    ],
    ae: [
      A("Nausea, bloating, flatulence (uncommon)", "common", "moderate"),
      A("Hypersensitivity reactions (rare)", "serious", "low"),
      A("Masking of vitamin B12 deficiency — neurological damage can progress", "serious", "high"),
      A("Possible reduction of phenytoin/phenobarbital levels with seizure risk", "moderate", "moderate"),
    ],
    warn: [
      W("warning", "Undiagnosed megaloblastic anaemia", "major", "Exclude/treat B12 deficiency before folic acid alone."),
      W("precaution", "Antiepileptic drugs", "moderate", "Monitor levels when starting high-dose folic acid."),
    ],
    special: {
      pregnancy: "Recommended before conception and in early pregnancy; higher doses for some risk groups (clinician advice).",
      lactation: "Compatible.",
      renal: "No adjustment.",
    },
    mon: ["Blood count / B12 status when treating anaemia"],
    src: ["who", "nice", "bnf", "uspstf"],
  }),
  med({
    name: "Ferric carboxymaltose",
    brands: ["Ferinject", "Injectafer"],
    cls: "Intravenous iron",
    mech: "Iron–carbohydrate complex delivering iron to the reticuloendothelial system for haemoglobin synthesis.",
    routes: ["IV"],
    reg: { US: US_OK + " (Injectafer)" },
    eq: "RCTs support rapid iron repletion; in iron-deficient heart failure, IV iron improves symptoms and is guideline-recommended.",
    ben: "Replaces iron in one or two infusions when oral iron fails or is unsuitable; hypophosphataemia is a recognised risk.",
    ind: [
      I("Iron deficiency when oral iron is ineffective, not tolerated, or rapid repletion is needed"),
      I("Iron deficiency in heart failure (guideline-supported; US-labelled)"),
      I("Iron-deficiency anaemia in non-dialysis chronic kidney disease (US)", "moderate"),
    ],
    ae: [
      A("Hypophosphataemia (can be severe; osteomalacia/fractures with repeated dosing)", "serious"),
      A("Hypersensitivity / anaphylactic reactions (rare)", "serious"),
      A("Headache, nausea, flushing, dizziness", "common"),
      A("Injection-site reactions; brown skin staining after extravasation", "moderate"),
      A("Transient hypertension", "moderate", "moderate"),
    ],
    warn: [
      W("warning", "Hypersensitivity", "major", "Give only where staff and resuscitation facilities are available; observe ≥30 minutes."),
      W("warning", "Hypophosphataemia", "major", "Monitor phosphate with repeated doses or risk factors."),
      W("precaution", "First trimester of pregnancy; active infection", "moderate", "Avoid in first trimester; caution with bacteraemia."),
    ],
    special: {
      pregnancy: "Avoid in first trimester; may be used later when benefit outweighs risk.",
      lactation: "Minimal iron transfer; generally compatible.",
      renal: "Used in CKD.",
    },
    mon: ["Haemoglobin, ferritin and transferrin saturation after 4+ weeks", "Phosphate if repeated dosing or symptoms", "Observation for hypersensitivity during/after infusion"],
    src: ["dailymed", "ema", "esc_hf", "nice"],
  }),
  med({
    name: "Testosterone",
    brands: ["Testogel", "AndroGel", "Nebido"],
    cls: "Androgen",
    mech: "Replaces testosterone, activating androgen receptors.",
    routes: ["transdermal", "IM"],
    reg: { US: US_OK + " (Schedule III; boxed warning for secondary exposure with gels)" },
    eq: "Benefits in confirmed hypogonadism (sexual function, bone density, anaemia); TRAVERSE (2023) found CV non-inferiority in older men with hypogonadism.",
    ben: "Restores testosterone in confirmed hypogonadism; not indicated for age-related decline without diagnosis.",
    ind: [
      I("Male hypogonadism confirmed by symptoms and repeatedly low testosterone"),
      I("Delayed puberty in males (specialist)", "moderate"),
      I("Gender-affirming hormone therapy", "moderate", false, "Off-label in many jurisdictions; specialist care"),
    ],
    ae: [
      A("Acne, oily skin", "common"),
      A("Erythrocytosis (raised haematocrit)", "serious"),
      A("Application-site reactions (gels)", "common"),
      A("Suppression of sperm production / infertility", "moderate"),
      A("Virilisation of women/children from skin contact with gels", "boxed"),
      A("Fluid retention, worsening sleep apnoea", "moderate", "moderate"),
    ],
    warn: [
      W("boxed", "Secondary exposure (gels)", "major", "Children/women exposed to skin contact can virilise — cover site, wash hands."),
      W("contraindication", "Prostate or male breast cancer", "major", "See label."),
      W("warning", "Abuse and dependence at supraphysiological doses", "moderate", "Serious CV and psychiatric effects."),
    ],
    special: {
      pregnancy: "Contraindicated (virilisation of female fetus).",
      lactation: "Contraindicated.",
      geriatric: "Prostate and haematocrit monitoring.",
    },
    mon: ["Testosterone levels", "Haematocrit", "PSA / prostate assessment per guidelines", "Blood pressure"],
    src: ["dailymed", "fda", "nice", "ema"],
  }),
];
