import { med, I, A, W, US_OK, US_NO } from "./helpers.mjs";

// Respiratory / allergy / ENT / emergency
export const MEDS_C = [
  med({
    name: "Mometasone (nasal)",
    brands: ["Nasonex"],
    cls: "Intranasal corticosteroid",
    mech: "Topical glucocorticoid reducing nasal mucosal inflammation.",
    routes: ["intranasal"],
    reg: { US: US_OK + " (also OTC)" },
    eq: "RCT and guideline support (ARIA) — intranasal steroids are the most effective single treatment for persistent allergic rhinitis.",
    ben: "Daily nasal spray for allergic rhinitis and nasal polyps with low systemic exposure.",
    ind: [
      I("Seasonal and perennial allergic rhinitis"),
      I("Nasal polyps"),
      I("Prophylaxis of seasonal allergic rhinitis symptoms", "moderate"),
    ],
    ae: [
      A("Nosebleeds, nasal irritation, dryness", "common"),
      A("Headache, pharyngitis", "common"),
      A("Nasal septal perforation (rare)", "serious", "moderate"),
      A("Cataract/glaucoma (rare, class)", "serious", "low"),
      A("Reduced growth velocity in children (class effect with prolonged use)", "moderate", "moderate"),
    ],
    warn: [
      W("precaution", "Recent nasal surgery, trauma or ulcers", "moderate", "Delays healing."),
      W("precaution", "Children on long-term therapy", "moderate", "Monitor growth."),
    ],
    special: {
      pregnancy: "Intranasal steroids generally considered acceptable when needed.",
      lactation: "Compatible.",
      pediatric: "Age limits per product.",
    },
    mon: ["Growth in children with prolonged use", "Nasal examination if bleeding/crusting persists"],
    src: ["dailymed", "nice", "bnf", "ema"],
  }),
  med({
    name: "Bilastine",
    brands: ["Bilaxten", "Ilaxten"],
    cls: "Second-generation H1 antihistamine",
    mech: "Selective peripheral H1-receptor inverse agonist with minimal CNS penetration.",
    reg: { US: US_NO },
    eq: "RCTs show efficacy comparable to other second-generation antihistamines for rhinitis and urticaria, with low sedation.",
    ben: "Non-sedating antihistamine for hay fever and hives.",
    ind: [
      I("Allergic rhinoconjunctivitis (seasonal and perennial)"),
      I("Urticaria"),
    ],
    ae: [
      A("Headache", "common"),
      A("Somnolence", "common", "moderate"),
      A("Dizziness, fatigue", "moderate", "moderate"),
      A("Abdominal pain, nausea", "moderate", "low"),
      A("Hypersensitivity reactions (rare)", "serious", "low"),
    ],
    warn: [
      W("precaution", "Food and fruit juice", "moderate", "Reduce absorption — product information gives timing advice."),
      W("precaution", "P-glycoprotein inhibitors in moderate–severe renal impairment", "moderate", "Avoid combination (raised exposure)."),
    ],
    special: {
      pregnancy: "Limited data — prefer antihistamines with more pregnancy data.",
      lactation: "Unknown; avoid if alternatives exist.",
      renal: "No dose adjustment alone; avoid with P-gp inhibitors in renal impairment.",
      pediatric: "Lower-strength products for children from 6 years.",
    },
    mon: ["Symptom response"],
    src: ["ema", "bnf", "swissmedic_pi", "nice"],
  }),
  med({
    name: "Xylometazoline",
    brands: ["Otrivin", "Otrivine"],
    cls: "Topical nasal decongestant (alpha-adrenergic agonist)",
    mech: "Alpha-adrenergic vasoconstriction of nasal mucosal blood vessels.",
    routes: ["intranasal"],
    reg: { US: "Check current US OTC status (not widely marketed in the US)" },
    eq: "Effective short-term relief of nasal congestion; rebound congestion with prolonged use is well documented.",
    ben: "Fast relief of a blocked nose for a few days; not for prolonged use.",
    ind: [
      I("Nasal congestion due to common cold (short-term)"),
      I("Nasal congestion in allergic rhinitis (short-term adjunct)", "moderate"),
      I("Congestion in acute sinusitis (adjunct)", "moderate"),
    ],
    ae: [
      A("Nasal burning, stinging, dryness, sneezing", "common"),
      A("Rebound congestion (rhinitis medicamentosa) with prolonged use", "moderate"),
      A("Headache", "common", "moderate"),
      A("Palpitations, raised blood pressure (rare; more with overuse)", "serious", "low"),
    ],
    warn: [
      W("warning", "Use beyond about 7 days", "moderate", "Rebound congestion and dependence on the spray."),
      W("contraindication", "After transsphenoidal surgery; narrow-angle glaucoma; MAOI use; young children (product-specific age limits)", "major", "See product information."),
    ],
    special: {
      pregnancy: "Avoid or use only briefly on clinician/pharmacist advice.",
      lactation: "Limited data — short use only if needed.",
      pediatric: "Paediatric strengths with age limits; risk of systemic toxicity in infants.",
    },
    mon: ["Duration of use"],
    src: ["bnf", "nhs_medicines", "swissmedic_pi", "ema"],
  }),
  med({
    name: "Acetylcysteine",
    brands: ["Fluimucil", "Acetadote", "Parvolex"],
    cls: "Antidote (paracetamol poisoning) / mucolytic",
    mech: "Replenishes glutathione to detoxify NAPQI (paracetamol metabolite); breaks disulfide bonds in mucus.",
    routes: ["IV", "oral", "inhalation"],
    reg: { US: US_OK + " (IV antidote and inhalation solution)" },
    eq: "Highly effective antidote for paracetamol overdose when given early; mucolytic benefit in chronic bronchitis/COPD is modest.",
    ben: "Life-saving antidote in paracetamol overdose; also sold in Europe as a mucolytic.",
    ind: [
      I("Paracetamol (acetaminophen) overdose — hospital antidote"),
      I("Mucolytic in respiratory conditions with thick mucus", "moderate"),
      I("Reduction of COPD exacerbations (high-dose, selected patients)", "low", false, "Evidence mixed; guideline-dependent"),
    ],
    ae: [
      A("Anaphylactoid reactions with IV antidote (rash, flushing, bronchospasm, hypotension)", "serious"),
      A("Nausea, vomiting (oral)", "common"),
      A("Bronchospasm (inhaled)", "serious", "moderate"),
      A("Headache, tinnitus (rare)", "moderate", "low"),
    ],
    warn: [
      W("warning", "Asthma / bronchospasm history", "moderate", "Monitor; reactions are usually manageable — the hospital team decides on continuing the antidote."),
      W("warning", "Possible paracetamol overdose", "major", "Seek emergency care immediately (CH: Tox Info Suisse 145; emergencies 144) — do not self-treat."),
      W("precaution", "Peptic ulcer (mucolytic use)", "moderate", "Caution."),
    ],
    special: {
      pregnancy: "Antidote should not be withheld in pregnancy.",
      lactation: "Generally compatible.",
      pediatric: "Weight-based antidote dosing in hospital.",
    },
    mon: ["Paracetamol levels, liver function, INR during antidote treatment (hospital)"],
    src: ["toxinfo", "dailymed", "bnf", "ema"],
  }),
  med({
    name: "Epinephrine (Adrenaline)",
    brands: ["EpiPen", "Jext", "Anapen"],
    cls: "Sympathomimetic (alpha/beta-adrenergic agonist)",
    mech: "Alpha-1 vasoconstriction reverses hypotension/oedema; beta-2 bronchodilation; beta-1 increases cardiac output; stabilises mast cells.",
    routes: ["IM", "IV", "inhalation"],
    reg: { US: US_OK },
    eq: "First-line treatment for anaphylaxis in every major guideline; delayed epinephrine is associated with fatal outcomes.",
    ben: "Life-saving first-line treatment for anaphylaxis; auto-injectors allow immediate self/bystander use.",
    ind: [
      I("Emergency treatment of anaphylaxis (intramuscular / auto-injector)"),
      I("Cardiac arrest (IV/IO, professional resuscitation)"),
      I("Severe croup (nebulised, hospital use)", "moderate"),
    ],
    ae: [
      A("Palpitations, tachycardia, tremor, anxiety, pallor", "common"),
      A("Hypertension, arrhythmias", "serious"),
      A("Myocardial ischaemia (especially with heart disease or overdose/IV errors)", "serious", "moderate"),
      A("Tissue ischaemia after accidental injection into fingers/hands", "serious", "moderate"),
      A("Headache, nausea, sweating", "common", "moderate"),
    ],
    warn: [
      W("warning", "Anaphylaxis", "major", "No absolute contraindication in anaphylaxis — always call emergency services (CH 144 / EU 112) after use."),
      W("precaution", "Beta-blockers (especially non-selective)", "moderate", "May reduce response and cause hypertension/bradycardia."),
      W("precaution", "Cardiovascular disease, hyperthyroidism", "moderate", "Higher risk of adverse effects — benefit usually outweighs risk in anaphylaxis."),
    ],
    special: {
      pregnancy: "Should not be withheld in anaphylaxis.",
      lactation: "Compatible.",
      pediatric: "Paediatric auto-injector strengths by weight.",
      geriatric: "Higher cardiovascular risk, but still first-line in anaphylaxis.",
    },
    mon: ["BP, heart rate, ECG in professional settings", "Auto-injector expiry dates"],
    src: ["dailymed", "nice", "ema", "bnf"],
  }),
  med({
    name: "Beclometasone/formoterol",
    brands: ["Foster", "Fostair"],
    cls: "ICS/LABA combination inhaler",
    mech: "Inhaled corticosteroid (anti-inflammatory) plus fast-onset long-acting beta-2 agonist (bronchodilator).",
    routes: ["inhalation"],
    reg: { US: US_NO },
    eq: "RCT evidence for asthma control (including maintenance-and-reliever regimens) and COPD exacerbation reduction.",
    ben: "Extrafine-particle combination inhaler used in asthma (incl. MART) and COPD.",
    ind: [
      I("Asthma maintenance (and maintenance-and-reliever therapy in selected products)"),
      I("Severe COPD with history of exacerbations"),
    ],
    ae: [
      A("Oral candidiasis (thrush), hoarseness", "common"),
      A("Headache, tremor, palpitations", "common"),
      A("Pneumonia in COPD (ICS class)", "serious"),
      A("Paradoxical bronchospasm", "serious", "moderate"),
      A("Hypokalaemia, hyperglycaemia (beta-agonist)", "moderate", "moderate"),
    ],
    warn: [
      W("warning", "Not for acute relief unless prescribed as MART", "major", "Follow the written asthma action plan."),
      W("warning", "COPD pneumonia risk", "moderate", "Report fever, increased sputum, breathlessness."),
      W("precaution", "Cardiac arrhythmias, thyrotoxicosis", "moderate", "Beta-agonist effects."),
    ],
    special: {
      pregnancy: "Asthma control is a priority in pregnancy — continue under clinician guidance.",
      lactation: "Generally compatible.",
      pediatric: "Product-specific age limits.",
    },
    mon: ["Asthma/COPD symptom control and exacerbations", "Inhaler technique", "Mouth rinsing after use"],
    src: ["gina_asthma", "gold_copd", "ema", "bnf"],
  }),
  med({
    name: "Fluticasone furoate/vilanterol",
    brands: ["Relvar Ellipta", "Breo Ellipta"],
    cls: "ICS/LABA combination inhaler (once daily)",
    mech: "Once-daily inhaled corticosteroid plus long-acting beta-2 agonist.",
    routes: ["inhalation"],
    reg: { US: US_OK, EU: "Centrally authorised (EMA) — see EPAR" },
    eq: "RCTs support asthma control and COPD exacerbation reduction; the Salford Lung Study provided real-world effectiveness data.",
    ben: "Once-daily combination inhaler for asthma and COPD maintenance.",
    ind: [
      I("Asthma maintenance (adolescents/adults)"),
      I("COPD maintenance"),
    ],
    ae: [
      A("Oral candidiasis, dysphonia", "common"),
      A("Headache, nasopharyngitis", "common"),
      A("Pneumonia in COPD", "serious"),
      A("Bone fractures / reduced BMD with long-term ICS (class)", "moderate", "moderate"),
      A("Paradoxical bronchospasm", "serious", "low"),
    ],
    warn: [
      W("warning", "Not a reliever inhaler", "major", "Use separate rescue medication for acute symptoms."),
      W("precaution", "Strong CYP3A4 inhibitors (e.g., ritonavir)", "moderate", "Increase systemic corticosteroid exposure."),
      W("warning", "COPD pneumonia risk", "moderate", "Report signs of infection."),
    ],
    special: {
      pregnancy: "Continue asthma treatment under clinician guidance.",
      lactation: "Limited data.",
      hepatic: "Lower dose in moderate–severe impairment.",
    },
    mon: ["Symptom control and exacerbations", "Inhaler technique"],
    src: ["gina_asthma", "gold_copd", "dailymed", "ema"],
  }),
];
