import { med, I, A, W, US_OK, US_NO } from "./helpers.mjs";

// CNS / neurology / psychiatry
export const MEDS_D = [
  med({
    name: "Amitriptyline",
    brands: ["Saroten", "Elavil (historical US brand)"],
    cls: "Tricyclic antidepressant (TCA)",
    mech: "Inhibits serotonin and noradrenaline reuptake; also antihistaminic, anticholinergic and alpha-blocking effects.",
    reg: { US: US_OK },
    eq: "Effective antidepressant but less tolerated than newer agents; low-dose use for neuropathic pain and headache prophylaxis is guideline-supported.",
    ben: "Old, inexpensive drug now mostly used at low dose for neuropathic pain and headache prevention; dangerous in overdose.",
    ind: [
      I("Major depressive disorder (adults)"),
      I("Neuropathic pain (low dose)", "moderate", true, "Licensed in some countries (e.g., UK); off-label in US"),
      I("Migraine and tension-type headache prophylaxis", "moderate", true, "Licensed in some countries; off-label in US"),
    ],
    ae: [
      A("Dry mouth, constipation, blurred vision, urinary retention", "common"),
      A("Sedation, weight gain", "common"),
      A("Orthostatic hypotension, falls", "serious", "moderate"),
      A("QT prolongation / arrhythmias; high toxicity in overdose", "serious"),
      A("Suicidal thoughts in young people", "boxed"),
      A("Serotonin syndrome with serotonergic drugs", "serious", "moderate"),
    ],
    warn: [
      W("boxed", "Children, adolescents and young adults", "major", "Antidepressant suicidality warning."),
      W("contraindication", "Recent myocardial infarction, heart block/arrhythmias, MAOI use, severe liver disease", "major", "See label."),
      W("warning", "Overdose", "major", "Small quantities can be fatal — prescribers limit supply for people at risk of self-harm."),
      W("precaution", "Older adults", "moderate", "Anticholinergic burden (Beers criteria)."),
    ],
    special: {
      pregnancy: "Risk–benefit decision; neonatal adaptation symptoms possible.",
      lactation: "Low levels in milk; generally considered acceptable at low doses — clinician decision.",
      hepatic: "Caution; avoid in severe impairment.",
      geriatric: "Avoid where possible (falls, confusion, retention).",
    },
    mon: ["Mood/suicidality early in treatment", "ECG in cardiac risk or higher doses", "Anticholinergic effects"],
    wd: "Abrupt stopping can cause discontinuation symptoms (nausea, headache, malaise, sleep disturbance) — taper with clinician advice.",
    src: ["dailymed", "nice", "bnf", "fda_ssri_suicidality"],
  }),
  med({
    name: "Vortioxetine",
    brands: ["Brintellix", "Trintellix"],
    cls: "Multimodal serotonergic antidepressant",
    mech: "Serotonin reuptake inhibition plus modulation of several 5-HT receptors (5-HT3/5-HT7/5-HT1D antagonism, 5-HT1A agonism, 5-HT1B partial agonism).",
    reg: { US: US_OK, EU: "Centrally authorised (EMA) — see EPAR" },
    eq: "RCTs show efficacy in MDD versus placebo; superiority over other antidepressants not established.",
    ben: "Antidepressant option; nausea is common early.",
    ind: [
      I("Major depressive disorder"),
      I("Prevention of relapse in major depressive disorder (maintenance)"),
    ],
    ae: [
      A("Nausea (very common, usually early)", "common"),
      A("Constipation, vomiting, dizziness, pruritus", "common"),
      A("Sexual dysfunction (dose-related)", "common", "moderate"),
      A("Suicidal thoughts in young people", "boxed"),
      A("Serotonin syndrome; bleeding risk; hyponatraemia", "serious", "moderate"),
    ],
    warn: [
      W("boxed", "Children, adolescents and young adults", "major", "Antidepressant suicidality warning."),
      W("contraindication", "MAOIs", "major", "Serotonin syndrome risk."),
      W("precaution", "Anticoagulants/antiplatelets/NSAIDs", "moderate", "Increased bleeding risk."),
    ],
    special: {
      pregnancy: "Limited data compared with SSRIs.",
      lactation: "Limited data.",
      geriatric: "Hyponatraemia risk.",
    },
    mon: ["Mood and suicidality early", "Sodium in at-risk patients"],
    wd: "Discontinuation symptoms appear less frequent than with some SSRIs/SNRIs, but stopping should still be discussed with the prescriber.",
    src: ["dailymed", "ema", "nice", "fda_ssri_suicidality"],
  }),
  med({
    name: "Haloperidol",
    brands: ["Haldol"],
    cls: "First-generation (typical) antipsychotic",
    mech: "Potent dopamine D2 receptor antagonist.",
    routes: ["oral", "IM", "IV"],
    reg: { US: US_OK + " (IV use is off-label in the US)" },
    eq: "Established antipsychotic; evidence for delirium is mixed and non-drug measures remain first-line.",
    ben: "Used for psychosis and short-term severe agitation/delirium; EPS and QT risks are significant.",
    ind: [
      I("Schizophrenia and other psychotic disorders"),
      I("Severe acute agitation (short-term)", "moderate"),
      I("Delirium when non-drug measures fail", "low", true, "Labelled in some countries; evidence mixed"),
      I("Tourette's syndrome / tics", "moderate"),
    ],
    ae: [
      A("Extrapyramidal effects — dystonia, parkinsonism, akathisia", "common"),
      A("Tardive dyskinesia", "serious"),
      A("QT prolongation / torsades de pointes (especially IV, high doses)", "serious"),
      A("Neuroleptic malignant syndrome", "serious", "moderate"),
      A("Sedation, hyperprolactinaemia", "common", "moderate"),
    ],
    warn: [
      W("boxed", "Older adults with dementia-related psychosis", "major", "Increased mortality."),
      W("contraindication", "Parkinson's disease, dementia with Lewy bodies, known QT prolongation, coma", "major", "See label."),
      W("warning", "QT-prolonging drugs and electrolyte disturbance", "major", "ECG monitoring recommended."),
    ],
    special: {
      pregnancy: "Neonatal EPS/withdrawal possible with third-trimester use.",
      lactation: "Passes into milk — clinician decision.",
      geriatric: "Lower doses; high EPS/fall risk; dementia boxed warning.",
    },
    mon: ["ECG (QTc) at baseline/higher doses", "Abnormal movements", "Electrolytes"],
    src: ["dailymed", "nice", "ema", "bnf"],
  }),
  med({
    name: "Donepezil",
    brands: ["Aricept"],
    cls: "Acetylcholinesterase inhibitor",
    mech: "Reversibly inhibits acetylcholinesterase, increasing synaptic acetylcholine.",
    reg: { US: US_OK },
    eq: "RCTs show modest benefits on cognition and global function in Alzheimer's disease; does not halt progression.",
    ben: "Symptomatic treatment for Alzheimer's dementia; benefits are modest and variable.",
    ind: [
      I("Mild to moderate Alzheimer's dementia"),
      I("Severe Alzheimer's dementia (US label)", "moderate"),
      I("Dementia with Lewy bodies / Parkinson's disease dementia", "moderate", false, "Guideline-supported (e.g., NICE); off-label in many countries"),
    ],
    ae: [
      A("Nausea, diarrhoea, loss of appetite", "common"),
      A("Insomnia, vivid dreams, muscle cramps", "common"),
      A("Bradycardia, heart block, syncope", "serious"),
      A("GI bleeding (especially with NSAIDs/ulcer history)", "serious", "moderate"),
      A("Weight loss", "moderate", "moderate"),
    ],
    warn: [
      W("warning", "Sick sinus syndrome / conduction disorders; beta-blocker co-therapy", "major", "Bradycardia and syncope risk."),
      W("precaution", "Peptic ulcer history, asthma/COPD, seizures, urinary outflow obstruction", "moderate", "Cholinergic effects."),
    ],
    special: {
      hepatic: "Caution.",
      geriatric: "Falls from syncope; weight monitoring.",
    },
    mon: ["Pulse / syncope", "Weight", "Cognitive and functional response"],
    wd: "Stopping can lead to loss of the symptomatic benefit; discuss with the prescriber.",
    src: ["dailymed", "nice", "ema", "aan"],
  }),
  med({
    name: "Memantine",
    brands: ["Ebixa", "Axura", "Namenda"],
    cls: "NMDA receptor antagonist",
    mech: "Uncompetitive NMDA receptor antagonist reducing glutamate excitotoxicity.",
    reg: { US: US_OK, EU: "Centrally authorised (EMA) — see EPARs" },
    eq: "Modest benefit in moderate–severe Alzheimer's disease in RCTs; little benefit in mild disease.",
    ben: "Symptomatic option for moderate–severe Alzheimer's, alone or with a cholinesterase inhibitor.",
    ind: [
      I("Moderate to severe Alzheimer's dementia"),
      I("Add-on to a cholinesterase inhibitor in moderate–severe Alzheimer's", "moderate"),
      I("Dementia with Lewy bodies", "low", false, "Off-label; limited evidence"),
    ],
    ae: [
      A("Dizziness, headache", "common"),
      A("Constipation, somnolence", "common"),
      A("Hypertension", "moderate", "moderate"),
      A("Confusion, hallucinations (uncommon)", "moderate", "moderate"),
      A("Seizures (rare)", "serious", "low"),
    ],
    warn: [
      W("precaution", "Severe renal impairment", "moderate", "Dose adjustment."),
      W("precaution", "Epilepsy; conditions raising urinary pH", "moderate", "Reduced elimination with alkaline urine."),
    ],
    special: {
      renal: "Dose reduction in moderate–severe impairment.",
      geriatric: "Monitor dizziness/falls.",
    },
    mon: ["Cognitive/functional response", "Renal function", "Blood pressure"],
    src: ["dailymed", "ema", "nice", "aan"],
  }),
  med({
    name: "Levodopa/carbidopa",
    brands: ["Sinemet", "Rytary", "Duodopa"],
    cls: "Dopamine precursor + peripheral decarboxylase inhibitor",
    mech: "Levodopa is converted to dopamine in the brain; carbidopa prevents peripheral conversion.",
    routes: ["oral", "enteral"],
    reg: { US: US_OK },
    eq: "Most effective symptomatic therapy for Parkinson's disease; motor fluctuations/dyskinesia develop over years.",
    ben: "Cornerstone Parkinson's treatment improving slowness, stiffness and tremor.",
    ind: [
      I("Parkinson's disease"),
      I("Parkinsonism (post-encephalitic, selected secondary forms)", "moderate"),
      I("Advanced Parkinson's with motor fluctuations (intestinal gel)", "moderate"),
    ],
    ae: [
      A("Nausea, loss of appetite", "common"),
      A("Orthostatic hypotension, dizziness", "common"),
      A("Dyskinesias and motor fluctuations (long-term)", "common"),
      A("Hallucinations, confusion, psychosis", "serious"),
      A("Impulse-control disorders; sudden sleep onset", "serious", "moderate"),
    ],
    warn: [
      W("warning", "Abrupt withdrawal or dose reduction", "major", "Can cause a neuroleptic malignant-like syndrome (fever, rigidity, confusion)."),
      W("contraindication", "Non-selective MAOIs; narrow-angle glaucoma", "major", "See label."),
      W("precaution", "Driving", "moderate", "Sudden sleep episodes reported."),
    ],
    special: {
      pregnancy: "Limited data — specialist decision.",
      lactation: "May suppress lactation.",
      geriatric: "Higher risk of confusion/hallucinations.",
    },
    mon: ["Motor response and fluctuations", "Orthostatic BP", "Impulse control and sleepiness", "Mental status"],
    wd: "Do not stop suddenly — risk of severe rigidity, fever and confusion (parkinsonism-hyperpyrexia). Changes should be supervised.",
    src: ["dailymed", "nice", "aan", "ema"],
  }),
  med({
    name: "Levodopa/benserazide",
    brands: ["Madopar"],
    cls: "Dopamine precursor + peripheral decarboxylase inhibitor",
    mech: "Levodopa replaces brain dopamine; benserazide blocks peripheral decarboxylation.",
    reg: { US: US_NO, CH: "Marketed in Switzerland (Madopar) — verify on swissmedicinfo.ch" },
    eq: "Equivalent role to levodopa/carbidopa; widely used in Europe.",
    ben: "Cornerstone symptomatic Parkinson's therapy in many European countries.",
    ind: [
      I("Parkinson's disease"),
      I("Restless legs syndrome (selected labels, e.g., some EU countries)", "moderate"),
    ],
    ae: [
      A("Nausea, loss of appetite", "common"),
      A("Orthostatic hypotension", "common"),
      A("Dyskinesias and motor fluctuations", "common"),
      A("Hallucinations, psychosis", "serious"),
      A("Impulse-control disorders; sudden sleep onset; augmentation in RLS", "serious", "moderate"),
    ],
    warn: [
      W("warning", "Abrupt withdrawal", "major", "Neuroleptic malignant-like syndrome."),
      W("contraindication", "Non-selective MAOIs; narrow-angle glaucoma; patients under 25 years (per SmPC)", "major", "See product information."),
    ],
    special: {
      pregnancy: "Specialist decision; restricted in product information.",
      lactation: "Not recommended.",
      geriatric: "Confusion/hallucination risk.",
    },
    mon: ["Motor response", "Orthostatic BP", "Impulse control", "Sleepiness"],
    wd: "Do not stop suddenly — supervised changes only.",
    src: ["swissmedic_pi", "compendium_ch", "nice", "ema"],
  }),
  med({
    name: "Pramipexole",
    brands: ["Sifrol", "Mirapex", "Mirapexin"],
    cls: "Non-ergot dopamine agonist",
    mech: "Stimulates dopamine D2/D3 receptors.",
    reg: { US: US_OK, EU: "Centrally authorised (EMA) — see EPAR" },
    eq: "RCTs support use in Parkinson's and restless legs syndrome; impulse-control disorders are a major safety issue.",
    ben: "Parkinson's and RLS therapy; impulse-control problems require proactive counselling.",
    ind: [
      I("Parkinson's disease (alone or with levodopa)"),
      I("Moderate to severe restless legs syndrome"),
    ],
    ae: [
      A("Nausea, dizziness, somnolence", "common"),
      A("Sudden sleep onset", "serious"),
      A("Impulse-control disorders (gambling, shopping, hypersexuality, binge eating)", "serious"),
      A("Hallucinations, confusion", "serious", "moderate"),
      A("Peripheral oedema; orthostatic hypotension", "moderate"),
      A("Augmentation of RLS symptoms", "moderate", "moderate"),
    ],
    warn: [
      W("warning", "Impulse-control disorders", "major", "Patients and families should report new compulsive behaviours."),
      W("warning", "Driving/operating machinery", "major", "Sudden sleep episodes."),
      W("precaution", "Renal impairment", "moderate", "Dose adjustment."),
    ],
    special: {
      pregnancy: "Limited data.",
      lactation: "Inhibits prolactin — not recommended.",
      renal: "Dose reduction required.",
      geriatric: "Hallucination risk.",
    },
    mon: ["Impulse-control behaviours", "Daytime sleepiness", "Orthostatic BP"],
    wd: "Abrupt stopping can cause dopamine-agonist withdrawal syndrome (anxiety, depression, apathy, pain) or NMS-like symptoms — taper under supervision.",
    src: ["dailymed", "ema", "nice", "aan"],
  }),
  med({
    name: "Baclofen",
    brands: ["Lioresal", "Lyvispah"],
    cls: "GABA-B agonist muscle relaxant",
    mech: "Activates GABA-B receptors in the spinal cord, reducing excitatory transmission and spasticity.",
    routes: ["oral", "intrathecal"],
    reg: { US: US_OK + " (intrathecal: boxed warning on abrupt discontinuation)" },
    eq: "Established for spasticity of spinal origin; evidence for alcohol use disorder is mixed.",
    ben: "Reduces spasticity in MS and spinal cord injury; withdrawal can be dangerous.",
    ind: [
      I("Spasticity due to multiple sclerosis"),
      I("Spasticity due to spinal cord injury/disease"),
      I("Severe spasticity via intrathecal pump"),
      I("Alcohol use disorder", "low", false, "Authorised in France; off-label elsewhere; evidence mixed"),
    ],
    ae: [
      A("Drowsiness, weakness, dizziness", "common"),
      A("Nausea, confusion", "common", "moderate"),
      A("Encephalopathy/toxicity in renal impairment", "serious"),
      A("Respiratory depression in overdose or with CNS depressants", "serious", "moderate"),
      A("Seizure threshold lowering", "moderate", "moderate"),
    ],
    warn: [
      W("boxed", "Abrupt discontinuation of intrathecal baclofen", "major", "High fever, altered mental status, rebound spasticity, rhabdomyolysis, death."),
      W("warning", "Renal impairment", "major", "Accumulation and neurotoxicity."),
      W("precaution", "Epilepsy, psychiatric disorders", "moderate", "Monitor."),
    ],
    special: {
      pregnancy: "Limited data; neonatal withdrawal reported.",
      lactation: "Small amounts in milk.",
      renal: "Major dose reduction / avoid in severe impairment.",
      geriatric: "Sedation/confusion.",
    },
    mon: ["Sedation and muscle tone", "Renal function", "Intrathecal pump refills (strict schedule)"],
    wd: "Do not stop abruptly — oral withdrawal can cause hallucinations, seizures and rebound spasticity; intrathecal withdrawal can be life-threatening.",
    src: ["dailymed", "nice", "bnf", "ema"],
  }),
  med({
    name: "Tizanidine",
    brands: ["Sirdalud", "Zanaflex"],
    cls: "Central alpha-2 adrenergic agonist muscle relaxant",
    mech: "Presynaptic alpha-2 agonism reducing release of excitatory amino acids in the spinal cord.",
    reg: { US: US_OK },
    eq: "RCTs support use in spasticity; CYP1A2 interactions are clinically critical.",
    ben: "Spasticity treatment; sedation, hypotension and liver effects are key risks.",
    ind: [
      I("Spasticity (e.g., multiple sclerosis, spinal cord injury)"),
      I("Painful muscle spasm (selected labels, e.g., some EU countries)", "moderate"),
    ],
    ae: [
      A("Drowsiness, dry mouth, fatigue, dizziness", "common"),
      A("Hypotension, bradycardia", "serious"),
      A("Hepatotoxicity", "serious"),
      A("Hallucinations", "moderate", "moderate"),
    ],
    warn: [
      W("contraindication", "Ciprofloxacin or fluvoxamine (strong CYP1A2 inhibitors)", "major", "Large rise in tizanidine levels — severe hypotension and sedation."),
      W("contraindication", "Significant hepatic impairment", "major", "See label."),
      W("warning", "Abrupt withdrawal", "moderate", "Rebound hypertension and tachycardia."),
    ],
    special: {
      pregnancy: "Limited data.",
      lactation: "Avoid.",
      renal: "Dose reduction.",
      hepatic: "Avoid in significant impairment.",
      geriatric: "Hypotension/sedation.",
    },
    mon: ["Liver tests per labeling (early in treatment and if symptoms)", "Blood pressure", "Interacting medicines"],
    wd: "Rebound hypertension/tachycardia can occur after abrupt stopping of regular high doses — changes should be clinician-guided.",
    src: ["dailymed", "bnf", "swissmedic_pi", "ema"],
  }),
  med({
    name: "Betahistine",
    brands: ["Betaserc", "Serc"],
    cls: "Histamine analogue (H1 agonist / H3 antagonist)",
    mech: "Thought to improve inner-ear microcirculation and modulate vestibular nuclei via H3 antagonism.",
    reg: { US: US_NO, EU: "Authorised nationally in many EU countries" },
    eq: "Low-certainty evidence; a large RCT (BEMED, 2016) found no reduction in Ménière's attack frequency versus placebo.",
    ben: "Widely prescribed in Europe for Ménière's disease, but evidence of benefit is weak.",
    why: "Long-standing practice and good tolerability, despite weak trial evidence — an example of a commonly used medicine with uncertain benefit.",
    ind: [
      I("Ménière's disease (vertigo, tinnitus, hearing loss)", "low"),
      I("Vestibular vertigo (selected labels)", "low"),
    ],
    ae: [
      A("Nausea, dyspepsia", "common"),
      A("Headache", "common"),
      A("Rash, pruritus, urticaria", "moderate", "moderate"),
      A("Hypersensitivity reactions (rare)", "serious", "low"),
    ],
    warn: [
      W("contraindication", "Phaeochromocytoma", "major", "See product information."),
      W("precaution", "Asthma; peptic ulcer history", "moderate", "Histamine-like effects."),
    ],
    special: {
      pregnancy: "Insufficient data — avoid.",
      lactation: "Unknown.",
      pediatric: "Not recommended.",
    },
    mon: ["Symptom review with the prescriber"],
    src: ["ema", "bnf", "cochrane_overview", "swissmedic_pi"],
  }),
  med({
    name: "Methadone",
    brands: ["Physeptone", "Dolophine"],
    cls: "Synthetic opioid agonist",
    mech: "Full mu-opioid agonist with NMDA antagonism; long and variable half-life.",
    routes: ["oral", "IV", "IM"],
    reg: { US: US_OK + " (OUD treatment only through certified opioid treatment programs)" },
    eq: "High-quality evidence that methadone maintenance reduces illicit opioid use, overdose deaths and HIV/HCV transmission.",
    ben: "Core opioid agonist treatment for opioid use disorder; also used in specialist pain care. QT and accumulation risks need careful management.",
    ind: [
      I("Opioid use disorder — maintenance and detoxification (opioid agonist treatment)"),
      I("Severe pain requiring opioid therapy (specialist use)", "moderate"),
    ],
    ae: [
      A("Constipation, sweating, sedation, nausea", "common"),
      A("Respiratory depression — especially during initiation (accumulation)", "boxed"),
      A("QT prolongation / torsades de pointes", "boxed"),
      A("Hypogonadism, reduced libido", "moderate", "moderate"),
      A("Hypoglycaemia (reported)", "moderate", "low"),
    ],
    warn: [
      W("boxed", "Life-threatening respiratory depression, QT prolongation, accidental ingestion, neonatal opioid withdrawal", "major", "US boxed warnings."),
      W("boxed", "Benzodiazepines and other CNS depressants", "major", "Profound sedation and death."),
      W("warning", "CYP3A4/CYP2B6 interactions", "major", "Inducers (rifampicin, some antiretrovirals) can cause withdrawal; inhibitors raise levels."),
    ],
    special: {
      pregnancy: "Recommended treatment for OUD in pregnancy under specialist care; neonatal withdrawal expected and managed.",
      lactation: "Generally compatible in stable maintenance.",
      hepatic: "Caution.",
      geriatric: "Accumulation and sedation risk.",
    },
    mon: ["ECG/QTc at baseline and with dose increases or risk factors", "Sedation during initiation", "Interacting medicines"],
    wd: "Opioid withdrawal on stopping; any taper should be gradual and supported by the treatment service. Loss of tolerance after stopping increases overdose risk.",
    src: ["dailymed", "who", "nice", "bnf"],
  }),
  med({
    name: "Lisdexamfetamine",
    brands: ["Elvanse", "Vyvanse"],
    cls: "CNS stimulant (amphetamine prodrug)",
    mech: "Prodrug converted to dextroamphetamine, increasing synaptic dopamine and noradrenaline.",
    reg: { US: US_OK + " (Schedule II; boxed warning: abuse, misuse, addiction)" },
    eq: "RCTs support efficacy in ADHD in children and adults, and in binge-eating disorder (US).",
    ben: "Long-acting stimulant; prodrug design may lower immediate abuse potential, but standard stimulant risks apply.",
    ind: [
      I("ADHD in children (≥6 years) and adults"),
      I("Moderate to severe binge-eating disorder (US)", "moderate"),
    ],
    ae: [
      A("Decreased appetite, weight loss, insomnia, dry mouth", "common"),
      A("Increased heart rate and blood pressure", "common"),
      A("Anxiety, irritability", "common", "moderate"),
      A("Psychosis or mania (rare)", "serious", "moderate"),
      A("Abuse, misuse and addiction", "boxed"),
    ],
    warn: [
      W("boxed", "Abuse, misuse and addiction", "major", "Assess risk before and during treatment."),
      W("contraindication", "MAOIs within 14 days; symptomatic cardiovascular disease; hyperthyroidism; glaucoma (label-specific)", "major", "See label."),
      W("precaution", "Growth in children", "moderate", "Monitor height and weight."),
    ],
    special: {
      pregnancy: "Limited data — specialist discussion.",
      lactation: "Amphetamines pass into milk — not recommended.",
      renal: "Dose limit in severe impairment.",
      pediatric: "Growth monitoring.",
    },
    mon: ["Blood pressure and heart rate", "Height and weight (children)", "Sleep and appetite", "Signs of misuse"],
    wd: "Stopping after high-dose or prolonged use can cause fatigue, low mood and increased sleep.",
    src: ["dailymed", "nice", "ema", "fda"],
  }),
];
