// New sources (landing pages / referral pages verified to return HTTP 200 on 2026-10-05)
export const SOURCES_V2 = [
  { key: "compendium_ch", title: "Compendium.ch — Swiss medicines compendium (product information)", organization: "HCI Solutions AG", evidenceType: "regulatory", url: "https://compendium.ch/", jurisdiction: "CH" },
  { key: "ema_metamizole_2024", title: "Metamizole-containing medicinal products — Article 107i referral: measures to minimise serious outcomes of agranulocytosis (2024)", organization: "European Medicines Agency", publicationDate: "2024-11-22", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/metamizole-containing-medicinal-products-0", jurisdiction: "EU" },
  { key: "ema_metamizole_2019", title: "Metamizole-containing medicinal products — Article 31 referral: harmonised dosing, pregnancy and breastfeeding (2019)", organization: "European Medicines Agency", publicationDate: "2019-03-20", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/metamizole-containing-medicinal-products", jurisdiction: "EU" },
  { key: "ema_domperidone", title: "Domperidone-containing medicines — referral (cardiac risk restrictions, 2014)", organization: "European Medicines Agency", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/domperidone-containing-medicines", jurisdiction: "EU" },
  { key: "ema_metoclopramide", title: "Metoclopramide-containing medicines — referral (neurological risks, 2013)", organization: "European Medicines Agency", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/metoclopramide-containing-medicines", jurisdiction: "EU" },
  { key: "ema_retinoids", title: "Retinoid-containing medicinal products — referral (pregnancy prevention, neuropsychiatric warnings, 2018)", organization: "European Medicines Agency", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/retinoid-containing-medicinal-products", jurisdiction: "EU" },
  { key: "ema_hydroxyzine", title: "Hydroxyzine-containing medicines — referral (QT prolongation, 2015)", organization: "European Medicines Agency", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/hydroxyzine", jurisdiction: "EU" },
  { key: "ema_ulipristal_5mg", title: "Ulipristal acetate 5 mg medicinal products — referral (liver injury)", organization: "European Medicines Agency", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/ulipristal-acetate-5mg-medicinal-products", jurisdiction: "EU" },
  { key: "ipledge", title: "iPLEDGE REMS (isotretinoin risk management program)", organization: "iPLEDGE Program / U.S. FDA REMS", evidenceType: "regulatory", url: "https://www.ipledgeprogram.com/", jurisdiction: "US" },
  { key: "toxinfo", title: "Tox Info Suisse — Swiss national poisons information centre (emergency number 145)", organization: "Tox Info Suisse", evidenceType: "guideline", url: "https://www.toxinfo.ch/", jurisdiction: "CH" },
  { key: "nhs_medicines", title: "NHS medicines A to Z", organization: "NHS England", evidenceType: "guideline", url: "https://www.nhs.uk/medicines/", jurisdiction: "UK" },
  { key: "medlineplus", title: "MedlinePlus — Drugs, Herbs and Supplements", organization: "U.S. National Library of Medicine", evidenceType: "guideline", url: "https://medlineplus.gov/druginformation.html", jurisdiction: "US" },
];
