// New sources (landing pages / referral pages verified to return HTTP 200 on 2026-10-05)
export const SOURCES_V2 = [
  { key: "compendium_ch", title: "Compendium.ch — Swiss medicines compendium (product information)", organization: "HCI Solutions AG", evidenceType: "regulatory", url: "https://compendium.ch/", jurisdiction: "CH" },
  { key: "ema_metamizole_2024", title: "Metamizole-containing medicinal products — Article 107i referral: measures to minimise serious outcomes of agranulocytosis (2024)", organization: "European Medicines Agency", publicationDate: "2024-11-22", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/metamizole-containing-medicinal-products-0", jurisdiction: "EU" },
  { key: "ema_metamizole_2019", title: "Metamizole-containing medicinal products — Article 31 referral: harmonised dosing, pregnancy and breastfeeding (2019)", organization: "European Medicines Agency", publicationDate: "2019-03-20", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/metamizole-containing-medicinal-products", jurisdiction: "EU" },
  { key: "ema_domperidone", title: "Domperidone-containing medicines — referral (cardiac risk restrictions, 2014)", organization: "European Medicines Agency", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/domperidone-containing-medicines", jurisdiction: "EU" },
  { key: "ema_metoclopramide", title: "Metoclopramide-containing medicines — referral (neurological risks, 2013)", organization: "European Medicines Agency", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/metoclopramide-containing-medicines", jurisdiction: "EU" },
  { key: "ema_retinoids", title: "Retinoid-containing medicinal products — referral (pregnancy prevention, neuropsychiatric warnings, 2018)", organization: "European Medicines Agency", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/retinoid-containing-medicinal-products", jurisdiction: "EU" },
  { key: "ema_hydroxyzine", title: "Hydroxyzine-containing medicines — referral (QT prolongation, 2015)", organization: "European Medicines Agency", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/hydroxyzine", jurisdiction: "EU" },
  { key: "ema_ulipristal_5mg", title: "Ulipristal acetate 5 mg medicinal products — referral (liver injury)", organization: "European Medicines Agency", evidenceType: "regulatory", url: "https://www.ema.europa.eu/en/medicines/human/referrals/ulipristal-acetate-5mg-medicinal-products", jurisdiction: "EU" },
  { key: "ipledge", title: "iPLEDGE REMS (isotretinoin risk management program)", organization: "iPLEDGE Program / U.S. FDA REMS", evidenceType: "regulatory", url: "https://www.ipledgeprogram.com/", jurisdiction: "US" },
  { key: "toxinfo", title: "Tox Info Suisse — Swiss national poisons information centre (emergency number 145)", organization: "Tox Info Suisse", evidenceType: "guideline", url: "https://www.toxinfo.ch/", jurisdiction: "CH" },
  { key: "nhs_medicines", title: "NHS medicines A to Z", organization: "NHS England", evidenceType: "guideline", url: "https://www.nhs.uk/medicines/", jurisdiction: "UK" },
  { key: "medlineplus", title: "MedlinePlus — Drugs, Herbs and Supplements", organization: "U.S. National Library of Medicine", evidenceType: "guideline", url: "https://medlineplus.gov/druginformation.html", jurisdiction: "US" },
  // Added 2026-10-05 for "Find medicines by condition" (URLs verified HTTP 200 on 2026-10-05)
  { key: "nhs_burns", title: "Burns and scalds — first aid, when to seek help, and pain relief", organization: "NHS England", publicationDate: "2026-03-31", evidenceType: "guideline", url: "https://www.nhs.uk/conditions/burns-and-scalds/", jurisdiction: "UK" },
  { key: "nhs_sunburn", title: "Sunburn — self-care and when to get urgent advice", organization: "NHS England", publicationDate: "2025-11-24", evidenceType: "guideline", url: "https://www.nhs.uk/conditions/sunburn/", jurisdiction: "UK" },
  { key: "who_burns", title: "Burns — fact sheet", organization: "World Health Organization", evidenceType: "guideline", url: "https://www.who.int/news-room/fact-sheets/detail/burns" },
  { key: "nhs_heartburn", title: "Heartburn and acid reflux — pharmacy medicines (antacids, alginates) and GP treatment (PPIs)", organization: "NHS England", evidenceType: "guideline", url: "https://www.nhs.uk/conditions/heartburn-and-acid-reflux/", jurisdiction: "UK" },
  { key: "label_ssd", title: "Silver sulfadiazine cream USP 1% — prescribing information (indication: adjunct for prevention and treatment of wound sepsis in second- and third-degree burns)", organization: "U.S. National Library of Medicine / DailyMed", evidenceType: "regulatory", url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b4d6694f-2b0a-4d64-9e05-2fef6d8e60d9", jurisdiction: "US" },
  { key: "label_pvpi_firstaid", title: "Povidone-iodine 10% first aid antiseptic — Drug Facts (uses: help prevent infection in minor cuts, scrapes, burns)", organization: "U.S. National Library of Medicine / DailyMed", evidenceType: "regulatory", url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2f07152-d7fb-4b1f-be77-c94618d5abd6", jurisdiction: "US" },
  { key: "label_caco3_antacid", title: "Calcium carbonate antacid chewable tablets — Drug Facts (uses: heartburn, acid indigestion, sour stomach)", organization: "U.S. National Library of Medicine / DailyMed", evidenceType: "regulatory", url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=15d3c559-2366-49b8-93ec-60a25dbde14d", jurisdiction: "US" },
  { key: "label_lidocaine_burn", title: "Lidocaine HCl 2% burn gel — Drug Facts (use: temporary pain relief for minor burns)", organization: "U.S. National Library of Medicine / DailyMed", evidenceType: "regulatory", url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e9d3e9be-1036-fad0-e053-2a95a90a6efe", jurisdiction: "US" },
];
