// Medication synonyms DSL. Fields are "|"-separated strings.
// b: brands "Name@REG1,REG2" ; intl: international/alternative INN ; abbr ; miss: misspellings ; de/fr/it: language forms
export const MED_SYN_1 = {
  "Paracetamol (Acetaminophen)": { intl: "paracetamol|acetaminophen", abbr: "APAP", b: "Dafalgan@CH|Panadol@CH,UK|Ben-u-ron@CH,DE|Acetalgin@CH|Tylenol@US|Calpol@UK|Doliprane@FR|Efferalgan@FR|Tachipirina@IT", miss: "paracetemol|paracetamole|paracetomol|parecetamol|paracetamal|acetominophen|acetaminophin|acetaminofen|acetamenophen", it: "paracetamolo" },
  "Ibuprofen": { b: "Algifor@CH|Irfen@CH|Dolocyl@CH|Advil@US,CH|Nurofen@UK,DE,CH|Motrin@US|Brufen@UK|Dolormin@DE|Moment@IT", miss: "ibuprofin|ibuprophen|ibuprofren|ibruprofen|iboprofen|ibuprofan|ibuprofine|ibuprophin", fr: "ibuprofène", it: "ibuprofene" },
  "Naproxen": { b: "Aleve@US,CH,DE|Naprosyn@US,UK|Proxen@CH,DE|Apranax@CH", miss: "naproxin|naproxan|naproxene", it: "naprossene" },
  "Aspirin (low-dose / antiplatelet)": { intl: "acetylsalicylic acid", abbr: "ASA|ASS", b: "Aspirin@CH,DE,US|Aspirin Cardio@CH|Bayer Aspirin@US|Disprin@UK", de: "Acetylsalicylsäure", fr: "aspirine|acide acétylsalicylique", it: "acido acetilsalicilico|aspirina", miss: "asprin|aspirine" },
  "Metamizole (Dipyrone)": { intl: "dipyrone|metamizole sodium", b: "Novalgin@CH,DE|Minalgin@CH|Nolotil@ES", de: "Metamizol|Novaminsulfon", it: "metamizolo", miss: "metamizon|metamisol|metamizole sodium" },
  "Diclofenac": { b: "Voltaren@CH,DE,US|Voltarol@UK|Inflamac@CH|Olfen@CH|Ecofenac@CH|Cataflam@US,CH", miss: "diclofenak|diclophenac|diclofenec|diclofanac" },
  "Mefenamic acid": { b: "Ponstan@CH,UK|Ponstel@US", de: "Mefenaminsäure", fr: "acide méfénamique", it: "acido mefenamico", miss: "mefanamic acid|mefenamic" },
  "Etoricoxib": { b: "Arcoxia@CH,EU,UK", miss: "etoricoxsib|etorocoxib" },
  "Celecoxib": { b: "Celebrex@US,CH,EU", miss: "celecoxcib|celecoxeb|celocoxib" },
  "Meloxicam": { b: "Mobic@US|Mobicox@CH", miss: "meloxicame|meloxicam" },
  "Indomethacin": { intl: "indometacin", miss: "indomethacine|indomethicin" },
  "Ketorolac": { b: "Toradol@US", miss: "ketorolak|ketoralac" },
  "Tramadol": { b: "Tramal@CH,DE|Ultram@US|Zydol@UK", miss: "tramadole|tramodol|tramadal", it: "tramadolo" },
  "Tapentadol": { b: "Palexia@CH,EU,UK|Nucynta@US", miss: "tapendatol|tapentadal" },
  "Codeine": { de: "Codein|Kodein", it: "codeina", miss: "codine|codiene" },
  "Morphine": { b: "MST Continus@UK|Sevredol@CH,DE,UK|Oramorph@UK|MS Contin@US", de: "Morphin", it: "morfina", miss: "morfine|morphene" },
  "Oxycodone": { b: "OxyContin@US,CH,UK|OxyNorm@CH,UK,DE", de: "Oxycodon", miss: "oxycodon|oxicodone|oxycontine" },
  "Hydromorphone": { b: "Palladon@CH,DE|Dilaudid@US", de: "Hydromorphon", miss: "hydromorphon|hydromorfone" },
  "Fentanyl": { b: "Durogesic@CH,EU,UK|Duragesic@US|Actiq@US,EU", miss: "fentanil|fentanyle|phentanyl" },
  "Buprenorphine": { b: "Temgesic@CH,EU,UK|Subutex@CH,EU,US|Transtec@CH,EU|Butrans@US,UK", de: "Buprenorphin", miss: "buprenorphin|buprenorfine" },
  "Methadone": { b: "Ketalgin@CH|Dolophine@US", de: "Methadon", it: "metadone", miss: "methodone|metadon" },
  "Naloxone": { b: "Narcan@US,UK", de: "Naloxon", miss: "naloxon|naloxine" },
  "Hydrocodone": { b: "Hysingla@US", miss: "hydrocodon|hidrocodone" },
  "Omeprazole": { b: "Prilosec@US|Antramups@CH|Losec@UK,EU|Antra@DE", de: "Omeprazol", it: "omeprazolo", miss: "omeprazol|omeprazole|omprazole|omeprazolle|omeprezole|omeparazole" },
  "Pantoprazole": { b: "Pantozol@CH,DE|Zurcal@CH|Protonix@US|Pantoloc@AT", de: "Pantoprazol", it: "pantoprazolo", miss: "pantaprazole|pantoprazol|pantoprazole sodium|pantoprozole" },
  "Esomeprazole": { b: "Nexium@CH,US,UK,EU", de: "Esomeprazol", it: "esomeprazolo", miss: "esomeprazol|esomeprezole|esomaprazole" },
  "Lansoprazole": { b: "Agopton@CH,DE|Prevacid@US|Zoton@UK", de: "Lansoprazol", miss: "lansoprazol|lanzoprazole" },
  "Rabeprazole": { b: "Pariet@CH,EU,UK|Aciphex@US", de: "Rabeprazol" },
  "Famotidine": { b: "Pepcid@US", de: "Famotidin" },
  "Atorvastatin": { b: "Sortis@CH,DE|Lipitor@US,UK", fr: "atorvastatine", it: "atorvastatina", miss: "atorvastin|atorvostatin|atrovastatin|atorvastatine|atorvastain|atorvastatin calcium" },
  "Rosuvastatin": { b: "Crestor@CH,US,UK,EU", fr: "rosuvastatine", it: "rosuvastatina", miss: "rosuvastin|rosuvastatine|rosuvastain|rosuvistatin" },
  "Simvastatin": { b: "Zocor@CH,US,UK", fr: "simvastatine", it: "simvastatina", miss: "simvastin|simvistatin|simvastatine" },
  "Pravastatin": { b: "Selipran@CH|Pravachol@US|Pravasin@DE", fr: "pravastatine", it: "pravastatina" },
  "Pitavastatin": { b: "Livazo@CH,EU,UK|Livalo@US" },
  "Lovastatin": { b: "Mevacor@US", fr: "lovastatine" },
  "Ezetimibe": { b: "Ezetrol@CH,EU,UK|Zetia@US", de: "Ezetimib", miss: "ezetemibe|ezetimib|ezitimibe" },
  "Fenofibrate": { b: "Lipanthyl@CH,FR|Tricor@US", de: "Fenofibrat" },
  "Evolocumab": { b: "Repatha@CH,US,EU,UK" },
  "Apixaban": { b: "Eliquis@CH,US,UK,EU", miss: "apixiban|apixeban|apixaben|apexaban" },
  "Rivaroxaban": { b: "Xarelto@CH,US,UK,EU", miss: "rivaroxiban|rivaroxaben|rivaroxoban|rivoroxaban" },
  "Edoxaban": { b: "Lixiana@CH,EU,UK|Savaysa@US", miss: "edoxiban|edoxaben" },
  "Dabigatran": { b: "Pradaxa@CH,US,UK,EU", miss: "dabigatren|dabigatan" },
  "Warfarin": { b: "Coumadin@US", fr: "warfarine", miss: "warfrin|warferin|warfarine|wafarin" },
  "Phenprocoumon": { b: "Marcoumar@CH|Marcumar@DE|Falithrom@DE", miss: "phenprocoumone|fenprocoumon|phenprocumon|phenprocoumen|marcumar" },
  "Acenocoumarol": { b: "Sintrom@CH,EU", miss: "acenocoumarole|acenocumarol" },
  "Enoxaparin": { b: "Clexane@CH,EU,UK|Lovenox@US", miss: "enoxoparin|enoxaparine" },
  "Heparin (unfractionated)": { b: "Liquemin@CH", fr: "héparine", it: "eparina", miss: "heparine" },
  "Clopidogrel": { b: "Plavix@CH,US,UK,EU", miss: "clopidrogel|clopidigrel|clopidogrel bisulfate|clopidogral|clopedogrel" },
  "Prasugrel": { b: "Efient@CH,EU,UK|Effient@US" },
  "Ticagrelor": { b: "Brilique@CH,EU,UK|Brilinta@US", miss: "ticagralor|ticagreler" },
  "Levothyroxine": { intl: "L-thyroxine|thyroxine", abbr: "T4", b: "Euthyrox@CH,DE|Eltroxin@CH|Synthroid@US|Tirosint@US|L-Thyroxin Henning@DE", de: "Levothyroxin|L-Thyroxin", it: "levotiroxina", miss: "levothyroxin|levothyroxene|levothroxine|levothyroxin sodium|levothyroxine sodium|levothyrixine" },
  "Metformin": { b: "Glucophage@CH,US,UK,EU", fr: "metformine", it: "metformina", miss: "metformine|metforman|metphormin|metfomin|metformin hcl" },
  "Insulin glargine": { b: "Lantus@CH,US,UK,EU|Toujeo@CH,US,EU|Abasaglar@CH,EU|Basaglar@US", de: "Insulin Glargin", miss: "insulin glargin|glargine" },
  "Insulin aspart": { b: "NovoRapid@CH,EU,UK|NovoLog@US|Fiasp@CH,EU,US" },
  "Empagliflozin": { b: "Jardiance@CH,US,UK,EU", miss: "empagliflocin|empaglifozin|empagliflozine" },
  "Dapagliflozin": { b: "Forxiga@CH,EU,UK|Farxiga@US", miss: "dapaglifozin|dapagliflocin|dapagliflozine" },
  "Canagliflozin": { b: "Invokana@CH,US,EU" },
  "Sitagliptin": { b: "Januvia@CH,US,UK,EU", fr: "sitagliptine", miss: "sitagliptine|sitaglipton" },
  "Gliclazide": { b: "Diamicron@CH,EU,UK", de: "Gliclazid" },
  "Semaglutide": { b: "Ozempic@CH,US,UK,EU|Wegovy@CH,US,UK,EU|Rybelsus@CH,US,EU", de: "Semaglutid", miss: "semaglutid|semaglitide|semaglutyde|ozempik" },
  "Liraglutide": { b: "Victoza@CH,US,EU|Saxenda@CH,US,EU", de: "Liraglutid" },
  "Dulaglutide": { b: "Trulicity@CH,US,EU", de: "Dulaglutid" },
  "Tirzepatide": { b: "Mounjaro@CH,US,UK,EU|Zepbound@US", de: "Tirzepatid", miss: "tirzepetide|terzepatide" },
  "Amlodipine": { b: "Norvasc@CH,US|Istin@UK", de: "Amlodipin", it: "amlodipina", miss: "amlodipin|amlodipene|amlodapine|amlodopine|amlodipine besylate" },
  "Lisinopril": { b: "Zestril@CH,US,UK|Prinivil@US", miss: "lisinipril|lisinoprel|lysinopril|lisinopril" },
  "Ramipril": { b: "Triatec@CH|Altace@US|Delix@DE|Tritace@UK", miss: "ramapril|rampril" },
  "Enalapril": { b: "Reniten@CH|Vasotec@US", miss: "enalopril|enalpril" },
  "Perindopril": { b: "Coversum@CH|Coversyl@UK,FR|Aceon@US" },
  "Losartan": { b: "Cosaar@CH|Cozaar@US,UK|Lorzaar@DE", miss: "losarten|losartin|lozartan" },
  "Candesartan": { b: "Atacand@CH,US,UK|Blopress@CH,DE", miss: "candasartan|candesarten" },
  "Valsartan": { b: "Diovan@CH,US,UK,EU", miss: "valsartin|valsarten" },
  "Irbesartan": { b: "Aprovel@CH,EU,UK|Avapro@US" },
  "Olmesartan": { b: "Olmetec@CH,EU,UK|Benicar@US|Votum@DE" },
  "Telmisartan": { b: "Micardis@CH,US,EU" },
  "Metoprolol": { b: "Beloc Zok@CH|Beloc-Zok@DE|Lopresor@CH,UK|Lopressor@US|Toprol-XL@US", miss: "metroprolol|metaprolol|metoprolol succinate|metoprolol tartrate|metoprolo" },
  "Bisoprolol": { b: "Concor@CH,DE,EU|Cardicor@UK", miss: "bisaprolol|bisoprolo|bisoprolol fumarate" },
  "Atenolol": { b: "Tenormin@CH,US,UK", miss: "atenolo|atenalol" },
  "Carvedilol": { b: "Dilatrend@CH,DE|Coreg@US", miss: "carvedolol|carvidilol" },
  "Nebivolol": { b: "Nebilet@CH,DE|Bystolic@US", miss: "nebivolo|nebivelol" },
  "Propranolol": { b: "Inderal@CH,US,UK|Dociton@DE", miss: "propanolol|propranalol|propranolo|proprenolol" },
  "Labetalol": { b: "Trandate@CH,UK,US" },
  "Hydrochlorothiazide": { abbr: "HCTZ", b: "Esidrex@CH|Microzide@US", de: "Hydrochlorothiazid", miss: "hydrochlorthiazide|hydrochlorothiazid|hydrochlorothiazine" },
  "Furosemide": { intl: "frusemide", b: "Lasix@CH,US,UK,DE", de: "Furosemid", miss: "furosemid|furosimide|furosamide|furosemide" },
  "Torsemide": { intl: "torasemide", b: "Torem@CH,DE|Demadex@US", de: "Torasemid", miss: "torasemid|torsamide" },
  "Indapamide": { b: "Fludex@CH,FR|Natrilix@UK", de: "Indapamid" },
  "Chlorthalidone": { intl: "chlortalidone", b: "Hygroton@CH,DE", de: "Chlortalidon" },
  "Spironolactone": { b: "Aldactone@CH,US,UK,EU", de: "Spironolacton", miss: "spirolactone|spironolacton|spironolactone|spironalactone" },
  "Eplerenone": { b: "Inspra@CH,US,UK,EU", de: "Eplerenon" },
  "Bumetanide": { b: "Burinex@EU,UK|Bumex@US", de: "Bumetanid" },
  "Diltiazem": { b: "Dilzem@CH,DE|Cardizem@US|Tildiem@UK" },
  "Verapamil": { b: "Isoptin@CH,DE,EU|Calan@US" },
  "Nifedipine": { b: "Adalat@CH,UK,DE|Procardia@US", de: "Nifedipin" },
  "Felodipine": { b: "Plendil@CH,US,UK", de: "Felodipin" },
  "Doxazosin": { b: "Cardura@CH,US,UK" },
  "Clonidine": { b: "Catapresan@CH,DE|Catapres@US,UK", de: "Clonidin" },
  "Digoxin": { b: "Lanoxin@US,UK", fr: "digoxine" },
  "Amiodarone": { b: "Cordarone@CH,EU|Pacerone@US", de: "Amiodaron", miss: "amiodaron|amiodarane|amioderone" },
  "Flecainide": { b: "Tambocor@CH,UK,US", de: "Flecainid" },
  "Sotalol": { b: "Sotalex@CH,DE|Betapace@US" },
  "Ivabradine": { b: "Procoralan@CH,EU,UK|Corlanor@US", de: "Ivabradin" },
  "Nitroglycerin (glyceryl trinitrate)": { intl: "glyceryl trinitrate|nitroglycerin|nitroglycerine", abbr: "GTN", b: "Nitrolingual@CH,DE,UK|Deponit@CH,DE|Nitrostat@US", fr: "trinitrine", miss: "nitroglycerine|nitroglycerin spray" },
  "Isosorbide mononitrate": { abbr: "ISMN", b: "Imdur@US,UK", de: "Isosorbidmononitrat" },
  "Sacubitril/valsartan": { b: "Entresto@CH,US,UK,EU" },
};
