export const MED_SYN_2 = {
  "Sertraline": { b: "Zoloft@CH,US|Lustral@UK", de: "Sertralin", it: "sertralina", miss: "sertaline|sertralin|setraline|sertrline" },
  "Escitalopram": { b: "Cipralex@CH,EU,UK|Lexapro@US", miss: "escitalipram|escitalopran|escitolopram|escitalapram" },
  "Citalopram": { b: "Seropram@CH|Celexa@US|Cipramil@UK,DE", miss: "citalopran|citalapram" },
  "Fluoxetine": { b: "Prozac@US,UK|Fluctine@CH", de: "Fluoxetin", it: "fluoxetina", miss: "fluoxitine|fluoxetin|fluoxatine|floxetine" },
  "Paroxetine": { b: "Deroxat@CH,FR|Paxil@US|Seroxat@UK", de: "Paroxetin", miss: "paroxitine|paroxetin" },
  "Fluvoxamine": { b: "Floxyfral@CH,FR|Luvox@US", de: "Fluvoxamin" },
  "Venlafaxine": { b: "Efexor@CH,EU,UK|Effexor@US", de: "Venlafaxin", miss: "venlafaxin|venlafaxene|venlaflaxine" },
  "Desvenlafaxine": { b: "Pristiq@US" },
  "Duloxetine": { b: "Cymbalta@CH,US,UK,EU", de: "Duloxetin", miss: "duloxetin|duloxatine|duloxitine" },
  "Mirtazapine": { b: "Remeron@CH,US|Zispin@UK", de: "Mirtazapin", miss: "mirtazepine|mirtazapin|mirtazipine" },
  "Trazodone": { b: "Trittico@CH,IT|Desyrel@US", de: "Trazodon", miss: "trazadone|trazodon|trazedone" },
  "Bupropion": { b: "Wellbutrin@CH,US|Zyban@CH,UK,US", miss: "buproprion|bupropian|bupropione" },
  "Vortioxetine": { b: "Brintellix@CH,EU,UK|Trintellix@US", de: "Vortioxetin" },
  "Amitriptyline": { b: "Saroten@CH,DE|Elavil@US", de: "Amitriptylin", miss: "amitryptiline|amitriptiline|amitryptyline|amitriptylin" },
  "Quetiapine": { b: "Seroquel@CH,US,UK,EU", de: "Quetiapin", miss: "quetiepine|quetapine|quetiapin|quetiapene" },
  "Olanzapine": { b: "Zyprexa@CH,US,UK,EU", de: "Olanzapin", miss: "olanzepine|olanzapin" },
  "Risperidone": { b: "Risperdal@CH,US,UK,EU", de: "Risperidon", miss: "risperidon|risperdone|resperidone" },
  "Aripiprazole": { b: "Abilify@CH,US,UK,EU", de: "Aripiprazol", miss: "aripiprazol|aripriprazole|aripiprazol" },
  "Clozapine": { b: "Leponex@CH,DE|Clozaril@US,UK", de: "Clozapin" },
  "Haloperidol": { b: "Haldol@CH,US,EU" },
  "Lithium carbonate": { intl: "lithium", b: "Priadel@UK", miss: "lithum" },
  "Valproate (valproic acid / divalproex)": { intl: "valproic acid|sodium valproate|divalproex|valproate", b: "Depakine@CH,EU|Depakote@US|Epilim@UK", de: "Valproinsäure|Valproat", fr: "acide valproïque", miss: "valproat|valporate" },
  "Lamotrigine": { b: "Lamictal@CH,US,UK,EU", de: "Lamotrigin", miss: "lamotragine|lamotrigin|lamotrogine" },
  "Levetiracetam": { b: "Keppra@CH,US,UK,EU", miss: "levetiracitam|levetiracetem|levitiracetam" },
  "Carbamazepine": { b: "Tegretol@CH,US,UK,EU", de: "Carbamazepin", miss: "carbamazapine|carbamezepine|carbamazepin" },
  "Phenytoin": { b: "Phenhydan@CH,DE|Dilantin@US|Epanutin@UK", miss: "phenytoine|fenytoin|phenitoin" },
  "Topiramate": { b: "Topamax@CH,US,UK,EU", de: "Topiramat", miss: "topiramat|topirimate" },
  "Gabapentin": { b: "Neurontin@CH,US,UK,EU", fr: "gabapentine", miss: "gabapenton|gabapentine|gabapentn|gabapenten" },
  "Gabapentin enacarbil": { b: "Horizant@US" },
  "Pregabalin": { b: "Lyrica@CH,US,UK,EU", fr: "prégabaline", miss: "pregablin|pregabaline|pregabalen|pregabolin" },
  "Lorazepam": { b: "Temesta@CH,AT|Ativan@US,UK|Tavor@DE", miss: "lorazapam|lorazepan|lorezepam" },
  "Diazepam": { b: "Valium@CH,US,UK,DE|Stesolid@EU", miss: "diazapam|diazepan|diazepame" },
  "Oxazepam": { b: "Seresta@CH,FR|Serax@US", miss: "oxazapam|oxazepan" },
  "Alprazolam": { b: "Xanax@CH,US,UK,EU", miss: "alprazolan|alprazalam|alprozolam" },
  "Clonazepam": { b: "Rivotril@CH,EU|Klonopin@US", miss: "clonazapam|clonazepan" },
  "Temazepam": { b: "Restoril@US" },
  "Zolpidem": { b: "Stilnox@CH,EU|Ambien@US", miss: "zolpidam|zolpidem tartrate|zolpiden" },
  "Zopiclone": { b: "Imovane@CH,FR,UK", de: "Zopiclon", miss: "zopiclon|zopiclon|zopiclone" },
  "Eszopiclone": { b: "Lunesta@US" },
  "Melatonin": { b: "Circadin@CH,EU,UK", fr: "mélatonine", miss: "melatonine|melotonin" },
  "Hydroxyzine": { b: "Atarax@CH,EU,UK|Vistaril@US", de: "Hydroxyzin", miss: "hydroxizine|hydroxyzin|hydroxyzene" },
  "Methylphenidate": { b: "Ritalin@CH,US,DE|Concerta@CH,US,EU|Medikinet@CH,DE", de: "Methylphenidat", miss: "methylphenidat|methylphenidate hcl|metylphenidate" },
  "Atomoxetine": { b: "Strattera@CH,US,EU", de: "Atomoxetin" },
  "Lisdexamfetamine": { b: "Elvanse@CH,EU,UK|Vyvanse@US", de: "Lisdexamfetamin" },
  "Amphetamine salts (mixed)": { b: "Adderall@US", miss: "aderall|adderal" },
  "Donepezil": { b: "Aricept@CH,US,UK,EU", miss: "donepizil|donepezel|donapezil" },
  "Memantine": { b: "Axura@CH,DE|Ebixa@CH,EU,UK|Namenda@US", de: "Memantin" },
  "Levodopa/carbidopa": { b: "Sinemet@CH,US,UK", de: "Levodopa/Carbidopa" },
  "Levodopa/benserazide": { b: "Madopar@CH,EU,UK" },
  "Pramipexole": { b: "Sifrol@CH,EU|Mirapex@US|Mirapexin@UK", de: "Pramipexol", miss: "pramipexol|pramipexol|pramipexile" },
  "Baclofen": { b: "Lioresal@CH,EU,UK", miss: "baclophen|bacoflen" },
  "Tizanidine": { b: "Sirdalud@CH,DE|Zanaflex@US", de: "Tizanidin" },
  "Betahistine": { b: "Betaserc@CH,EU,UK", de: "Betahistin", miss: "betahistin|betahistene|betahystine" },
  "Varenicline": { b: "Champix@CH,EU,UK|Chantix@US", de: "Vareniclin", miss: "vareniclin|verenicline" },
  "Nicotine replacement therapy": { abbr: "NRT", b: "Nicorette@CH,EU,UK,US|Nicotinell@CH,EU,UK|NiQuitin@UK,EU|Nicoderm CQ@US" },
  "Salbutamol (Albuterol)": { intl: "salbutamol|albuterol", b: "Ventolin@CH,UK,EU,US|ProAir@US|Proventil@US|Airomir@UK,EU", miss: "salbutemol|albuteral|salbutamole|albuterol sulfate" },
  "Budesonide/formoterol": { b: "Symbicort@CH,US,UK,EU", de: "Budesonid/Formoterol" },
  "Fluticasone (inhaled)": { b: "Axotide@CH|Flixotide@UK,EU|Flovent@US", de: "Fluticason" },
  "Fluticasone/salmeterol": { b: "Seretide@CH,EU,UK|Advair@US", miss: "seretid" },
  "Tiotropium": { b: "Spiriva@CH,US,UK,EU", miss: "tiotroprium|tiotropiun" },
  "Budesonide (inhaled)": { b: "Pulmicort@CH,US,UK,EU", de: "Budesonid" },
  "Beclomethasone (inhaled)": { intl: "beclometasone", b: "Qvar@CH,US,UK|Clenil@UK", de: "Beclometason" },
  "Beclometasone/formoterol": { b: "Foster@CH,EU,UK" },
  "Fluticasone furoate/vilanterol": { b: "Relvar Ellipta@CH,EU,UK|Breo Ellipta@US" },
  "Umeclidinium/vilanterol": { b: "Anoro Ellipta@CH,US,EU,UK" },
  "Ipratropium": { b: "Atrovent@CH,US,UK,EU" },
  "Montelukast": { b: "Singulair@CH,US,UK,EU", miss: "montelucast|montelukas|montelukast sodium|monteleukast" },
  "Mometasone (nasal)": { b: "Nasonex@CH,US,UK,EU", de: "Mometason" },
  "Cetirizine": { b: "Zyrtec@CH,US,UK,EU|Reactine@UK", de: "Cetirizin", it: "cetirizina", miss: "cetirizin|cetrizine|cetirazine|ceterizine|zirtec" },
  "Loratadine": { b: "Claritin@US|Clarityn@UK|Claritine@FR", de: "Loratadin", it: "loratadina", miss: "loratidine|loratadene|loratadin|loratidin" },
  "Desloratadine": { b: "Aerius@CH,EU,UK|Clarinex@US", de: "Desloratadin" },
  "Fexofenadine": { b: "Telfast@CH,EU,UK|Allegra@US", de: "Fexofenadin", miss: "fexofenadin|fexofenidine" },
  "Levocetirizine": { b: "Xyzal@CH,US,UK,EU", de: "Levocetirizin" },
  "Bilastine": { b: "Bilaxten@CH,EU", de: "Bilastin" },
  "Diphenhydramine": { b: "Benadryl@US", de: "Diphenhydramin" },
  "Xylometazoline": { b: "Otrivin@CH,DE,UK|Olynth@DE", de: "Xylometazolin", miss: "xylometazolin|xylomethazoline|xylometazolene" },
  "Acetylcysteine": { intl: "N-acetylcysteine", abbr: "NAC", b: "Fluimucil@CH,DE,EU|ACC@DE", de: "Acetylcystein", miss: "acetylcystein|acetylcisteine|acetylcysteine" },
  "Epinephrine (Adrenaline)": { intl: "adrenaline|epinephrine", b: "EpiPen@CH,US,UK,EU|Jext@CH,EU,UK|Anapen@EU,UK|Auvi-Q@US", de: "Adrenalin", it: "adrenalina", miss: "epinephrin|adrenalin" },
};
