export const MED_SYN_3 = {
  "Amoxicillin": { intl: "amoxycillin", b: "Clamoxyl@CH,FR|Amoxil@US,UK", fr: "amoxicilline", it: "amoxicillina", miss: "amoxicilin|amoxicillan|amoxacillin|amoxilin|amoxicillen|amoxycilin" },
  "Amoxicillin/clavulanate": { intl: "co-amoxiclav|amoxicillin clavulanic acid|amoxicillin-clavulanate", b: "Augmentin@CH,US,UK,EU", de: "Amoxicillin/Clavulansäure", miss: "augmentine|co amoxiclav" },
  "Azithromycin": { b: "Zithromax@CH,US,UK,EU|Z-Pak@US", fr: "azithromycine", it: "azitromicina", miss: "azithromicin|azithromicyn|azithromycine|azitromycin" },
  "Clarithromycin": { b: "Klacid@CH,EU,UK|Biaxin@US", fr: "clarithromycine", it: "claritromicina", miss: "clarithromicin|claritromycin|clarythromycin" },
  "Ciprofloxacin": { b: "Ciproxin@CH,UK|Cipro@US|Ciprobay@DE", fr: "ciprofloxacine", it: "ciprofloxacina", miss: "ciproflaxin|ciprofloxin|ciprofloxacine|ciproflox" },
  "Levofloxacin": { b: "Tavanic@CH,EU|Levaquin@US", fr: "lévofloxacine", miss: "levofloxin|levofloxacine|levoflaxacin" },
  "Moxifloxacin": { b: "Avalox@CH,DE|Avelox@US" },
  "Ofloxacin": { b: "Tarivid@CH,EU" },
  "Doxycycline": { b: "Vibramycin@CH,US,UK", de: "Doxycyclin", it: "doxiciclina", miss: "doxicycline|doxycyline|doxycyclin|doxycicline" },
  "Minocycline": { b: "Minocin@US,UK", de: "Minocyclin" },
  "Trimethoprim/sulfamethoxazole": { intl: "co-trimoxazole|cotrimoxazole|sulfamethoxazole trimethoprim", abbr: "TMP-SMX|SMX-TMP", b: "Bactrim@CH,US,EU|Septra@US", de: "Cotrimoxazol", miss: "cotrimoxazol|bactrim ds" },
  "Trimethoprim": { miss: "trimetoprim|trimethoprin" },
  "Nitrofurantoin": { b: "Macrobid@US|Macrodantin@US,UK|Furadantin@CH,EU|Uvamin@CH", miss: "nitrofurantion|nitrofuratoin|nitrofurantoine" },
  "Fosfomycin": { intl: "phosphomycin", b: "Monuril@CH,EU|Monurol@US", fr: "fosfomycine", miss: "fosfomicin|fosfomycine" },
  "Cefuroxime": { b: "Zinat@CH,EU|Zinnat@UK|Zinacef@CH,UK,US|Ceftin@US", de: "Cefuroxim", miss: "cefuroxim|cefuroxin|cefuroxine" },
  "Cefalexin (Cephalexin)": { intl: "cefalexin|cephalexin", b: "Keflex@US,UK", miss: "cephalexine|cefalexine|kefalex" },
  "Ceftriaxone": { b: "Rocephin@CH,US,EU", de: "Ceftriaxon", miss: "ceftriaxon|ceftriaxzone|ceftriaxone sodium" },
  "Phenoxymethylpenicillin (Penicillin V)": { intl: "penicillin V|penicillin VK|phenoxymethylpenicillin", b: "Ospen@CH,AT", miss: "penicilin|penecillin" },
  "Flucloxacillin": { intl: "floxacillin", b: "Floxapen@CH,UK", miss: "flucloxacilin|flucloxicillin" },
  "Clindamycin": { b: "Dalacin C@CH,EU,UK|Cleocin@US", fr: "clindamycine", miss: "clindamicin|clindamyacin" },
  "Metronidazole": { b: "Flagyl@CH,US,UK,EU", de: "Metronidazol", it: "metronidazolo", miss: "metronidazol|metranidazole|metronidazole|metronizadole" },
  "Vancomycin": { b: "Vancocin@CH,US,UK", miss: "vancomicin|vancomycine" },
  "Gentamicin": { miss: "gentamycin|gentamicine" },
  "Linezolid": { b: "Zyvox@US|Zyvoxid@CH,EU" },
  "Rifampin": { intl: "rifampicin|rifampin", b: "Rifadin@US,UK|Rimactan@CH", miss: "rifampicine|rifampacin" },
  "Rifaximin": { b: "Xifaxan@US,CH,UK" },
  "Aciclovir (Acyclovir)": { intl: "aciclovir|acyclovir", b: "Zovirax@CH,US,UK,EU", miss: "acyclovier|aciclovier|acylovir" },
  "Valaciclovir (Valacyclovir)": { intl: "valaciclovir|valacyclovir", b: "Valtrex@CH,US,UK", miss: "valacyclovier|valaciclovier|valcyclovir" },
  "Oseltamivir": { b: "Tamiflu@CH,US,UK,EU", miss: "oseltamavir|oseltamivier|osaltamivir" },
  "Fluconazole": { b: "Diflucan@CH,US,UK,EU", de: "Fluconazol", miss: "fluconazol|flucanazole|fluconozole|flukonazol" },
  "Terbinafine": { b: "Lamisil@CH,US,UK,EU", de: "Terbinafin", miss: "terbinafin|terbenafine" },
  "Clotrimazole": { b: "Canesten@CH,UK,EU|Lotrimin@US", de: "Clotrimazol", miss: "clotrimazol|clotrimazol|clotrimazole" },
  "Mebendazole": { b: "Vermox@CH,US,UK,EU", de: "Mebendazol" },
  "Hydroxychloroquine": { b: "Plaquenil@CH,US,UK,EU", de: "Hydroxychloroquin", miss: "hydroxychlorquine|hydroxycloroquine|hydroxychloroquin|hydroxichloroquine" },
  "Isoniazid": { abbr: "INH" },
  "Allopurinol": { b: "Zyloric@CH,EU,UK|Zyloprim@US", miss: "allopurinal|allopurino|alopurinol" },
  "Febuxostat": { b: "Adenuric@CH,EU,UK|Uloric@US" },
  "Colchicine": { b: "Colcrys@US", de: "Colchicin", miss: "colchicin|cholchicine|colchacine" },
  "Alendronate": { intl: "alendronic acid", b: "Fosamax@CH,US,UK,EU", de: "Alendronsäure|Alendronat", miss: "alendronat|alendronate sodium" },
  "Risedronate": { intl: "risedronic acid", b: "Actonel@CH,US,UK,EU", de: "Risedronat" },
  "Zoledronic acid": { b: "Aclasta@CH,EU,UK|Zometa@CH,US,EU|Reclast@US", de: "Zoledronsäure", miss: "zoledronate" },
  "Denosumab": { b: "Prolia@CH,US,UK,EU|Xgeva@CH,US,EU" },
  "Vitamin D3 (Cholecalciferol)": { intl: "cholecalciferol|colecalciferol|vitamin D3", de: "Colecalciferol" },
  "Methotrexate (low-dose rheumatologic)": { intl: "methotrexate", abbr: "MTX", b: "Metoject@CH,EU,UK|Trexall@US|Otrexup@US", de: "Methotrexat", miss: "methotrexat|metotrexate|methotrexete" },
  "Azathioprine": { b: "Imurek@CH,DE|Imuran@US,UK", de: "Azathioprin", miss: "azathioprin|azathiaprine" },
  "Cyclosporine": { intl: "ciclosporin|cyclosporin", b: "Sandimmun@CH,EU|Sandimmune@US|Neoral@CH,US,UK", miss: "cyclosporin|ciclosporine" },
  "Tacrolimus": { b: "Prograf@CH,US,UK,EU|Advagraf@CH,EU,UK|Protopic@CH,US,EU" },
  "Adalimumab": { b: "Humira@CH,US,UK,EU|Amgevita@CH,EU|Hyrimoz@CH,EU,US|Imraldi@EU,UK" },
  "Prednisone / Prednisolone": { intl: "prednisone|prednisolone", de: "Prednison|Prednisolon", it: "prednisone", miss: "prednizone|prednisolon|prednisalone|predisone" },
  "Methylprednisolone": { b: "Medrol@CH,US,UK,EU|Solu-Medrol@CH,US,EU", de: "Methylprednisolon" },
  "Dexamethasone": { b: "Fortecortin@CH,DE|Decadron@US", de: "Dexamethason", miss: "dexamethason|dexamethazone|dexametasone" },
  "Sumatriptan": { b: "Imigran@CH,EU,UK|Imitrex@US", miss: "sumatriptin|sumitriptan|sumatripton" },
  "Rizatriptan": { b: "Maxalt@CH,US,UK,EU", miss: "rizatriptin|risatriptan" },
  "Ondansetron": { b: "Zofran@CH,US,UK,EU", miss: "ondansatron|ondansetrone|ondansteron|ondasetron" },
  "Metoclopramide": { b: "Paspertin@CH,DE,AT|Reglan@US|Maxolon@UK", de: "Metoclopramid", miss: "metaclopramide|metoclopramid|metoclopromide" },
  "Domperidone": { b: "Motilium@CH,EU,UK", de: "Domperidon", miss: "domperidon|domperidome|domperidine" },
  "Loperamide": { b: "Imodium@CH,US,UK,EU", de: "Loperamid", miss: "loperamid|loparamide|loperimide" },
  "Butylscopolamine (Hyoscine butylbromide)": { intl: "hyoscine butylbromide|butylscopolamine|scopolamine butylbromide", b: "Buscopan@CH,UK,EU", de: "Butylscopolamin" },
  "Mesalazine (Mesalamine)": { intl: "mesalazine|mesalamine|5-ASA", b: "Asacol@CH,UK|Pentasa@CH,US,UK,EU|Salofalk@CH,DE,UK|Lialda@US", de: "Mesalazin", miss: "mesalazin|mesalamin" },
  "Macrogol (Polyethylene glycol)": { intl: "macrogol|polyethylene glycol", abbr: "PEG", b: "Movicol@CH,UK,EU|Transipeg@CH|MiraLAX@US", miss: "movicolon|macrogol 3350" },
  "Lactulose": { b: "Duphalac@CH,EU,UK", miss: "lactulos|lactulosa" },
  "Bisacodyl": { b: "Dulcolax@CH,US,UK,EU", miss: "bisacodil|bisacadyl" },
  "Ursodeoxycholic acid": { intl: "ursodiol", abbr: "UDCA", b: "Ursofalk@CH,DE,UK|Actigall@US|Urso@US", de: "Ursodeoxycholsäure" },
  "Tamsulosin": { b: "Pradif@CH|Flomax@US|Omnic@EU", miss: "tamsulosine|tamsolusin|tamsulosin hcl|tamsolosin" },
  "Finasteride": { b: "Proscar@CH,US,UK,EU|Propecia@CH,US,UK,EU", de: "Finasterid", miss: "finasterid|finastaride|finesteride" },
  "Dutasteride": { b: "Avodart@CH,US,UK,EU", de: "Dutasterid" },
  "Sildenafil": { b: "Viagra@CH,US,UK,EU|Revatio@CH,US,EU", miss: "sildenafill|sildenofil|sildanafil" },
  "Tadalafil": { b: "Cialis@CH,US,UK,EU|Adcirca@US", miss: "tadalafill|tadalefil|tadalifil" },
  "Solifenacin": { b: "Vesicare@CH,US,UK,EU", miss: "solifenacine|solifenecin" },
  "Mirabegron": { b: "Betmiga@CH,EU,UK|Myrbetriq@US" },
  "Oxybutynin": { b: "Ditropan@CH,US|Kentera@CH,EU", miss: "oxybutinin|oxybutynine" },
  "Estradiol": { intl: "oestradiol", b: "Estrofem@CH,EU|Oestrogel@CH,UK,EU|Estrogel@US|Estradot@CH,EU", miss: "estradiole|estradial" },
  "Progesterone (micronised)": { intl: "progesterone|micronized progesterone", b: "Utrogestan@CH,EU,UK|Prometrium@US", de: "Progesteron" },
  "Desogestrel (progestogen-only pill)": { intl: "desogestrel", b: "Cerazette@CH,EU,UK" },
  "Ulipristal acetate": { intl: "ulipristal", b: "ellaOne@CH,EU,UK|ella@US", de: "Ulipristalacetat" },
  "Levonorgestrel emergency contraception": { intl: "levonorgestrel", b: "NorLevo@CH,EU|Plan B One-Step@US|Levonelle@UK" },
  "Medroxyprogesterone acetate": { abbr: "DMPA|MPA", b: "Depo-Provera@CH,US,UK,EU|Sayana Press@UK,EU|Provera@US,UK", de: "Medroxyprogesteronacetat" },
  "Isotretinoin": { b: "Roaccutan@CH,DE|Roaccutane@UK|Claravis@US|Absorica@US|Accutane@US", miss: "isotretinon|isotrentinoin|isotretinion|isotretinoine" },
  "Tranexamic acid": { abbr: "TXA", b: "Cyklokapron@CH,UK,EU,US|Lysteda@US", de: "Tranexamsäure", fr: "acide tranexamique", it: "acido tranexamico", miss: "tranexamic|tranexemic acid" },
  "Folic acid": { intl: "folate|vitamin B9", de: "Folsäure", fr: "acide folique", it: "acido folico" },
  "Ferric carboxymaltose": { b: "Ferinject@CH,EU,UK|Injectafer@US", de: "Eisencarboxymaltose" },
  "Ferrous sulfate": { intl: "ferrous sulphate|iron sulfate", b: "Tardyferon@CH,EU", de: "Eisensulfat|Eisen(II)-sulfat" },
  "Testosterone": { b: "Testogel@CH,EU,UK|AndroGel@US|Nebido@CH,EU,UK|Testim@US", de: "Testosteron" },
  "Tamoxifen": { b: "Nolvadex@CH,US,UK", miss: "tamoxiphen|tamoxifene" },
  "Letrozole": { b: "Femara@CH,US,UK,EU", de: "Letrozol", miss: "letrazole|letrozol" },
  "Lidocaine": { intl: "lignocaine|lidocaine", b: "Xylocaine@CH,US,UK,EU|Xylocain@DE|Versatis@UK", de: "Lidocain", it: "lidocaina", miss: "lidocain|lidocane|lydocaine" },
  "Potassium chloride": { abbr: "KCl", b: "Klor-Con@US", de: "Kaliumchlorid" },
  "St. John's wort": { intl: "hypericum|Hypericum perforatum|St Johns wort", de: "Johanniskraut", fr: "millepertuis", it: "iperico" },
  "Ranitidine (historical / withdrawn)": { b: "Zantac@US,UK" },
  "Oral contraceptives (combined) — class overview": { abbr: "COC|OCP" },
  "Paxlovid (nirmatrelvir/ritonavir)": { intl: "nirmatrelvir|nirmatrelvir/ritonavir" },
  "Insulin lispro": { b: "Humalog@CH,US,UK,EU|Lyumjev@CH,US,EU" },
  "Insulin degludec": { b: "Tresiba@CH,US,UK,EU" },
  "Glimepiride": { b: "Amaryl@CH,US,UK,EU", de: "Glimepirid", miss: "glimeperide|glimepirid" },
  "Linagliptin": { b: "Trajenta@CH,EU,UK|Tradjenta@US" },
  "Pioglitazone": { b: "Actos@CH,US,UK,EU", de: "Pioglitazon" },
};
